/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author mpma0
 */
public class TabelaCartaoMenu {

    public static final String SELECT
            = "SELECT JSON_QUERY(\n"
            + " concat(concat('{\"tb_id_beneficio\":\"',TB_ID_BENEFICIO),'\",'),\n"
            + " concat(concat('\"tb_id_programa\":\"',TB_ID_PROGRAMA),'\",')),\n"
            + " concat(concat('\"tb_ddd\":\"',TB_DDD),'\",')),\n"
            + " concat(concat('\"tb_regiao\":\"',TB_REGIAO),'\",')),\n"
            + " concat(concat('\"upr1_oi_cpp_minicial\":\"',UPR1_OI_CPP_MINICIAL),'\",')),\n"
            + " concat(concat('\"upr1_oi_cpp_regtorpedo\":\"',UPR1_OI_CPP_REGTORPEDO),'\",')),\n"
            + " concat(concat('\"upr1_oi_cpp_regligacao\":\"',UPR1_OI_CPP_REGLIGACAO),'\",')),\n"
            + " concat(concat('\"upr1_oi_cppcont_regligacaooimovel\":\"',UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL),'\",')),\n"
            + " concat(concat('\"upr1_oi_cppcont_regligacaooimovelfixo\":\"',UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO),'\",')),\n"
            + " concat(concat('\"upr1_oi_cppcont_regligacaomix\":\"',UPR1_OI_CPPCONT_REGLIGACAOMIX),'\",')),\n"
            + " concat(concat('\"upr1_oi_cpp_comousar\":\"',UPR1_OI_CPP_COMOUSAR),'\",')),\n"
            + " concat(concat('\"upr1_oi_crbdad5arbi_promodegrau_init2\":\"',UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2),'\",')),\n"
            + " concat(concat('\"upr1_oi_crbdad5d_recbonusmax_init2\":\"',UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2),'\",')),\n"
            + " concat(concat('\"upr1_oi_crbdad5d_recbonusmindegrau2_init2\":\"',UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2),'\",')),\n"
            + " concat(concat('\"upr1_oi_crbdad5d_recebonusmindegrau3_init2\":\"',UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2),'\",')),\n"
            + " concat(concat('\"upr1_oi_crbdad5d_recebebonusmindegrau2e3_init2\":\"',UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2),'\",')),\n"
            + " concat(concat('\"upr1_oi_crbdad5d_recebebonusmax3_init2\":\"',UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2),'\",')),\n"
            + " concat(concat('\"upr1_oi_cinfpromo_mensageminicial\":\"',UPR1_OI_CINFPROMO_MENSAGEMINICIAL),'\",')),\n"
            + " concat(concat('\"upr1_oi_cinfpromo_regtorpedo\":\"',UPR1_OI_CINFPROMO_REGTORPEDO),'\",')),\n"
            + " concat(concat('\"upr1_oi_cinfpromo_regligacao\":\"',UPR1_OI_CINFPROMO_REGLIGACAO),'\",')),\n"
            + " concat(concat('\"upr1_oi_cinfpromo_comousar\":\"',UPR1_OI_CINFPROMO_COMOUSAR),'\",')),\n"
            + " concat(concat('\"upr1_oi_cinfpromo_validadepromo\":\"',UPR1_OI_CINFPROMO_VALIDADEPROMO),'\",')),\n"
            + " concat(concat('\"upr1_oi_ccpop_promooicartao\":\"',UPR1_OI_CCPOP_PROMOOICARTAO),'\",')),\n"
            + " concat(concat('\"upr1_oi_cinfp_regdados\":\"',UPR1_OI_CINFP_REGDADOS),'\",')),\n"
            + " concat(concat('\"upr1_oi_cpp_regdados\":\"',UPR1_OI_CPP_REGDADOS),'\",')),\n"
            + " concat(concat('\"incentivo_oferta_pre\":\"',INCENTIVO_OFERTA_PRE),'\",')),\n"
            + " concat(concat('\"jacliente_sva\":\"',JACLIENTE_SVA),'\"}'))\n"
            + ",'$') as json,ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM TB_CARTAOMENU t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO TB_CARTAOMENU (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	UPR1_OI_CPP_MINICIAL,\n"
            + "	UPR1_OI_CPP_REGTORPEDO,\n"
            + "	UPR1_OI_CPP_REGLIGACAO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOMIX,\n"
            + "	UPR1_OI_CPP_COMOUSAR,\n"
            + "	UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2,\n"
            + "	UPR1_OI_CINFPROMO_MENSAGEMINICIAL,\n"
            + "	UPR1_OI_CINFPROMO_REGTORPEDO,\n"
            + "	UPR1_OI_CINFPROMO_REGLIGACAO,\n"
            + "	UPR1_OI_CINFPROMO_COMOUSAR,\n"
            + "	UPR1_OI_CINFPROMO_VALIDADEPROMO,\n"
            + "	UPR1_OI_CCPOP_PROMOOICARTAO,\n"
            + "	UPR1_OI_CINFP_REGDADOS,\n"
            + "	UPR1_OI_CPP_REGDADOS,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	JACLIENTE_SVA,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	UPR1_OI_CPP_MINICIAL,\n"
            + "	UPR1_OI_CPP_REGTORPEDO,\n"
            + "	UPR1_OI_CPP_REGLIGACAO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOMIX,\n"
            + "	UPR1_OI_CPP_COMOUSAR,\n"
            + "	UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2,\n"
            + "	UPR1_OI_CINFPROMO_MENSAGEMINICIAL,\n"
            + "	UPR1_OI_CINFPROMO_REGTORPEDO,\n"
            + "	UPR1_OI_CINFPROMO_REGLIGACAO,\n"
            + "	UPR1_OI_CINFPROMO_COMOUSAR,\n"
            + "	UPR1_OI_CINFPROMO_VALIDADEPROMO,\n"
            + "	UPR1_OI_CCPOP_PROMOOICARTAO,\n"
            + "	UPR1_OI_CINFP_REGDADOS,\n"
            + "	UPR1_OI_CPP_REGDADOS,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	JACLIENTE_SVA,\n"
            + "	?,\n"
            + "   DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + "	TB_ID_BENEFICIO VARCHAR2(2500) PATH '$.tb_id_beneficio',\n"
            + "	TB_ID_PROGRAMA VARCHAR2(2500) PATH '$.tb_id_programa',\n"
            + "	TB_DDD VARCHAR2(2500) PATH '$.tb_ddd',\n"
            + "	TB_REGIAO VARCHAR2(2500) PATH '$.tb_regiao',\n"
            + "	UPR1_OI_CPP_MINICIAL VARCHAR2(2500) PATH '$.upr1_oi_cpp_minicial',\n"
            + "	UPR1_OI_CPP_REGTORPEDO VARCHAR2(2500) PATH '$.upr1_oi_cpp_regtorpedo',\n"
            + "	UPR1_OI_CPP_REGLIGACAO VARCHAR2(2500) PATH '$.upr1_oi_cpp_regligacao',\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL VARCHAR2(2500) PATH '$.upr1_oi_cppcont_regligacaooimovel',\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO VARCHAR2(2500) PATH '$.upr1_oi_cppcont_regligacaooimovelfixo',\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOMIX VARCHAR2(2500) PATH '$.upr1_oi_cppcont_regligacaomix',\n"
            + "	UPR1_OI_CPP_COMOUSAR VARCHAR2(2500) PATH '$.upr1_oi_cpp_comousar',\n"
            + "	UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2 VARCHAR2(2500) PATH '$.upr1_oi_crbdad5arbi_promodegrau_init2',\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2 VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recbonusmax_init2',\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2 VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recbonusmindegrau2_init2',\n"
            + "	UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2 VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recebonusmindegrau3_init2',\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2 VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recebebonusmindegrau2e3_init2',\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2 VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recebebonusmax3_init2',\n"
            + "	UPR1_OI_CINFPROMO_MENSAGEMINICIAL VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_mensageminicial',\n"
            + "	UPR1_OI_CINFPROMO_REGTORPEDO VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_regtorpedo',\n"
            + "	UPR1_OI_CINFPROMO_REGLIGACAO VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_regligacao',\n"
            + "	UPR1_OI_CINFPROMO_COMOUSAR VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_comousar',\n"
            + "	UPR1_OI_CINFPROMO_VALIDADEPROMO VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_validadepromo',\n"
            + "	UPR1_OI_CCPOP_PROMOOICARTAO VARCHAR2(2500) PATH '$.upr1_oi_ccpop_promooicartao',\n"
            + "	UPR1_OI_CINFP_REGDADOS VARCHAR2(2500) PATH '$.upr1_oi_cinfp_regdados',\n"
            + "	UPR1_OI_CPP_REGDADOS VARCHAR2(2500) PATH '$.upr1_oi_cpp_regdados',\n"
            + "	INCENTIVO_OFERTA_PRE VARCHAR2(2500) PATH '$.incentivo_oferta_pre',\n"
            + "	JACLIENTE_SVA VARCHAR2(2500) PATH '$.jacliente_sva',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE TB_CARTAOMENU SET \n"
            + "	TB_ID_BENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_BENEFICIO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_BENEFICIO',json NUMBER(38,0) PATH '$.tb_id_beneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_ID_PROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_PROGRAMA as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_PROGRAMA',json NUMBER(38,0) PATH '$.tb_id_programa')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_DDD as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_DDD',json VARCHAR2(2500) PATH '$.tb_ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_REGIAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_REGIAO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_REGIAO',json VARCHAR2(2500) PATH '$.tb_regiao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CPP_MINICIAL = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CPP_MINICIAL as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CPP_MINICIAL',json VARCHAR2(2500) PATH '$.upr1_oi_cpp_minicial')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CPP_REGTORPEDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CPP_REGTORPEDO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CPP_REGTORPEDO',json VARCHAR2(2500) PATH '$.upr1_oi_cpp_regtorpedo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CPP_REGLIGACAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CPP_REGLIGACAO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CPP_REGLIGACAO',json VARCHAR2(2500) PATH '$.upr1_oi_cpp_regligacao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL',json VARCHAR2(2500) PATH '$.upr1_oi_cppcont_regligacaooimovel')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO',json VARCHAR2(2500) PATH '$.upr1_oi_cppcont_regligacaooimovelfixo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOMIX = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CPPCONT_REGLIGACAOMIX as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CPPCONT_REGLIGACAOMIX',json VARCHAR2(2500) PATH '$.upr1_oi_cppcont_regligacaomix')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CPP_COMOUSAR = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CPP_COMOUSAR as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CPP_COMOUSAR',json VARCHAR2(2500) PATH '$.upr1_oi_cpp_comousar')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2 as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2',json VARCHAR2(2500) PATH '$.upr1_oi_crbdad5arbi_promodegrau_init2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2 as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2',json VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recbonusmax_init2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2 as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2',json VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recbonusmindegrau2_init2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2 as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2',json VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recebonusmindegrau3_init2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2 as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2',json VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recebebonusmindegrau2e3_init2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2 as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2',json VARCHAR2(2500) PATH '$.upr1_oi_crbdad5d_recebebonusmax3_init2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CINFPROMO_MENSAGEMINICIAL = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CINFPROMO_MENSAGEMINICIAL as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CINFPROMO_MENSAGEMINICIAL',json VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_mensageminicial')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CINFPROMO_REGTORPEDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CINFPROMO_REGTORPEDO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CINFPROMO_REGTORPEDO',json VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_regtorpedo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CINFPROMO_REGLIGACAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CINFPROMO_REGLIGACAO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CINFPROMO_REGLIGACAO',json VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_regligacao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CINFPROMO_COMOUSAR = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CINFPROMO_COMOUSAR as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CINFPROMO_COMOUSAR',json VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_comousar')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CINFPROMO_VALIDADEPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CINFPROMO_VALIDADEPROMO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CINFPROMO_VALIDADEPROMO',json VARCHAR2(2500) PATH '$.upr1_oi_cinfpromo_validadepromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CCPOP_PROMOOICARTAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CCPOP_PROMOOICARTAO as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CCPOP_PROMOOICARTAO',json VARCHAR2(2500) PATH '$.upr1_oi_ccpop_promooicartao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CINFP_REGDADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CINFP_REGDADOS as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CINFP_REGDADOS',json VARCHAR2(2500) PATH '$.upr1_oi_cinfp_regdados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	UPR1_OI_CPP_REGDADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OI_CPP_REGDADOS as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OI_CPP_REGDADOS',json VARCHAR2(2500) PATH '$.upr1_oi_cpp_regdados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	INCENTIVO_OFERTA_PRE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO_OFERTA_PRE as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO_OFERTA_PRE',json VARCHAR2(2500) PATH '$.incentivo_oferta_pre')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	JACLIENTE_SVA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SVA as coluna,jsonEdit,json FROM TB_CARTAOMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SVA',json VARCHAR2(2500) PATH '$.jacliente_sva')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO TB_CARTAOMENU (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	UPR1_OI_CPP_MINICIAL,\n"
            + "	UPR1_OI_CPP_REGTORPEDO,\n"
            + "	UPR1_OI_CPP_REGLIGACAO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOMIX,\n"
            + "	UPR1_OI_CPP_COMOUSAR,\n"
            + "	UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2,\n"
            + "	UPR1_OI_CINFPROMO_MENSAGEMINICIAL,\n"
            + "	UPR1_OI_CINFPROMO_REGTORPEDO,\n"
            + "	UPR1_OI_CINFPROMO_REGLIGACAO,\n"
            + "	UPR1_OI_CINFPROMO_COMOUSAR,\n"
            + "	UPR1_OI_CINFPROMO_VALIDADEPROMO,\n"
            + "	UPR1_OI_CCPOP_PROMOOICARTAO,\n"
            + "	UPR1_OI_CINFP_REGDADOS,\n"
            + "	UPR1_OI_CPP_REGDADOS,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	JACLIENTE_SVA,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	UPR1_OI_CPP_MINICIAL,\n"
            + "	UPR1_OI_CPP_REGTORPEDO,\n"
            + "	UPR1_OI_CPP_REGLIGACAO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOMIX,\n"
            + "	UPR1_OI_CPP_COMOUSAR,\n"
            + "	UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2,\n"
            + "	UPR1_OI_CINFPROMO_MENSAGEMINICIAL,\n"
            + "	UPR1_OI_CINFPROMO_REGTORPEDO,\n"
            + "	UPR1_OI_CINFPROMO_REGLIGACAO,\n"
            + "	UPR1_OI_CINFPROMO_COMOUSAR,\n"
            + "	UPR1_OI_CINFPROMO_VALIDADEPROMO,\n"
            + "	UPR1_OI_CCPOP_PROMOOICARTAO,\n"
            + "	UPR1_OI_CINFP_REGDADOS,\n"
            + "	UPR1_OI_CPP_REGDADOS,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	JACLIENTE_SVA,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM TB_CARTAOMENU WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO TB_CARTAOMENU (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	UPR1_OI_CPP_MINICIAL,\n"
            + "	UPR1_OI_CPP_REGTORPEDO,\n"
            + "	UPR1_OI_CPP_REGLIGACAO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOMIX,\n"
            + "	UPR1_OI_CPP_COMOUSAR,\n"
            + "	UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2,\n"
            + "	UPR1_OI_CINFPROMO_MENSAGEMINICIAL,\n"
            + "	UPR1_OI_CINFPROMO_REGTORPEDO,\n"
            + "	UPR1_OI_CINFPROMO_REGLIGACAO,\n"
            + "	UPR1_OI_CINFPROMO_COMOUSAR,\n"
            + "	UPR1_OI_CINFPROMO_VALIDADEPROMO,\n"
            + "	UPR1_OI_CCPOP_PROMOOICARTAO,\n"
            + "	UPR1_OI_CINFP_REGDADOS,\n"
            + "	UPR1_OI_CPP_REGDADOS,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	JACLIENTE_SVA,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	UPR1_OI_CPP_MINICIAL,\n"
            + "	UPR1_OI_CPP_REGTORPEDO,\n"
            + "	UPR1_OI_CPP_REGLIGACAO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO,\n"
            + "	UPR1_OI_CPPCONT_REGLIGACAOMIX,\n"
            + "	UPR1_OI_CPP_COMOUSAR,\n"
            + "	UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2,\n"
            + "	UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2,\n"
            + "	UPR1_OI_CINFPROMO_MENSAGEMINICIAL,\n"
            + "	UPR1_OI_CINFPROMO_REGTORPEDO,\n"
            + "	UPR1_OI_CINFPROMO_REGLIGACAO,\n"
            + "	UPR1_OI_CINFPROMO_COMOUSAR,\n"
            + "	UPR1_OI_CINFPROMO_VALIDADEPROMO,\n"
            + "	UPR1_OI_CCPOP_PROMOOICARTAO,\n"
            + "	UPR1_OI_CINFP_REGDADOS,\n"
            + "	UPR1_OI_CPP_REGDADOS,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	JACLIENTE_SVA,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM TB_CARTAOMENU WHERE ID IN (?))";

    public static final String APROVAR
            = "t1.TB_ID_BENEFICIO = t2.TB_ID_BENEFICIO,\n"
            + "t1.TB_ID_PROGRAMA = t2.TB_ID_PROGRAMA,\n"
            + "t1.TB_DDD = t2.TB_DDD,\n"
            + "t1.TB_REGIAO = t2.TB_REGIAO,\n"
            + "t1.UPR1_OI_CPP_MINICIAL = t2.UPR1_OI_CPP_MINICIAL,\n"
            + "t1.UPR1_OI_CPP_REGTORPEDO = t2.UPR1_OI_CPP_REGTORPEDO,\n"
            + "t1.UPR1_OI_CPP_REGLIGACAO = t2.UPR1_OI_CPP_REGLIGACAO,\n"
            + "t1.UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL = t2.UPR1_OI_CPPCONT_REGLIGACAOOIMOVEL,\n"
            + "t1.UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO = t2.UPR1_OI_CPPCONT_REGLIGACAOOIMOVELFIXO,\n"
            + "t1.UPR1_OI_CPPCONT_REGLIGACAOMIX = t2.UPR1_OI_CPPCONT_REGLIGACAOMIX,\n"
            + "t1.UPR1_OI_CPP_COMOUSAR = t2.UPR1_OI_CPP_COMOUSAR,\n"
            + "t1.UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2 = t2.UPR1_OI_CRBDAD5ARBI_PROMODEGRAU_INIT2,\n"
            + "t1.UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2 = t2.UPR1_OI_CRBDAD5D_RECBONUSMAX_INIT2,\n"
            + "t1.UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2 = t2.UPR1_OI_CRBDAD5D_RECBONUSMINDEGRAU2_INIT2,\n"
            + "t1.UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2 = t2.UPR1_OI_CRBDAD5D_RECEBONUSMINDEGRAU3_INIT2,\n"
            + "t1.UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2 = t2.UPR1_OI_CRBDAD5D_RECEBEBONUSMINDEGRAU2E3_INIT2,\n"
            + "t1.UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2 = t2.UPR1_OI_CRBDAD5D_RECEBEBONUSMAX3_INIT2,\n"
            + "t1.UPR1_OI_CINFPROMO_MENSAGEMINICIAL = t2.UPR1_OI_CINFPROMO_MENSAGEMINICIAL,\n"
            + "t1.UPR1_OI_CINFPROMO_REGTORPEDO = t2.UPR1_OI_CINFPROMO_REGTORPEDO,\n"
            + "t1.UPR1_OI_CINFPROMO_REGLIGACAO = t2.UPR1_OI_CINFPROMO_REGLIGACAO,\n"
            + "t1.UPR1_OI_CINFPROMO_COMOUSAR = t2.UPR1_OI_CINFPROMO_COMOUSAR,\n"
            + "t1.UPR1_OI_CINFPROMO_VALIDADEPROMO = t2.UPR1_OI_CINFPROMO_VALIDADEPROMO,\n"
            + "t1.UPR1_OI_CCPOP_PROMOOICARTAO = t2.UPR1_OI_CCPOP_PROMOOICARTAO,\n"
            + "t1.UPR1_OI_CINFP_REGDADOS = t2.UPR1_OI_CINFP_REGDADOS,\n"
            + "t1.UPR1_OI_CPP_REGDADOS = t2.UPR1_OI_CPP_REGDADOS,\n"
            + "t1.INCENTIVO_OFERTA_PRE = t2.INCENTIVO_OFERTA_PRE,\n"
            + "t1.JACLIENTE_SVA = t2.JACLIENTE_SVA,\n"
            + "t1.HISTORY = t2.HISTORY";

}
