/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author Jpereirc
 */
public class TabelaOiCMenu {

    public static final String SELECT
            = "SELECT JSON_QUERY(\n"
            + " concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(\n"
            + " concat(concat('{\"tb_id_beneficio\":\"',TB_ID_BENEFICIO),'\",'),\n"
            + " concat(concat('\"tb_id_programa\":\"',TB_ID_PROGRAMA),'\",')),\n"
            + " concat(concat('\"tb_ddd\":\"',TB_DDD),'\",')),\n"
            + " concat(concat('\"tb_regiao\":\"',TB_REGIAO),'\",')),\n"
            + " concat(concat('\"upr1_oicpp_mensageminicial\":\"',UPR1_OICPP_MENSAGEMINICIAL),'\",')),\n"
            + " concat(concat('\"upr1_oicpp_regtorpedo\":\"',UPR1_OICPP_REGTORPEDO),'\",')),\n"
            + " concat(concat('\"upr1_oicpp_regligacao\":\"',UPR1_OICPP_REGLIGACAO),'\",')),\n"
            + " concat(concat('\"upr1_oicpp_comousar\":\"',UPR1_OICPP_COMOUSAR),'\",')),\n"
            + " concat(concat('\"upr1_oicinfp_mensageminicial\":\"',UPR1_OICINFP_MENSAGEMINICIAL),'\",')),\n"
            + " concat(concat('\"upr1_oicinfp_regtorpedo\":\"',UPR1_OICINFP_REGTORPEDO),'\",')),\n"
            + " concat(concat('\"upr1_oicinfop_regligacao\":\"',UPR1_OICINFOP_REGLIGACAO),'\",')),\n"
            + " concat(concat('\"upr1_oicinfp_comousar\":\"',UPR1_OICINFP_COMOUSAR),'\",')),\n"
            + " concat(concat('\"upr1_oicinfp_validadepromo\":\"',UPR1_OICINFP_VALIDADEPROMO),'\",')),\n"
            + " concat(concat('\"upr1_oiccpoplanos_promooicontrole\":\"',UPR1_OICCPOPLANOS_PROMOOICONTROLE),'\",')),\n"
            + " concat(concat('\"upr1_oicinfp_regdados\":\"',UPR1_OICINFP_REGDADOS),'\",')),\n"
            + " concat(concat('\"upr1_oicpp_regdados\":\"',UPR1_OICPP_REGDADOS),'\",')),\n"
            + " concat(concat('\"jacliente_sva\":\"',JACLIENTE_SVA),'\"}'))\n"
            + ",'$') as json,ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM TB_OICMENU t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO TB_OICMENU (\n"
            + " TB_ID_BENEFICIO,\n"
            + " TB_ID_PROGRAMA,\n"
            + " TB_DDD,\n"
            + " TB_REGIAO,\n"
            + " UPR1_OICPP_MENSAGEMINICIAL,\n"
            + " UPR1_OICPP_REGTORPEDO,\n"
            + " UPR1_OICPP_REGLIGACAO,\n"
            + " UPR1_OICPP_COMOUSAR,\n"
            + " UPR1_OICINFP_MENSAGEMINICIAL,\n"
            + " UPR1_OICINFP_REGTORPEDO,\n"
            + " UPR1_OICINFOP_REGLIGACAO,\n"
            + " UPR1_OICINFP_COMOUSAR,\n"
            + " UPR1_OICINFP_VALIDADEPROMO,\n"
            + " UPR1_OICCPOPLANOS_PROMOOICONTROLE,\n"
            + " UPR1_OICINFP_REGDADOS,\n"
            + " UPR1_OICPP_REGDADOS,\n"
            + " JACLIENTE_SVA,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + " TB_ID_BENEFICIO,\n"
            + " TB_ID_PROGRAMA,\n"
            + " TB_DDD,\n"
            + " TB_REGIAO,\n"
            + " UPR1_OICPP_MENSAGEMINICIAL,\n"
            + " UPR1_OICPP_REGTORPEDO,\n"
            + " UPR1_OICPP_REGLIGACAO,\n"
            + " UPR1_OICPP_COMOUSAR,\n"
            + " UPR1_OICINFP_MENSAGEMINICIAL,\n"
            + " UPR1_OICINFP_REGTORPEDO,\n"
            + " UPR1_OICINFOP_REGLIGACAO,\n"
            + " UPR1_OICINFP_COMOUSAR,\n"
            + " UPR1_OICINFP_VALIDADEPROMO,\n"
            + " UPR1_OICCPOPLANOS_PROMOOICONTROLE,\n"
            + " UPR1_OICINFP_REGDADOS,\n"
            + " UPR1_OICPP_REGDADOS,\n"
            + " JACLIENTE_SVA,\n"
            + "	?,\n"
            + "   DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + " TB_ID_BENEFICIO VARCHAR2(2500) PATH '$.tb_id_beneficio',\n"
            + " TB_ID_PROGRAMA VARCHAR2(2500) PATH '$.tb_id_programa',\n"
            + " TB_DDD VARCHAR2(2500) PATH '$.tb_ddd',\n"
            + " TB_REGIAO VARCHAR2(2500) PATH '$.tb_regiao',\n"
            + " UPR1_OICPP_MENSAGEMINICIAL VARCHAR2(2500) PATH '$.upr1_oicpp_mensageminicial',\n"
            + " UPR1_OICPP_REGTORPEDO VARCHAR2(2500) PATH '$.upr1_oicpp_regtorpedo',\n"
            + " UPR1_OICPP_REGLIGACAO VARCHAR2(2500) PATH '$.upr1_oicpp_regligacao',\n"
            + " UPR1_OICPP_COMOUSAR VARCHAR2(2500) PATH '$.upr1_oicpp_comousar',\n"
            + " UPR1_OICINFP_MENSAGEMINICIAL VARCHAR2(2500) PATH '$.upr1_oicinfp_mensageminicial',\n"
            + " UPR1_OICINFP_REGTORPEDO VARCHAR2(2500) PATH '$.upr1_oicinfp_regtorpedo',\n"
            + " UPR1_OICINFOP_REGLIGACAO VARCHAR2(2500) PATH '$.upr1_oicinfop_regligacao',\n"
            + " UPR1_OICINFP_COMOUSAR VARCHAR2(2500) PATH '$.upr1_oicinfp_comousar',\n"
            + " UPR1_OICINFP_VALIDADEPROMO VARCHAR2(2500) PATH '$.upr1_oicinfp_validadepromo',\n"
            + " UPR1_OICCPOPLANOS_PROMOOICONTROLE VARCHAR2(2500) PATH '$.upr1_oiccpoplanos_promooicontrole',\n"
            + " UPR1_OICINFP_REGDADOS VARCHAR2(2500) PATH '$.upr1_oicinfp_regdados',\n"
            + " UPR1_OICPP_REGDADOS VARCHAR2(2500) PATH '$.upr1_oicpp_regdados',\n"
            + " JACLIENTE_SVA VARCHAR2(2500) PATH '$.jacliente_sva',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE TB_OICMENU SET \n"
            + " TB_ID_BENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_BENEFICIO as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_BENEFICIO',json NUMBER(38,0) PATH '$.tb_id_beneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TB_ID_PROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_PROGRAMA as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_PROGRAMA',json NUMBER(38,0) PATH '$.tb_id_programa')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TB_DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_DDD as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_DDD',json VARCHAR2(2500) PATH '$.tb_ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TB_REGIAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_REGIAO as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_REGIAO',json VARCHAR2(2500) PATH '$.tb_regiao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICPP_MENSAGEMINICIAL = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICPP_MENSAGEMINICIAL as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICPP_MENSAGEMINICIAL',json VARCHAR2(2500) PATH '$.upr1_oicpp_mensageminicial')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICPP_REGTORPEDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICPP_REGTORPEDO as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICPP_REGTORPEDO',json VARCHAR2(2500) PATH '$.upr1_oicpp_regtorpedo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICPP_REGLIGACAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICPP_REGLIGACAO as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICPP_REGLIGACAO',json VARCHAR2(2500) PATH '$.upr1_oicpp_regligacao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICPP_COMOUSAR = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICPP_COMOUSAR as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICPP_COMOUSAR',json VARCHAR2(2500) PATH '$.upr1_oicpp_comousar')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICINFP_MENSAGEMINICIAL = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICINFP_MENSAGEMINICIAL as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICINFP_MENSAGEMINICIAL',json VARCHAR2(2500) PATH '$.upr1_oicinfp_mensageminicial')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICINFP_REGTORPEDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICINFP_REGTORPEDO as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICINFP_REGTORPEDO',json VARCHAR2(2500) PATH '$.upr1_oicinfp_regtorpedo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICINFOP_REGLIGACAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICINFOP_REGLIGACAO as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICINFOP_REGLIGACAO',json VARCHAR2(2500) PATH '$.upr1_oicinfop_regligacao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICINFP_COMOUSAR = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICINFP_COMOUSAR as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICINFP_COMOUSAR',json VARCHAR2(2500) PATH '$.upr1_oicinfp_comousar')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICINFP_VALIDADEPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICINFP_VALIDADEPROMO as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICINFP_VALIDADEPROMO',json VARCHAR2(2500) PATH '$.upr1_oicinfp_validadepromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICCPOPLANOS_PROMOOICONTROLE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICCPOPLANOS_PROMOOICONTROLE as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICCPOPLANOS_PROMOOICONTROLE',json VARCHAR2(2500) PATH '$.upr1_oiccpoplanos_promooicontrole')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICINFP_REGDADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICINFP_REGDADOS as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICINFP_REGDADOS',json VARCHAR2(2500) PATH '$.upr1_oicinfp_regdados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " UPR1_OICPP_REGDADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT UPR1_OICPP_REGDADOS as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.UPR1_OICPP_REGDADOS',json VARCHAR2(2500) PATH '$.upr1_oicpp_regdados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_SVA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SVA as coluna,jsonEdit,json FROM TB_OICMENU,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SVA',json VARCHAR2(2500) PATH '$.jacliente_sva')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO TB_OICMENU (\n"
            + " TB_ID_BENEFICIO,\n"
            + " TB_ID_PROGRAMA,\n"
            + " TB_DDD,\n"
            + " TB_REGIAO,\n"
            + " UPR1_OICPP_MENSAGEMINICIAL,\n"
            + " UPR1_OICPP_REGTORPEDO,\n"
            + " UPR1_OICPP_REGLIGACAO,\n"
            + " UPR1_OICPP_COMOUSAR,\n"
            + " UPR1_OICINFP_MENSAGEMINICIAL,\n"
            + " UPR1_OICINFP_REGTORPEDO,\n"
            + " UPR1_OICINFOP_REGLIGACAO,\n"
            + " UPR1_OICINFP_COMOUSAR,\n"
            + " UPR1_OICINFP_VALIDADEPROMO,\n"
            + " UPR1_OICCPOPLANOS_PROMOOICONTROLE,\n"
            + " UPR1_OICINFP_REGDADOS,\n"
            + " UPR1_OICPP_REGDADOS,\n"
            + " JACLIENTE_SVA,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + " TB_ID_BENEFICIO,\n"
            + " TB_ID_PROGRAMA,\n"
            + " TB_DDD,\n"
            + " TB_REGIAO,\n"
            + " UPR1_OICPP_MENSAGEMINICIAL,\n"
            + " UPR1_OICPP_REGTORPEDO,\n"
            + " UPR1_OICPP_REGLIGACAO,\n"
            + " UPR1_OICPP_COMOUSAR,\n"
            + " UPR1_OICINFP_MENSAGEMINICIAL,\n"
            + " UPR1_OICINFP_REGTORPEDO,\n"
            + " UPR1_OICINFOP_REGLIGACAO,\n"
            + " UPR1_OICINFP_COMOUSAR,\n"
            + " UPR1_OICINFP_VALIDADEPROMO,\n"
            + " UPR1_OICCPOPLANOS_PROMOOICONTROLE,\n"
            + " UPR1_OICINFP_REGDADOS,\n"
            + " UPR1_OICPP_REGDADOS,\n"
            + " JACLIENTE_SVA,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM TB_OICMENU WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO TB_OICMENU (\n"
            + " TB_ID_BENEFICIO,\n"
            + " TB_ID_PROGRAMA,\n"
            + " TB_DDD,\n"
            + " TB_REGIAO,\n"
            + " UPR1_OICPP_MENSAGEMINICIAL,\n"
            + " UPR1_OICPP_REGTORPEDO,\n"
            + " UPR1_OICPP_REGLIGACAO,\n"
            + " UPR1_OICPP_COMOUSAR,\n"
            + " UPR1_OICINFP_MENSAGEMINICIAL,\n"
            + " UPR1_OICINFP_REGTORPEDO,\n"
            + " UPR1_OICINFOP_REGLIGACAO,\n"
            + " UPR1_OICINFP_COMOUSAR,\n"
            + " UPR1_OICINFP_VALIDADEPROMO,\n"
            + " UPR1_OICCPOPLANOS_PROMOOICONTROLE,\n"
            + " UPR1_OICINFP_REGDADOS,\n"
            + " UPR1_OICPP_REGDADOS,\n"
            + " JACLIENTE_SVA,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + " TB_ID_BENEFICIO,\n"
            + " TB_ID_PROGRAMA,\n"
            + " TB_DDD,\n"
            + " TB_REGIAO,\n"
            + " UPR1_OICPP_MENSAGEMINICIAL,\n"
            + " UPR1_OICPP_REGTORPEDO,\n"
            + " UPR1_OICPP_REGLIGACAO,\n"
            + " UPR1_OICPP_COMOUSAR,\n"
            + " UPR1_OICINFP_MENSAGEMINICIAL,\n"
            + " UPR1_OICINFP_REGTORPEDO,\n"
            + " UPR1_OICINFOP_REGLIGACAO,\n"
            + " UPR1_OICINFP_COMOUSAR,\n"
            + " UPR1_OICINFP_VALIDADEPROMO,\n"
            + " UPR1_OICCPOPLANOS_PROMOOICONTROLE,\n"
            + " UPR1_OICINFP_REGDADOS,\n"
            + " UPR1_OICPP_REGDADOS,\n"
            + " JACLIENTE_SVA,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM TB_OICMENU WHERE ID IN (?))";

    public static final String APROVAR
            = "t1.TB_ID_BENEFICIO = t2.TB_ID_BENEFICIO,\n"
            + "t1.TB_ID_PROGRAMA = t2.TB_ID_PROGRAMA,\n"
            + "t1.TB_DDD = t2.TB_DDD,\n"
            + "t1.TB_REGIAO = t2.TB_REGIAO,\n"
            + "t1.UPR1_OICPP_MENSAGEMINICIAL = t2.UPR1_OICPP_MENSAGEMINICIAL,\n"
            + "t1.UPR1_OICPP_REGTORPEDO = t2.UPR1_OICPP_REGTORPEDO,\n"
            + "t1.UPR1_OICPP_REGLIGACAO = t2.UPR1_OICPP_REGLIGACAO,\n"
            + "t1.UPR1_OICPP_COMOUSAR = t2.UPR1_OICPP_COMOUSAR,\n"
            + "t1.UPR1_OICINFP_MENSAGEMINICIAL = t2.UPR1_OICINFP_MENSAGEMINICIAL,\n"
            + "t1.UPR1_OICINFP_REGTORPEDO = t2.UPR1_OICINFP_REGTORPEDO,\n"
            + "t1.UPR1_OICINFOP_REGLIGACAO = t2.UPR1_OICINFOP_REGLIGACAO,\n"
            + "t1.UPR1_OICINFP_COMOUSAR = t2.UPR1_OICINFP_COMOUSAR,\n"
            + "t1.UPR1_OICINFP_VALIDADEPROMO = t2.UPR1_OICINFP_VALIDADEPROMO\n"
            + "t1.UPR1_OICCPOPLANOS_PROMOOICONTROLE = t2.UPR1_OICCPOPLANOS_PROMOOICONTROLE,\n"
            + "t1.UPR1_OICINFP_REGDADOS = t2.UPR1_OICINFP_REGDADOS,\n"
            + "t1.UPR1_OICPP_REGDADOS = t2.UPR1_OICPP_REGDADOS,\n"
            + "t1.JACLIENTE_SVA = t2.JACLIENTE_SVA,\n"
            + "t1.HISTORY = t2.HISTORY";

}
