/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author jpereirc
 */
public class TabelaVoControle {

    public static final String SELECT
            = "SELECT JSON_QUERY(\n"
            + " concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(\n"
            + " concat(concat('{\"idbeneficio\":\"',IDBENEFICIO),'\",'),\n"
            + " concat(concat('\"idprograma\":\"',IDPROGRAMA),'\",')),\n"
            + " concat(concat('\"ddd\":\"',DDD),'\",')),\n"
            + " concat(concat('\"tb_tipobonus\":\"',TB_TIPOBONUS),'\",')),\n"
            + " concat(concat('\"tb_tipoplano\":\"',TB_TIPOPLANO),'\",')),\n"
            + " concat(concat('\"incentivo1\":\"',INCENTIVO1),'\",')),\n"
            + " concat(concat('\"incentivo2\":\"',INCENTIVO2),'\",')),\n"
            + " concat(concat('\"outrosplanos\":\"',OUTROSPLANOS),'\",')),\n"
            + " concat(concat('\"offercode\":\"',OFFERCODE),'\",')),\n"
            + " concat(concat('\"data_inic\":\"',DATA_INIC),'\",')),\n"
            + " concat(concat('\"data_fim\":\"',DATA_FIM),'\",')),\n"
            + " concat(concat('\"taxaadesao\":\"',TAXAADESAO),'\",')),\n"
            + " concat(concat('\"tarifasmsdadoswifi\":\"',TARIFASMSDADOSWIFI),'\",')),\n"
            + " concat(concat('\"tarifasms\":\"',TARIFASMS),'\",')),\n"
            + " concat(concat('\"tarifadados\":\"',TARIFADADOS),'\",')),\n"
            + " concat(concat('\"tarifavoz\":\"',TARIFAVOZ),'\",')),\n"
            + " concat(concat('\"franquia\":\"',FRANQUIA),'\",')),\n"
            + " concat(concat('\"creditos\":\"',CREDITOS),'\",')),\n"
            + " concat(concat('\"elegivel_nova_promo\":\"',ELEGIVEL_NOVA_PROMO),'\",')),\n"
            + " concat(concat('\"tb_taxa_adesaoboleto\":\"',TB_TAXA_ADESAOBOLETO),'\",')),\n"
            + " concat(concat('\"bolso_ilimitado\":\"',BOLSO_ILIMITADO),'\",')),\n"
            + " concat(concat('\"bolso_allnet\":\"',BOLSO_ALLNET),'\",')),\n"
            + " concat(concat('\"franquia_boleto\":\"',FRANQUIA_BOLETO),'\",')),\n"
            + " concat(concat('\"tipo_pagamento\":\"',TIPO_PAGAMENTO),'\",')),\n"
            + " concat(concat('\"tb_ussd_convertido\":\"',TB_USSD_CONVERTIDO),'\"}'))\n"
            + ",'$') as json,ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM VO_CONTROLE t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO VO_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " TB_TIPOBONUS,\n"
            + " TB_TIPOPLANO,\n"
            + " INCENTIVO1,\n"
            + " INCENTIVO2,\n"
            + " OUTROSPLANOS,\n"
            + " OFFERCODE,\n"
            + " DATA_INIC,\n"
            + " DATA_FIM,\n"
            + " TAXAADESAO,\n"
            + " TARIFASMSDADOSWIFI,\n"
            + " TARIFASMS,\n"
            + " TARIFADADOS,\n"
            + " TARIFAVOZ,\n"
            + " FRANQUIA,\n"
            + " CREDITOS,\n"
            + " ELEGIVEL_NOVA_PROMO,\n"
            + " TB_TAXA_ADESAOBOLETO,\n"
            + " BOLSO_ILIMITADO,\n"
            + " BOLSO_ALLNET,\n"
            + " FRANQUIA_BOLETO,\n"
            + " TIPO_PAGAMENTO,\n"
            + " TB_USSD_CONVERTIDO,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " TB_TIPOBONUS,\n"
            + " TB_TIPOPLANO,\n"
            + " INCENTIVO1,\n"
            + " INCENTIVO2,\n"
            + " OUTROSPLANOS,\n"
            + " OFFERCODE,\n"
            + " DATA_INIC,\n"
            + " DATA_FIM,\n"
            + " TAXAADESAO,\n"
            + " TARIFASMSDADOSWIFI,\n"
            + " TARIFASMS,\n"
            + " TARIFADADOS,\n"
            + " TARIFAVOZ,\n"
            + " FRANQUIA,\n"
            + " CREDITOS,\n"
            + " ELEGIVEL_NOVA_PROMO,\n"
            + " TB_TAXA_ADESAOBOLETO,\n"
            + " BOLSO_ILIMITADO,\n"
            + " BOLSO_ALLNET,\n"
            + " FRANQUIA_BOLETO,\n"
            + " TIPO_PAGAMENTO,\n"
            + " TB_USSD_CONVERTIDO,\n"
            + "	?,\n"
            + "   DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + " IDBENEFICIO VARCHAR2(2500) PATH '$.idbeneficio',\n"
            + " IDPROGRAMA VARCHAR2(2500) PATH '$.idprograma',\n"
            + " DDD VARCHAR2(2500) PATH '$.ddd',\n"
            + " TB_TIPOBONUS VARCHAR2(2500) PATH '$.tb_tipobonus',\n"
            + " TB_TIPOPLANO VARCHAR2(2500) PATH '$.tb_tipoplano',\n"
            + " INCENTIVO1 VARCHAR2(2500) PATH '$.incentivo1',\n"
            + " INCENTIVO2 VARCHAR2(2500) PATH '$.incentivo2',\n"
            + " OUTROSPLANOS VARCHAR2(2500) PATH '$.outrosplanos',\n"
            + " OFFERCODE VARCHAR2(2500) PATH '$.offercode',\n"
            + " DATA_INIC VARCHAR2(2500) PATH '$.data_inic',\n"
            + " DATA_FIM VARCHAR2(2500) PATH '$.data_fim',\n"
            + " TAXAADESAO VARCHAR2(2500) PATH '$.taxaadesao',\n"
            + " TARIFASMSDADOSWIFI VARCHAR2(2500) PATH '$.tarifasmsdadoswifi',\n"
            + " TARIFASMS VARCHAR2(2500) PATH '$.tarifasms',\n"
            + " TARIFADADOS VARCHAR2(2500) PATH '$.tarifadados',\n"
            + " TARIFAVOZ VARCHAR2(2500) PATH '$.tarifavoz',\n"
            + " FRANQUIA VARCHAR2(2500) PATH '$.franquia',\n"
            + " CREDITOS VARCHAR2(2500) PATH '$.creditos',\n"
            + " ELEGIVEL_NOVA_PROMO VARCHAR2(2500) PATH '$.elegivel_nova_promo',\n"
            + " TB_TAXA_ADESAOBOLETO VARCHAR2(2500) PATH '$.tb_taxa_adesaoboleto',\n"
            + " BOLSO_ILIMITADO VARCHAR2(2500) PATH '$.bolso_ilimitado',\n"
            + " BOLSO_ALLNET VARCHAR2(2500) PATH '$.bolso_allnet',\n"
            + " FRANQUIA_BOLETO VARCHAR2(2500) PATH '$.franquia_boleto',\n"
            + " TIPO_PAGAMENTO VARCHAR2(2500) PATH '$.tipo_pagamento',\n"
            + " TB_USSD_CONVERTIDO VARCHAR2(2500) PATH '$.tb_ussd_convertido',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE VO_CONTROLE SET \n"
            + " IDBENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDBENEFICIO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDBENEFICIO',json NUMBER(38,0) PATH '$.idbeneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " IDPROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDPROGRAMA as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDPROGRAMA',json NUMBER(38,0) PATH '$.idprograma')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DDD as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DDD',json VARCHAR2(2500) PATH '$.ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TB_TIPOBONUS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_TIPOBONUS as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_TIPOBONUS',json VARCHAR2(2500) PATH '$.tb_tipobonus')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TB_TIPOPLANO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_TIPOPLANO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_TIPOPLANO',json VARCHAR2(2500) PATH '$.tb_tipoplano')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " INCENTIVO1 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO1 as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO1',json VARCHAR2(2500) PATH '$.incentivo1')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " INCENTIVO2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO2 as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO2',json VARCHAR2(2500) PATH '$.incentivo2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " OUTROSPLANOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OUTROSPLANOS as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OUTROSPLANOS',json VARCHAR2(2500) PATH '$.outrosplanos')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " OFFERCODE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFFERCODE as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFFERCODE',json VARCHAR2(2500) PATH '$.offercode')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " DATA_INIC = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DATA_INIC as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DATA_INIC',json DATE PATH '$.data_inic')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " DATA_FIM = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DATA_FIM as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DATA_FIM',json DATE PATH '$.data_fim')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TAXAADESAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TAXAADESAO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TAXAADESAO',json VARCHAR2(2500) PATH '$.taxaadesao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TARIFASMSDADOSWIFI = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFASMSDADOSWIFI as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFASMSDADOSWIFI',json VARCHAR2(2500) PATH '$.tarifasmsdadoswifi')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TARIFASMS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFASMS as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFASMS',json VARCHAR2(2500) PATH '$.tarifasms')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TARIFADADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFADADOS as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFADADOS',json VARCHAR2(2500) PATH '$.tarifadados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TARIFAVOZ = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFAVOZ as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFAVOZ',json VARCHAR2(2500) PATH '$.tarifavoz')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " FRANQUIA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT FRANQUIA as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.FRANQUIA',json VARCHAR2(2500) PATH '$.franquia')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " CREDITOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CREDITOS as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CREDITOS',json VARCHAR2(2500) PATH '$.creditos')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " ELEGIVEL_NOVA_PROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT ELEGIVEL_NOVA_PROMO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.ELEGIVEL_NOVA_PROMO',json VARCHAR2(2500) PATH '$.elegivel_nova_promo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TB_TAXA_ADESAOBOLETO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_TAXA_ADESAOBOLETO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_TAXA_ADESAOBOLETO',json VARCHAR2(2500) PATH '$.tb_taxa_adesaoboleto')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " BOLSO_ILIMITADO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT BOLSO_ILIMITADO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.BOLSO_ILIMITADO',json NUMBER(38,0) PATH '$.bolso_ilimitado')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " BOLSO_ALLNET = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT BOLSO_ALLNET as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.BOLSO_ALLNET',json NUMBER(38,0) PATH '$.bolso_allnet')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " FRANQUIA_BOLETO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT FRANQUIA_BOLETO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.FRANQUIA_BOLETO',json VARCHAR2(2500) PATH '$.franquia_boleto')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TIPO_PAGAMENTO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TIPO_PAGAMENTO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TIPO_PAGAMENTO',json VARCHAR2(2500) PATH '$.tipo_pagamento')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " TB_USSD_CONVERTIDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_USSD_CONVERTIDO as coluna,jsonEdit,json FROM VO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_USSD_CONVERTIDO',json VARCHAR2(2500) PATH '$.tb_ussd_convertido')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO VO_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " TB_TIPOBONUS,\n"
            + " TB_TIPOPLANO,\n"
            + " INCENTIVO1,\n"
            + " INCENTIVO2,\n"
            + " OUTROSPLANOS,\n"
            + " OFFERCODE,\n"
            + " DATA_INIC,\n"
            + " DATA_FIM,\n"
            + " TAXAADESAO,\n"
            + " TARIFASMSDADOSWIFI,\n"
            + " TARIFASMS,\n"
            + " TARIFADADOS,\n"
            + " TARIFAVOZ,\n"
            + " FRANQUIA,\n"
            + " CREDITOS,\n"
            + " ELEGIVEL_NOVA_PROMO,\n"
            + " TB_TAXA_ADESAOBOLETO,\n"
            + " BOLSO_ILIMITADO,\n"
            + " BOLSO_ALLNET,\n"
            + " FRANQUIA_BOLETO,\n"
            + " TIPO_PAGAMENTO,\n"
            + " TB_USSD_CONVERTIDO,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " TB_TIPOBONUS,\n"
            + " TB_TIPOPLANO,\n"
            + " INCENTIVO1,\n"
            + " INCENTIVO2,\n"
            + " OUTROSPLANOS,\n"
            + " OFFERCODE,\n"
            + " DATA_INIC,\n"
            + " DATA_FIM,\n"
            + " TAXAADESAO,\n"
            + " TARIFASMSDADOSWIFI,\n"
            + " TARIFASMS,\n"
            + " TARIFADADOS,\n"
            + " TARIFAVOZ,\n"
            + " FRANQUIA,\n"
            + " CREDITOS,\n"
            + " ELEGIVEL_NOVA_PROMO,\n"
            + " TB_TAXA_ADESAOBOLETO,\n"
            + " BOLSO_ILIMITADO,\n"
            + " BOLSO_ALLNET,\n"
            + " FRANQUIA_BOLETO,\n"
            + " TIPO_PAGAMENTO,\n"
            + " TB_USSD_CONVERTIDO,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM VO_CONTROLE WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO VO_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " TB_TIPOBONUS,\n"
            + " TB_TIPOPLANO,\n"
            + " INCENTIVO1,\n"
            + " INCENTIVO2,\n"
            + " OUTROSPLANOS,\n"
            + " OFFERCODE,\n"
            + " DATA_INIC,\n"
            + " DATA_FIM,\n"
            + " TAXAADESAO,\n"
            + " TARIFASMSDADOSWIFI,\n"
            + " TARIFASMS,\n"
            + " TARIFADADOS,\n"
            + " TARIFAVOZ,\n"
            + " FRANQUIA,\n"
            + " CREDITOS,\n"
            + " ELEGIVEL_NOVA_PROMO,\n"
            + " TB_TAXA_ADESAOBOLETO,\n"
            + " BOLSO_ILIMITADO,\n"
            + " BOLSO_ALLNET,\n"
            + " FRANQUIA_BOLETO,\n"
            + " TIPO_PAGAMENTO,\n"
            + " TB_USSD_CONVERTIDO,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " TB_TIPOBONUS,\n"
            + " TB_TIPOPLANO,\n"
            + " INCENTIVO1,\n"
            + " INCENTIVO2,\n"
            + " OUTROSPLANOS,\n"
            + " OFFERCODE,\n"
            + " DATA_INIC,\n"
            + " DATA_FIM,\n"
            + " TAXAADESAO,\n"
            + " TARIFASMSDADOSWIFI,\n"
            + " TARIFASMS,\n"
            + " TARIFADADOS,\n"
            + " TARIFAVOZ,\n"
            + " FRANQUIA,\n"
            + " CREDITOS,\n"
            + " ELEGIVEL_NOVA_PROMO,\n"
            + " TB_TAXA_ADESAOBOLETO,\n"
            + " BOLSO_ILIMITADO,\n"
            + " BOLSO_ALLNET,\n"
            + " FRANQUIA_BOLETO,\n"
            + " TIPO_PAGAMENTO,\n"
            + " TB_USSD_CONVERTIDO,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM VO_CONTROLE WHERE ID IN (?))";

    public static final String APROVAR
            = "t1.IDBENEFICIO = t2.IDBENEFICIO,\n"
            + "t1.IDPROGRAMA = t2.IDPROGRAMA,\n"
            + "t1.DDD = t2.DDD,\n"
            + "t1.TB_TIPOBONUS = t2.TB_TIPOBONUS,\n"
            + "t1.TB_TIPOPLANO = t2.TB_TIPOPLANO,\n"
            + "t1.INCENTIVO1 = t2.INCENTIVO1,\n"
            + "t1.INCENTIVO2 = t2.INCENTIVO2,\n"
            + "t1.OUTROSPLANOS = t2.OUTROSPLANOS,\n"
            + "t1.OFFERCODE = t2.OFFERCODE,\n"
            + "t1.DATA_INIC = t2.DATA_INIC,\n"
            + "t1.DATA_FIM = t2.DATA_FIM,\n"
            + "t1.TAXAADESAO = t2.TAXAADESAO,\n"
            + "t1.TARIFASMSDADOSWIFI = t2.TARIFASMSDADOSWIFI,\n"
            + "t1.TARIFASMS = t2.TARIFASMS,\n"
            + "t1.TARIFADADOS = t2.TARIFADADOS,\n"
            + "t1.TARIFAVOZ = t2.TARIFAVOZ,\n"
            + "t1.FRANQUIA = t2.FRANQUIA,\n"
            + "t1.CREDITOS = t2.CREDITOS,\n"
            + "t1.ELEGIVEL_NOVA_PROMO = t2.ELEGIVEL_NOVA_PROMO,\n"
            + "t1.TB_TAXA_ADESAOBOLETO = t2.TB_TAXA_ADESAOBOLETO,\n"
            + "t1.BOLSO_ILIMITADO = t2.BOLSO_ILIMITADO,\n"
            + "t1.BOLSO_ALLNET = t2.BOLSO_ALLNET,\n"
            + "t1.FRANQUIA_BOLETO = t2.FRANQUIA_BOLETO,\n"
            + "t1.TIPO_PAGAMENTO = t2.TIPO_PAGAMENTO,\n"
            + "t1.TB_USSD_CONVERTIDO = t2.TB_USSD_CONVERTIDO,\n"
            + "t1.HISTORY = t2.HISTORY";

}
