/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author Jpereirc
 */
public class TabelaFrasesControle {

    public static final String SELECT
            = "SELECT '' as json,\n" +
            "IDBENEFICIO,\n" +
            "IDPROGRAMA,\n" +
            "DDD,\n" +
            "JACLIENTE_PROMOPADRAO,\n" +
            "JACLIENTE_REGRAS,\n" +
            "JACLIENTE_VALIDADE,\n" +
            "JACLIENTE_SALDO,\n" +
            "JACLIENTE_CONTING,\n" +
            "NAOCLIENTE_INFORMAPROMO,\n" +
            "NAOCLIENTE_REGRAS,\n" +
            "NAOCLIENTE_VALIDADE,\n" +
            "CONECTADO_INCENTIVO,\n" +
            "CONECTADO_INCENTIVOPROMOCAO,\n" +
            "JACLIENTE_SVA,\n" +
            "INCENTIVO_COMBOLETO,\n" +
            "DETALHES_OFERTARETENCAO,\n" +
            "INTERNETEMDOBRO_JACLIENTE,\n" +
            "INTERNETEMDOBRO_NAOCLIENTE,\n" +
            "BENEFICIOINTERNET_ANTERIORDTVENDAURA,\n" +
            "BENEFICIOINTERNET_APOSDTVENDAURA,\n" +
            "FALLBACK,\n" +
            "JACLIENTE_PROMOPADRAO_144,\n" +
            "JACLIENTE_REGRAS_144,\n" +
            "JACLIENTE_VALIDADE_144,\n" +
            "JACLIENTE_SALDO_144,\n" +
            "JACLIENTE_CONTING_144,\n" +
            "NAOCLIENTE_INFORMAPROMO_144,\n" +
            "NAOCLIENTE_REGRAS_144,\n" +
            "NAOCLIENTE_VALIDADE_144,\n" +
            "CONECTADO_INCENTIVO_144,\n" +
            "CONECTADO_INCENTIVOPROMOCAO_144,\n" +
            "JACLIENTE_SVA_144,\n" +
            "INCENTIVO_COMBOLETO_144,\n" +
            "DETALHES_OFERTARETENCAO_144,\n" +
            "INTERNETEMDOBRO_JACLIENTE_144,\n" +
            "INTERNETEMDOBRO_NAOCLIENTE_144,\n" +
            "BENEFICIOINTERNET_ANTERIORDTVENDAURA_144,\n" +
            "BENEFICIOINTERNET_APOSDTVENDAURA_144,\n" +
            "FALLBACK_144,\n" +
            "ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM FRASES_CONTROLE t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO FRASES_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " JACLIENTE_PROMOPADRAO,\n"
            + " JACLIENTE_REGRAS,\n"
            + " JACLIENTE_VALIDADE,\n"
            + " JACLIENTE_SALDO,\n"
            + " JACLIENTE_CONTING,\n"
            + " NAOCLIENTE_INFORMAPROMO,\n"
            + " NAOCLIENTE_REGRAS,\n"
            + " NAOCLIENTE_VALIDADE,\n"
            + " CONECTADO_INCENTIVO,\n"
            + " CONECTADO_INCENTIVOPROMOCAO,\n"
            + " JACLIENTE_SVA,\n"
            + " INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTERNETEMDOBRO_JACLIENTE,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA,\n"
            + " FALLBACK,\n"
            + " JACLIENTE_PROMOPADRAO_144,\n"
            + " JACLIENTE_REGRAS_144,\n"
            + " JACLIENTE_VALIDADE_144,\n"
            + " JACLIENTE_SALDO_144,\n"
            + " JACLIENTE_CONTING_144,\n"
            + " NAOCLIENTE_INFORMAPROMO_144,\n"
            + " NAOCLIENTE_REGRAS_144,\n"
            + " NAOCLIENTE_VALIDADE_144,\n"
            + " CONECTADO_INCENTIVO_144,\n"
            + " CONECTADO_INCENTIVOPROMOCAO_144,\n"
            + " JACLIENTE_SVA_144,\n"
            + " INCENTIVO_COMBOLETO_144,\n"
            + " DETALHES_OFERTARETENCAO_144,\n"
            + " INTERNETEMDOBRO_JACLIENTE_144,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE_144,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA_144,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA_144,\n"
            + " FALLBACK_144,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " JACLIENTE_PROMOPADRAO,\n"
            + " JACLIENTE_REGRAS,\n"
            + " JACLIENTE_VALIDADE,\n"
            + " JACLIENTE_SALDO,\n"
            + " JACLIENTE_CONTING,\n"
            + " NAOCLIENTE_INFORMAPROMO,\n"
            + " NAOCLIENTE_REGRAS,\n"
            + " NAOCLIENTE_VALIDADE,\n"
            + " CONECTADO_INCENTIVO,\n"
            + " CONECTADO_INCENTIVOPROMOCAO,\n"
            + " JACLIENTE_SVA,\n"
            + " INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTERNETEMDOBRO_JACLIENTE,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA,\n"
            + " FALLBACK,\n"
            + " JACLIENTE_PROMOPADRAO_144,\n"
            + " JACLIENTE_REGRAS_144,\n"
            + " JACLIENTE_VALIDADE_144,\n"
            + " JACLIENTE_SALDO_144,\n"
            + " JACLIENTE_CONTING_144,\n"
            + " NAOCLIENTE_INFORMAPROMO_144,\n"
            + " NAOCLIENTE_REGRAS_144,\n"
            + " NAOCLIENTE_VALIDADE_144,\n"
            + " CONECTADO_INCENTIVO_144,\n"
            + " CONECTADO_INCENTIVOPROMOCAO_144,\n"
            + " JACLIENTE_SVA_144,\n"
            + " INCENTIVO_COMBOLETO_144,\n"
            + " DETALHES_OFERTARETENCAO_144,\n"
            + " INTERNETEMDOBRO_JACLIENTE_144,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE_144,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA_144,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA_144,\n"
            + " FALLBACK_144,\n"
            + "	?,\n"
            + "   DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + " IDBENEFICIO VARCHAR2(2500) PATH '$.idbeneficio',\n"
            + " IDPROGRAMA VARCHAR2(2500) PATH '$.idprograma',\n"
            + " DDD VARCHAR2(2500) PATH '$.ddd',\n"
            + " JACLIENTE_PROMOPADRAO VARCHAR2(2500) PATH '$.jacliente_promopadrao',\n"
            + " JACLIENTE_REGRAS VARCHAR2(2500) PATH '$.jacliente_regras',\n"
            + " JACLIENTE_VALIDADE VARCHAR2(2500) PATH '$.jacliente_validade',\n"
            + " JACLIENTE_SALDO VARCHAR2(2500) PATH '$.jacliente_saldo',\n"
            + " JACLIENTE_CONTING VARCHAR2(2500) PATH '$.jacliente_conting',\n"
            + " NAOCLIENTE_INFORMAPROMO VARCHAR2(2500) PATH '$.naocliente_informapromo',\n"
            + " NAOCLIENTE_REGRAS VARCHAR2(2500) PATH '$.naocliente_regras',\n"
            + " NAOCLIENTE_VALIDADE VARCHAR2(2500) PATH '$.naocliente_validade',\n"
            + " CONECTADO_INCENTIVO VARCHAR2(2500) PATH '$.conectado_incentivo',\n"
            + " CONECTADO_INCENTIVOPROMOCAO VARCHAR2(2500) PATH '$.conectado_incentivopromocao',\n"
            + " JACLIENTE_SVA VARCHAR2(2500) PATH '$.jacliente_sva',\n"
            + " INCENTIVO_COMBOLETO VARCHAR2(2500) PATH '$.incentivo_comboleto',\n"
            + " DETALHES_OFERTARETENCAO VARCHAR2(2500) PATH '$.detalhes_ofertaretencao',\n"
            + " INTERNETEMDOBRO_JACLIENTE VARCHAR2(2500) PATH '$.internetemdobro_jacliente',\n"
            + " INTERNETEMDOBRO_NAOCLIENTE VARCHAR2(2500) PATH '$.internetemdobro_naocliente',\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA VARCHAR2(2500) PATH '$.beneficiointernet_anteriordtvendaura',\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA VARCHAR2(2500) PATH '$.beneficiointernet_aposdtvendaura',\n"
            + " FALLBACK VARCHAR2(2500) PATH '$.fallback',\n"
            + " JACLIENTE_PROMOPADRAO_144 VARCHAR2(2500) PATH '$.jacliente_promopadrao_144',\n"
            + " JACLIENTE_REGRAS_144 VARCHAR2(2500) PATH '$.jacliente_regras_144',\n"
            + " JACLIENTE_VALIDADE_144 VARCHAR2(2500) PATH '$.jacliente_validade_144',\n"
            + " JACLIENTE_SALDO_144 VARCHAR2(2500) PATH '$.jacliente_saldo_144',\n"
            + " JACLIENTE_CONTING_144 VARCHAR2(2500) PATH '$.jacliente_conting_144',\n"
            + " NAOCLIENTE_INFORMAPROMO_144 VARCHAR2(2500) PATH '$.naocliente_informapromo_144',\n"
            + " NAOCLIENTE_REGRAS_144 VARCHAR2(2500) PATH '$.naocliente_regras_144',\n"
            + " NAOCLIENTE_VALIDADE_144 VARCHAR2(2500) PATH '$.naocliente_validade_144',\n"
            + " CONECTADO_INCENTIVO_144 VARCHAR2(2500) PATH '$.conectado_incentivo_144',\n"
            + " CONECTADO_INCENTIVOPROMOCAO_144 VARCHAR2(2500) PATH '$.conectado_incentivopromocao_144',\n"
            + " JACLIENTE_SVA_144 VARCHAR2(2500) PATH '$.jacliente_sva_144',\n"
            + " INCENTIVO_COMBOLETO_144 VARCHAR2(2500) PATH '$.incentivo_comboleto_144',\n"
            + " DETALHES_OFERTARETENCAO_144 VARCHAR2(2500) PATH '$.detalhes_ofertaretencao_144',\n"
            + " INTERNETEMDOBRO_JACLIENTE_144 VARCHAR2(2500) PATH '$.internetemdobro_jacliente_144',\n"
            + " INTERNETEMDOBRO_NAOCLIENTE_144 VARCHAR2(2500) PATH '$.internetemdobro_naocliente_144',\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA_144 VARCHAR2(2500) PATH '$.beneficiointernet_anteriordtvendaura_144',\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA_144 VARCHAR2(2500) PATH '$.beneficiointernet_aposdtvendaura_144',\n"
            + " FALLBACK_144 VARCHAR2(2500) PATH '$.fallback_144',\n"
            + " DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE FRASES_CONTROLE SET \n"
            + " IDBENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDBENEFICIO as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDBENEFICIO',json NUMBER(38,0) PATH '$.idbeneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " IDPROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDPROGRAMA as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDPROGRAMA',json NUMBER(38,0) PATH '$.idprograma')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DDD as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DDD',json VARCHAR2(2500) PATH '$.ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_PROMOPADRAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_PROMOPADRAO as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_PROMOPADRAO',json VARCHAR2(2500) PATH '$.jacliente_promopadrao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_REGRAS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_REGRAS as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_REGRAS',json VARCHAR2(2500) PATH '$.jacliente_regras')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_VALIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_VALIDADE as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_VALIDADE',json VARCHAR2(2500) PATH '$.jacliente_validade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_SALDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SALDO as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SALDO',json VARCHAR2(2500) PATH '$.jacliente_saldo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_CONTING = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_CONTING as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_CONTING',json VARCHAR2(2500) PATH '$.jacliente_conting')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " NAOCLIENTE_INFORMAPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_INFORMAPROMO as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_INFORMAPROMO',json VARCHAR2(2500) PATH '$.naocliente_informapromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " NAOCLIENTE_REGRAS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_REGRAS as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_REGRAS',json VARCHAR2(2500) PATH '$.naocliente_regras')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " NAOCLIENTE_VALIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_VALIDADE as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_VALIDADE',json VARCHAR2(2500) PATH '$.naocliente_validade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " CONECTADO_INCENTIVO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CONECTADO_INCENTIVO as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CONECTADO_INCENTIVO',json VARCHAR2(2500) PATH '$.conectado_incentivo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " CONECTADO_INCENTIVOPROMOCAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CONECTADO_INCENTIVOPROMOCAO as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CONECTADO_INCENTIVOPROMOCAO',json VARCHAR2(2500) PATH '$.conectado_incentivopromocao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_SVA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SVA as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SVA',json VARCHAR2(2500) PATH '$.jacliente_sva')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " INCENTIVO_COMBOLETO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO_COMBOLETO as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO_COMBOLETO',json VARCHAR2(2500) PATH '$.incentivo_comboleto')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " DETALHES_OFERTARETENCAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DETALHES_OFERTARETENCAO as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DETALHES_OFERTARETENCAO',json VARCHAR2(2500) PATH '$.detalhes_ofertaretencao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " INTERNETEMDOBRO_JACLIENTE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INTERNETEMDOBRO_JACLIENTE as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INTERNETEMDOBRO_JACLIENTE',json VARCHAR2(2500) PATH '$.internetemdobro_jacliente')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " INTERNETEMDOBRO_NAOCLIENTE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INTERNETEMDOBRO_NAOCLIENTE as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INTERNETEMDOBRO_NAOCLIENTE',json VARCHAR2(2500) PATH '$.internetemdobro_naocliente')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT BENEFICIOINTERNET_ANTERIORDTVENDAURA as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.BENEFICIOINTERNET_ANTERIORDTVENDAURA',json VARCHAR2(2500) PATH '$.beneficiointernet_anteriordtvendaura')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT BENEFICIOINTERNET_APOSDTVENDAURA as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.BENEFICIOINTERNET_APOSDTVENDAURA',json VARCHAR2(2500) PATH '$.beneficiointernet_aposdtvendaura')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " FALLBACK = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT FALLBACK as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.FALLBACK',json VARCHAR2(2500) PATH '$.fallback')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_PROMOPADRAO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_PROMOPADRAO_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_PROMOPADRAO_144',json VARCHAR2(2500) PATH '$.jacliente_promopadrao_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_REGRAS_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_REGRAS_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_REGRAS_144',json VARCHAR2(2500) PATH '$.jacliente_regras_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_VALIDADE_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_VALIDADE_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_VALIDADE_144',json VARCHAR2(2500) PATH '$.jacliente_validade_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_SALDO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SALDO_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SALDO_144',json VARCHAR2(2500) PATH '$.jacliente_saldo_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_CONTING_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_CONTING_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_CONTING_144',json VARCHAR2(2500) PATH '$.jacliente_conting_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " NAOCLIENTE_INFORMAPROMO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_INFORMAPROMO_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_INFORMAPROMO_144',json VARCHAR2(2500) PATH '$.naocliente_informapromo_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " NAOCLIENTE_REGRAS_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_REGRAS_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_REGRAS_144',json VARCHAR2(2500) PATH '$.naocliente_regras_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " NAOCLIENTE_VALIDADE_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_VALIDADE_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_VALIDADE_144',json VARCHAR2(2500) PATH '$.naocliente_validade_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " CONECTADO_INCENTIVO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CONECTADO_INCENTIVO_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CONECTADO_INCENTIVO_144',json VARCHAR2(2500) PATH '$.conectado_incentivo_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " CONECTADO_INCENTIVOPROMOCAO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CONECTADO_INCENTIVOPROMOCAO_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CONECTADO_INCENTIVOPROMOCAO_144',json VARCHAR2(2500) PATH '$.conectado_incentivopromocao_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " JACLIENTE_SVA_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SVA_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SVA_144',json VARCHAR2(2500) PATH '$.jacliente_sva_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " INCENTIVO_COMBOLETO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO_COMBOLETO_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO_COMBOLETO_144',json VARCHAR2(2500) PATH '$.incentivo_comboleto_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " DETALHES_OFERTARETENCAO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DETALHES_OFERTARETENCAO_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DETALHES_OFERTARETENCAO_144',json VARCHAR2(2500) PATH '$.detalhes_ofertaretencao_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " INTERNETEMDOBRO_JACLIENTE_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INTERNETEMDOBRO_JACLIENTE_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INTERNETEMDOBRO_JACLIENTE_144',json VARCHAR2(2500) PATH '$.internetemdobro_jacliente_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " INTERNETEMDOBRO_NAOCLIENTE_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INTERNETEMDOBRO_NAOCLIENTE_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INTERNETEMDOBRO_NAOCLIENTE_144',json VARCHAR2(2500) PATH '$.internetemdobro_naocliente_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT BENEFICIOINTERNET_ANTERIORDTVENDAURA_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.BENEFICIOINTERNET_ANTERIORDTVENDAURA_144',json VARCHAR2(2500) PATH '$.beneficiointernet_anteriordtvendaura_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT BENEFICIOINTERNET_APOSDTVENDAURA_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.BENEFICIOINTERNET_APOSDTVENDAURA_144',json VARCHAR2(2500) PATH '$.beneficiointernet_aposdtvendaura_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + " FALLBACK_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT FALLBACK_144 as coluna,jsonEdit,json FROM FRASES_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.FALLBACK_144',json VARCHAR2(2500) PATH '$.fallback_144')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO FRASES_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " JACLIENTE_PROMOPADRAO,\n"
            + " JACLIENTE_REGRAS,\n"
            + " JACLIENTE_VALIDADE,\n"
            + " JACLIENTE_SALDO,\n"
            + " JACLIENTE_CONTING,\n"
            + " NAOCLIENTE_INFORMAPROMO,\n"
            + " NAOCLIENTE_REGRAS,\n"
            + " NAOCLIENTE_VALIDADE,\n"
            + " CONECTADO_INCENTIVO,\n"
            + " CONECTADO_INCENTIVOPROMOCAO,\n"
            + " JACLIENTE_SVA,\n"
            + " INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTERNETEMDOBRO_JACLIENTE,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA,\n"
            + " FALLBACK,\n"
            + " JACLIENTE_PROMOPADRAO_144,\n"
            + " JACLIENTE_REGRAS_144,\n"
            + " JACLIENTE_VALIDADE_144,\n"
            + " JACLIENTE_SALDO_144,\n"
            + " JACLIENTE_CONTING_144,\n"
            + " NAOCLIENTE_INFORMAPROMO_144,\n"
            + " NAOCLIENTE_REGRAS_144,\n"
            + " NAOCLIENTE_VALIDADE_144,\n"
            + " CONECTADO_INCENTIVO_144,\n"
            + " CONECTADO_INCENTIVOPROMOCAO_144,\n"
            + " JACLIENTE_SVA_144,\n"
            + " INCENTIVO_COMBOLETO_144,\n"
            + " DETALHES_OFERTARETENCAO_144,\n"
            + " INTERNETEMDOBRO_JACLIENTE_144,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE_144,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA_144,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA_144,\n"
            + " FALLBACK_144,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " JACLIENTE_PROMOPADRAO,\n"
            + " JACLIENTE_REGRAS,\n"
            + " JACLIENTE_VALIDADE,\n"
            + " JACLIENTE_SALDO,\n"
            + " JACLIENTE_CONTING,\n"
            + " NAOCLIENTE_INFORMAPROMO,\n"
            + " NAOCLIENTE_REGRAS,\n"
            + " NAOCLIENTE_VALIDADE,\n"
            + " CONECTADO_INCENTIVO,\n"
            + " CONECTADO_INCENTIVOPROMOCAO,\n"
            + " JACLIENTE_SVA,\n"
            + " INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTERNETEMDOBRO_JACLIENTE,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA,\n"
            + " FALLBACK,\n"
            + " JACLIENTE_PROMOPADRAO_144,\n"
            + " JACLIENTE_REGRAS_144,\n"
            + " JACLIENTE_VALIDADE_144,\n"
            + " JACLIENTE_SALDO_144,\n"
            + " JACLIENTE_CONTING_144,\n"
            + " NAOCLIENTE_INFORMAPROMO_144,\n"
            + " NAOCLIENTE_REGRAS_144,\n"
            + " NAOCLIENTE_VALIDADE_144,\n"
            + " CONECTADO_INCENTIVO_144,\n"
            + " CONECTADO_INCENTIVOPROMOCAO_144,\n"
            + " JACLIENTE_SVA_144,\n"
            + " INCENTIVO_COMBOLETO_144,\n"
            + " DETALHES_OFERTARETENCAO_144,\n"
            + " INTERNETEMDOBRO_JACLIENTE_144,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE_144,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA_144,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA_144,\n"
            + " FALLBACK_144,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM FRASES_CONTROLE WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO FRASES_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " JACLIENTE_PROMOPADRAO,\n"
            + " JACLIENTE_REGRAS,\n"
            + " JACLIENTE_VALIDADE,\n"
            + " JACLIENTE_SALDO,\n"
            + " JACLIENTE_CONTING,\n"
            + " NAOCLIENTE_INFORMAPROMO,\n"
            + " NAOCLIENTE_REGRAS,\n"
            + " NAOCLIENTE_VALIDADE,\n"
            + " CONECTADO_INCENTIVO,\n"
            + " CONECTADO_INCENTIVOPROMOCAO,\n"
            + " JACLIENTE_SVA,\n"
            + " INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTERNETEMDOBRO_JACLIENTE,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA,\n"
            + " FALLBACK,\n"
            + " JACLIENTE_PROMOPADRAO_144,\n"
            + " JACLIENTE_REGRAS_144,\n"
            + " JACLIENTE_VALIDADE_144,\n"
            + " JACLIENTE_SALDO_144,\n"
            + " JACLIENTE_CONTING_144,\n"
            + " NAOCLIENTE_INFORMAPROMO_144,\n"
            + " NAOCLIENTE_REGRAS_144,\n"
            + " NAOCLIENTE_VALIDADE_144,\n"
            + " CONECTADO_INCENTIVO_144,\n"
            + " CONECTADO_INCENTIVOPROMOCAO_144,\n"
            + " JACLIENTE_SVA_144,\n"
            + " INCENTIVO_COMBOLETO_144,\n"
            + " DETALHES_OFERTARETENCAO_144,\n"
            + " INTERNETEMDOBRO_JACLIENTE_144,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE_144,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA_144,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA_144,\n"
            + " FALLBACK_144,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " JACLIENTE_PROMOPADRAO,\n"
            + " JACLIENTE_REGRAS,\n"
            + " JACLIENTE_VALIDADE,\n"
            + " JACLIENTE_SALDO,\n"
            + " JACLIENTE_CONTING,\n"
            + " NAOCLIENTE_INFORMAPROMO,\n"
            + " NAOCLIENTE_REGRAS,\n"
            + " NAOCLIENTE_VALIDADE,\n"
            + " CONECTADO_INCENTIVO,\n"
            + " CONECTADO_INCENTIVOPROMOCAO,\n"
            + " JACLIENTE_SVA,\n"
            + " INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTERNETEMDOBRO_JACLIENTE,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA,\n"
            + " FALLBACK,\n"
            + " JACLIENTE_PROMOPADRAO_144,\n"
            + " JACLIENTE_REGRAS_144,\n"
            + " JACLIENTE_VALIDADE_144,\n"
            + " JACLIENTE_SALDO_144,\n"
            + " JACLIENTE_CONTING_144,\n"
            + " NAOCLIENTE_INFORMAPROMO_144,\n"
            + " NAOCLIENTE_REGRAS_144,\n"
            + " NAOCLIENTE_VALIDADE_144,\n"
            + " CONECTADO_INCENTIVO_144,\n"
            + " CONECTADO_INCENTIVOPROMOCAO_144,\n"
            + " JACLIENTE_SVA_144,\n"
            + " INCENTIVO_COMBOLETO_144,\n"
            + " DETALHES_OFERTARETENCAO_144,\n"
            + " INTERNETEMDOBRO_JACLIENTE_144,\n"
            + " INTERNETEMDOBRO_NAOCLIENTE_144,\n"
            + " BENEFICIOINTERNET_ANTERIORDTVENDAURA_144,\n"
            + " BENEFICIOINTERNET_APOSDTVENDAURA_144,\n"
            + " FALLBACK_144,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM FRASES_CONTROLE WHERE ID IN (?))";

    public static final String APROVAR
            = " t1.IDBENEFICIO = t2.IDBENEFICIO,\n"
            + " t1.IDPROGRAMA = t2.IDPROGRAMA,\n"
            + " t1.DDD = t2.DDD,\n"
            + " t1.JACLIENTE_PROMOPADRAO = t2.JACLIENTE_PROMOPADRAO,\n"
            + " t1.JACLIENTE_REGRAS = t2.JACLIENTE_REGRAS,\n"
            + " t1.JACLIENTE_VALIDADE = t2.JACLIENTE_VALIDADE,\n"
            + " t1.JACLIENTE_SALDO = t2.JACLIENTE_SALDO,\n"
            + " t1.JACLIENTE_CONTING = t2.JACLIENTE_CONTING,\n"
            + " t1.NAOCLIENTE_INFORMAPROMO = t2.NAOCLIENTE_INFORMAPROMO,\n"
            + " t1.NAOCLIENTE_REGRAS = t2.NAOCLIENTE_REGRAS,\n"
            + " t1.NAOCLIENTE_VALIDADE = t2.NAOCLIENTE_VALIDADE,\n"
            + " t1.CONECTADO_INCENTIVO = t2.CONECTADO_INCENTIVO,\n"
            + " t1.CONECTADO_INCENTIVOPROMOCAO = t2.CONECTADO_INCENTIVOPROMOCAO,\n"
            + " t1.JACLIENTE_SVA = t2.JACLIENTE_SVA,\n"
            + " t1.INCENTIVO_COMBOLETO = t2.INCENTIVO_COMBOLETO,\n"
            + " t1.DETALHES_OFERTARETENCAO = t2.DETALHES_OFERTARETENCAO,\n"
            + " t1.INTERNETEMDOBRO_JACLIENTE = t2.INTERNETEMDOBRO_JACLIENTE,\n"
            + " t1.INTERNETEMDOBRO_NAOCLIENTE = t2.INTERNETEMDOBRO_NAOCLIENTE,\n"
            + " t1.BENEFICIOINTERNET_ANTERIORDTVENDAURA = t2.BENEFICIOINTERNET_ANTERIORDTVENDAURA,\n"
            + " t1.BENEFICIOINTERNET_APOSDTVENDAURA = t2.BENEFICIOINTERNET_APOSDTVENDAURA,\n"
            + " t1.FALLBACK = t2.FALLBACK,\n"
            + " t1.JACLIENTE_PROMOPADRAO_144 = t2.JACLIENTE_PROMOPADRAO_144,\n"
            + " t1.JACLIENTE_REGRAS_144 = t2.JACLIENTE_REGRAS_144,\n"
            + " t1.JACLIENTE_VALIDADE_144 = t2.JACLIENTE_VALIDADE_144,\n"
            + " t1.JACLIENTE_SALDO_144 = t2.JACLIENTE_SALDO_144,\n"
            + " t1.JACLIENTE_CONTING_144 = t2.JACLIENTE_CONTING_144,\n"
            + " t1.NAOCLIENTE_INFORMAPROMO_144 = t2.NAOCLIENTE_INFORMAPROMO_144,\n"
            + " t1.NAOCLIENTE_REGRAS_144 = t2.NAOCLIENTE_REGRAS_144,\n"
            + " t1.NAOCLIENTE_VALIDADE_144 = t2.NAOCLIENTE_VALIDADE_144,\n"
            + " t1.CONECTADO_INCENTIVO_144 = t2.CONECTADO_INCENTIVO_144,\n"
            + " t1.CONECTADO_INCENTIVOPROMOCAO_144 = t2.CONECTADO_INCENTIVOPROMOCAO_144,\n"
            + " t1.JACLIENTE_SVA_144 = t2.JACLIENTE_SVA_144,\n"
            + " t1.INCENTIVO_COMBOLETO_144 = t2.INCENTIVO_COMBOLETO_144,\n"
            + " t1.DETALHES_OFERTARETENCAO_144 = t2.DETALHES_OFERTARETENCAO_144,\n"
            + " t1.INTERNETEMDOBRO_JACLIENTE_144 = t2.INTERNETEMDOBRO_JACLIENTE_144,\n"
            + " t1.INTERNETEMDOBRO_NAOCLIENTE_144 = t2.INTERNETEMDOBRO_NAOCLIENTE_144,\n"
            + " t1.BENEFICIOINTERNET_ANTERIORDTVENDAURA_144 = t2.BENEFICIOINTERNET_ANTERIORDTVENDAURA_144,\n"
            + " t1.BENEFICIOINTERNET_APOSDTVENDAURA_144 = t2.BENEFICIOINTERNET_APOSDTVENDAURA_144,\n"
            + " t1.FALLBACK_144 = t2.FALLBACK_144,\n"
            + "t1.HISTORY = t2.HISTORY";

}
