/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author mpma0
 */
public class TabelaPromptCartaoMenu {

    public static final String SELECT
            = "SELECT '' as json,\n" +
            "TB_ID_BENEFICIO,\n" +
            "TB_ID_PROGRAMA,\n" +
            "TB_DDD,\n" +
            "CLIENTE_MENSAGEMINICIAL_USSD,\n" +
            "CLIENTE_REGRATORPEDO_USSD,\n" +
            "CLIENTE_REGRALIGACAO_USSD,\n" +
            "CLIENTE_REGRADADOS_USSD,\n" +
            "CLIENTE_SVA_USSD,\n" +
            "CLIENTE_COMOUSAR_USSD,\n" +
            "REGRALIGACAOOIMOVEL_USSD,\n" +
            "REGRALIGACAOOIMOVELFIXO_USSD,\n" +
            "REGRALIGACAOMIX_USSD,\n" +
            "RECEBEBONUSINICIOPROMODEGRAU_USSD,\n" +
            "RECEBEBONUSMAX_USSD,\n" +
            "RECEBEBONUSMINDEGRAU2_USSD,\n" +
            "RECEBEBONUSMINDEGRAU3_USSD,\n" +
            "RECEBEBONUSMINDEGRAU2E3_USSD,\n" +
            "RECEBEBONUSMAX3_USSD,\n" +
            "NAOCLIENTE_MENSAGEMINICIAL_USSD,\n" +
            "NAOCLIENTE_REGRATORPEDO_USSD,\n" +
            "NAOCLIENTE_REGRALIGACAO_USSD,\n" +
            "NAOCLIENTE_COMOUSAR_USSD,\n" +
            "NAOCLIENTE_VALIDADEPROMO_USSD,\n" +
            "NAOCLIENTE_REGRADADOS_USSD,\n" +
            "PROMOOICARTAO_USSD,\n" +
            "OFERTA_PRE_USSD,\n" +
            "CLIENTE_MENSAGEMINICIAL_144,\n" +
            "CLIENTE_REGRATORPEDO_144,\n" +
            "CLIENTE_REGRALIGACAO_144,\n" +
            "CLIENTE_REGRADADOS_144,\n" +
            "CLIENTE_SVA_144,\n" +
            "CLIENTE_COMOUSAR_144,\n" +
            "REGRALIGACAOOIMOVEL_144,\n" +
            "REGRALIGACAOOIMOVELFIXO_144,\n" +
            "REGRALIGACAOMIX_144,\n" +
            "RECEBEBONUSINICIOPROMODEGRAU_144,\n" +
            "RECEBEBONUSMAX_144,\n" +
            "RECEBEBONUSMINDEGRAU2_144,\n" +
            "RECEBEBONUSMINDEGRAU3_144,\n" +
            "RECEBEBONUSMINDEGRAU2E3_144,\n" +
            "RECEBEBONUSMAX3_144,\n" +
            "NAOCLIENTE_MENSAGEMINICIAL_144,\n" +
            "NAOCLIENTE_REGRATORPEDO_144,\n" +
            "NAOCLIENTE_REGRALIGACAO_144,\n" +
            "NAOCLIENTE_COMOUSAR_144,\n" +
            "NAOCLIENTE_VALIDADEPROMO_144,\n" +
            "NAOCLIENTE_REGRADADOS_144,\n" +
            "PROMOOICARTAO_144,\n" +
            "OFERTA_PRE_144,\n" +
            "t.ID,t.TEMPID,t.HISTORY,t.INSERTED,t.DT_GMUD,t.DELETED FROM PROMPT_CARTAOMENU t WHERE (t.DT_GMUD IS NULL AND t.DELETED = 0) OR (t.DT_GMUD IS NOT NULL) ORDER BY t.INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO PROMPT_CARTAOMENU (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	CLIENTE_REGRATORPEDO_USSD,\n"
            + "	CLIENTE_REGRALIGACAO_USSD,\n"
            + "	CLIENTE_REGRADADOS_USSD,\n"
            + "	CLIENTE_SVA_USSD,\n"
            + "	CLIENTE_COMOUSAR_USSD,\n"
            + "	REGRALIGACAOOIMOVEL_USSD,\n"
            + "	REGRALIGACAOOIMOVELFIXO_USSD,\n"
            + "	REGRALIGACAOMIX_USSD,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_USSD,\n"
            + "	RECEBEBONUSMAX_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU3_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_USSD,\n"
            + "	RECEBEBONUSMAX3_USSD,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	NAOCLIENTE_REGRATORPEDO_USSD,\n"
            + "	NAOCLIENTE_REGRALIGACAO_USSD,\n"
            + "	NAOCLIENTE_COMOUSAR_USSD,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_USSD,\n"
            + "	NAOCLIENTE_REGRADADOS_USSD,\n"
            + "	PROMOOICARTAO_USSD,\n"
            + "	OFERTA_PRE_USSD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_144,\n"
            + "	CLIENTE_REGRATORPEDO_144,\n"
            + "	CLIENTE_REGRALIGACAO_144,\n"
            + "	CLIENTE_REGRADADOS_144,\n"
            + "	CLIENTE_SVA_144,\n"
            + "	CLIENTE_COMOUSAR_144,\n"
            + "	REGRALIGACAOOIMOVEL_144,\n"
            + "	REGRALIGACAOOIMOVELFIXO_144,\n"
            + "	REGRALIGACAOMIX_144,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_144,\n"
            + "	RECEBEBONUSMAX_144,\n"
            + "	RECEBEBONUSMINDEGRAU2_144,\n"
            + "	RECEBEBONUSMINDEGRAU3_144,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_144,\n"
            + "	RECEBEBONUSMAX3_144,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_144,\n"
            + "	NAOCLIENTE_REGRATORPEDO_144,\n"
            + "	NAOCLIENTE_REGRALIGACAO_144,\n"
            + "	NAOCLIENTE_COMOUSAR_144,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_144,\n"
            + "	NAOCLIENTE_REGRADADOS_144,\n"
            + "	PROMOOICARTAO_144,\n"
            + "	OFERTA_PRE_144,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	CLIENTE_REGRATORPEDO_USSD,\n"
            + "	CLIENTE_REGRALIGACAO_USSD,\n"
            + "	CLIENTE_REGRADADOS_USSD,\n"
            + "	CLIENTE_SVA_USSD,\n"
            + "	CLIENTE_COMOUSAR_USSD,\n"
            + "	REGRALIGACAOOIMOVEL_USSD,\n"
            + "	REGRALIGACAOOIMOVELFIXO_USSD,\n"
            + "	REGRALIGACAOMIX_USSD,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_USSD,\n"
            + "	RECEBEBONUSMAX_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU3_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_USSD,\n"
            + "	RECEBEBONUSMAX3_USSD,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	NAOCLIENTE_REGRATORPEDO_USSD,\n"
            + "	NAOCLIENTE_REGRALIGACAO_USSD,\n"
            + "	NAOCLIENTE_COMOUSAR_USSD,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_USSD,\n"
            + "	NAOCLIENTE_REGRADADOS_USSD,\n"
            + "	PROMOOICARTAO_USSD,\n"
            + "	OFERTA_PRE_USSD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_144,\n"
            + "	CLIENTE_REGRATORPEDO_144,\n"
            + "	CLIENTE_REGRALIGACAO_144,\n"
            + "	CLIENTE_REGRADADOS_144,\n"
            + "	CLIENTE_SVA_144,\n"
            + "	CLIENTE_COMOUSAR_144,\n"
            + "	REGRALIGACAOOIMOVEL_144,\n"
            + "	REGRALIGACAOOIMOVELFIXO_144,\n"
            + "	REGRALIGACAOMIX_144,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_144,\n"
            + "	RECEBEBONUSMAX_144,\n"
            + "	RECEBEBONUSMINDEGRAU2_144,\n"
            + "	RECEBEBONUSMINDEGRAU3_144,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_144,\n"
            + "	RECEBEBONUSMAX3_144,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_144,\n"
            + "	NAOCLIENTE_REGRATORPEDO_144,\n"
            + "	NAOCLIENTE_REGRALIGACAO_144,\n"
            + "	NAOCLIENTE_COMOUSAR_144,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_144,\n"
            + "	NAOCLIENTE_REGRADADOS_144,\n"
            + "	PROMOOICARTAO_144,\n"
            + "	OFERTA_PRE_144,\n"
            + "	?,\n"
            + "   DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + "	TB_ID_BENEFICIO VARCHAR2(2500) PATH '$.tb_id_beneficio',\n"
            + "	TB_ID_PROGRAMA VARCHAR2(2500) PATH '$.tb_id_programa',\n"
            + "	TB_DDD VARCHAR2(2500) PATH '$.tb_ddd',\n"
            + "	CLIENTE_MENSAGEMINICIAL_USSD VARCHAR2(2500) PATH '$.cliente_mensageminicial_ussd',\n"
            + "	CLIENTE_REGRATORPEDO_USSD VARCHAR2(2500) PATH '$.cliente_regratorpedo_ussd',\n"
            + "	CLIENTE_REGRALIGACAO_USSD VARCHAR2(2500) PATH '$.cliente_regraligacao_ussd',\n"
            + "	CLIENTE_REGRADADOS_USSD VARCHAR2(2500) PATH '$.cliente_regradados_ussd',\n"
            + "	CLIENTE_SVA_USSD VARCHAR2(2500) PATH '$.cliente_sva_ussd',\n"
            + "	CLIENTE_COMOUSAR_USSD VARCHAR2(2500) PATH '$.cliente_comousar_ussd',\n"
            + "	REGRALIGACAOOIMOVEL_USSD VARCHAR2(2500) PATH '$.regraligacaooimovel_ussd',\n"
            + "	REGRALIGACAOOIMOVELFIXO_USSD VARCHAR2(2500) PATH '$.regraligacaooimovelfixo_ussd',\n"
            + "	REGRALIGACAOMIX_USSD VARCHAR2(2500) PATH '$.regraligacaomix_ussd',\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_USSD VARCHAR2(2500) PATH '$.recebebonusiniciopromodegrau_ussd',\n"
            + "	RECEBEBONUSMAX_USSD VARCHAR2(2500) PATH '$.recebebonusmax_ussd',\n"
            + "	RECEBEBONUSMINDEGRAU2_USSD VARCHAR2(2500) PATH '$.recebebonusmindegrau2_ussd',\n"
            + "	RECEBEBONUSMINDEGRAU3_USSD VARCHAR2(2500) PATH '$.recebebonusmindegrau3_ussd',\n"
            + "	RECEBEBONUSMINDEGRAU2E3_USSD VARCHAR2(2500) PATH '$.recebebonusmindegrau2e3_ussd',\n"
            + "	RECEBEBONUSMAX3_USSD VARCHAR2(2500) PATH '$.recebebonusmax3_ussd',\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_USSD VARCHAR2(2500) PATH '$.naocliente_mensageminicial_ussd',\n"
            + "	NAOCLIENTE_REGRATORPEDO_USSD VARCHAR2(2500) PATH '$.naocliente_regratorpedo_ussd',\n"
            + "	NAOCLIENTE_REGRALIGACAO_USSD VARCHAR2(2500) PATH '$.naocliente_regraligacao_ussd',\n"
            + "	NAOCLIENTE_COMOUSAR_USSD VARCHAR2(2500) PATH '$.naocliente_comousar_ussd',\n"
            + "	NAOCLIENTE_VALIDADEPROMO_USSD VARCHAR2(2500) PATH '$.naocliente_validadepromo_ussd',\n"
            + "	NAOCLIENTE_REGRADADOS_USSD VARCHAR2(2500) PATH '$.naocliente_regradados_ussd',\n"
            + "	PROMOOICARTAO_USSD VARCHAR2(2500) PATH '$.promooicartao_ussd',\n"
            + "	OFERTA_PRE_USSD VARCHAR2(2500) PATH '$.oferta_pre_ussd',\n"
            + "	CLIENTE_MENSAGEMINICIAL_144 VARCHAR2(2500) PATH '$.cliente_mensageminicial_144',\n"
            + "	CLIENTE_REGRATORPEDO_144 VARCHAR2(2500) PATH '$.cliente_regratorpedo_144',\n"
            + "	CLIENTE_REGRALIGACAO_144 VARCHAR2(2500) PATH '$.cliente_regraligacao_144',\n"
            + "	CLIENTE_REGRADADOS_144 VARCHAR2(2500) PATH '$.cliente_regradados_144',\n"
            + "	CLIENTE_SVA_144 VARCHAR2(2500) PATH '$.cliente_sva_144',\n"
            + "	CLIENTE_COMOUSAR_144 VARCHAR2(2500) PATH '$.cliente_comousar_144',\n"
            + "	REGRALIGACAOOIMOVEL_144 VARCHAR2(2500) PATH '$.regraligacaooimovel_144',\n"
            + "	REGRALIGACAOOIMOVELFIXO_144 VARCHAR2(2500) PATH '$.regraligacaooimovelfixo_144',\n"
            + "	REGRALIGACAOMIX_144 VARCHAR2(2500) PATH '$.regraligacaomix_144',\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_144 VARCHAR2(2500) PATH '$.recebebonusiniciopromodegrau_144',\n"
            + "	RECEBEBONUSMAX_144 VARCHAR2(2500) PATH '$.recebebonusmax_144',\n"
            + "	RECEBEBONUSMINDEGRAU2_144 VARCHAR2(2500) PATH '$.recebebonusmindegrau2_144',\n"
            + "	RECEBEBONUSMINDEGRAU3_144 VARCHAR2(2500) PATH '$.recebebonusmindegrau3_144',\n"
            + "	RECEBEBONUSMINDEGRAU2E3_144 VARCHAR2(2500) PATH '$.recebebonusmindegrau2e3_144',\n"
            + "	RECEBEBONUSMAX3_144 VARCHAR2(2500) PATH '$.recebebonusmax3_144',\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_144 VARCHAR2(2500) PATH '$.naocliente_mensageminicial_144',\n"
            + "	NAOCLIENTE_REGRATORPEDO_144 VARCHAR2(2500) PATH '$.naocliente_regratorpedo_144',\n"
            + "	NAOCLIENTE_REGRALIGACAO_144 VARCHAR2(2500) PATH '$.naocliente_regraligacao_144',\n"
            + "	NAOCLIENTE_COMOUSAR_144 VARCHAR2(2500) PATH '$.naocliente_comousar_144',\n"
            + "	NAOCLIENTE_VALIDADEPROMO_144 VARCHAR2(2500) PATH '$.naocliente_validadepromo_144',\n"
            + "	NAOCLIENTE_REGRADADOS_144 VARCHAR2(2500) PATH '$.naocliente_regradados_144',\n"
            + "	PROMOOICARTAO_144 VARCHAR2(2500) PATH '$.promooicartao_144',\n"
            + "	OFERTA_PRE_144 VARCHAR2(2500) PATH '$.oferta_pre_144',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE PROMPT_CARTAOMENU SET \n"
            + "	TB_ID_BENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_BENEFICIO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_BENEFICIO',json NUMBER(38,0) PATH '$.tb_id_beneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_ID_PROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_PROGRAMA as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_PROGRAMA',json NUMBER(38,0) PATH '$.tb_id_programa')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_DDD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_DDD',json VARCHAR2(2500) PATH '$.tb_ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_MENSAGEMINICIAL_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_MENSAGEMINICIAL_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_MENSAGEMINICIAL_USSD',json VARCHAR2(2500) PATH '$.cliente_mensageminicial_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_REGRATORPEDO_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_REGRATORPEDO_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_REGRATORPEDO_USSD',json VARCHAR2(2500) PATH '$.cliente_regratorpedo_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_REGRALIGACAO_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_REGRALIGACAO_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_REGRALIGACAO_USSD',json VARCHAR2(2500) PATH '$.cliente_regraligacao_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_REGRADADOS_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_REGRADADOS_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_REGRADADOS_USSD',json VARCHAR2(2500) PATH '$.cliente_regradados_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_SVA_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_SVA_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_SVA_USSD',json VARCHAR2(2500) PATH '$.cliente_sva_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_COMOUSAR_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_COMOUSAR_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_COMOUSAR_USSD',json VARCHAR2(2500) PATH '$.cliente_comousar_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	REGRALIGACAOOIMOVEL_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT REGRALIGACAOOIMOVEL_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.REGRALIGACAOOIMOVEL_USSD',json VARCHAR2(2500) PATH '$.regraligacaooimovel_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	REGRALIGACAOOIMOVELFIXO_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT REGRALIGACAOOIMOVELFIXO_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.REGRALIGACAOOIMOVELFIXO_USSD',json VARCHAR2(2500) PATH '$.regraligacaooimovelfixo_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	REGRALIGACAOMIX_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT REGRALIGACAOMIX_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.REGRALIGACAOMIX_USSD',json VARCHAR2(2500) PATH '$.regraligacaomix_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSINICIOPROMODEGRAU_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSINICIOPROMODEGRAU_USSD',json VARCHAR2(2500) PATH '$.recebebonusiniciopromodegrau_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMAX_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMAX_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMAX_USSD',json VARCHAR2(2500) PATH '$.recebebonusmax_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMINDEGRAU2_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMINDEGRAU2_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMINDEGRAU2_USSD',json VARCHAR2(2500) PATH '$.recebebonusmindegrau2_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMINDEGRAU3_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMINDEGRAU3_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMINDEGRAU3_USSD',json VARCHAR2(2500) PATH '$.recebebonusmindegrau3_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMINDEGRAU2E3_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMINDEGRAU2E3_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMINDEGRAU2E3_USSD',json VARCHAR2(2500) PATH '$.recebebonusmindegrau2e3_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMAX3_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMAX3_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMAX3_USSD',json VARCHAR2(2500) PATH '$.recebebonusmax3_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_MENSAGEMINICIAL_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_MENSAGEMINICIAL_USSD',json VARCHAR2(2500) PATH '$.naocliente_mensageminicial_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_REGRATORPEDO_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_REGRATORPEDO_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_REGRATORPEDO_USSD',json VARCHAR2(2500) PATH '$.naocliente_regratorpedo_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_REGRALIGACAO_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_REGRALIGACAO_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_REGRALIGACAO_USSD',json VARCHAR2(2500) PATH '$.naocliente_regraligacao_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_COMOUSAR_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_COMOUSAR_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_COMOUSAR_USSD',json VARCHAR2(2500) PATH '$.naocliente_comousar_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_VALIDADEPROMO_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_VALIDADEPROMO_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_VALIDADEPROMO_USSD',json VARCHAR2(2500) PATH '$.naocliente_validadepromo_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_REGRADADOS_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_REGRADADOS_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_REGRADADOS_USSD',json VARCHAR2(2500) PATH '$.naocliente_regradados_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	PROMOOICARTAO_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT PROMOOICARTAO_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.PROMOOICARTAO_USSD',json VARCHAR2(2500) PATH '$.promooicartao_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTA_PRE_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTA_PRE_USSD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTA_PRE_USSD',json VARCHAR2(2500) PATH '$.oferta_pre_ussd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_MENSAGEMINICIAL_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_MENSAGEMINICIAL_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_MENSAGEMINICIAL_144',json VARCHAR2(2500) PATH '$.cliente_mensageminicial_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_REGRATORPEDO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_REGRATORPEDO_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_REGRATORPEDO_144',json VARCHAR2(2500) PATH '$.cliente_regratorpedo_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_REGRALIGACAO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_REGRALIGACAO_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_REGRALIGACAO_144',json VARCHAR2(2500) PATH '$.cliente_regraligacao_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_REGRADADOS_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_REGRADADOS_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_REGRADADOS_144',json VARCHAR2(2500) PATH '$.cliente_regradados_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_SVA_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_SVA_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_SVA_144',json VARCHAR2(2500) PATH '$.cliente_sva_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CLIENTE_COMOUSAR_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CLIENTE_COMOUSAR_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CLIENTE_COMOUSAR_144',json VARCHAR2(2500) PATH '$.cliente_comousar_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	REGRALIGACAOOIMOVEL_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT REGRALIGACAOOIMOVEL_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.REGRALIGACAOOIMOVEL_144',json VARCHAR2(2500) PATH '$.regraligacaooimovel_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	REGRALIGACAOOIMOVELFIXO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT REGRALIGACAOOIMOVELFIXO_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.REGRALIGACAOOIMOVELFIXO_144',json VARCHAR2(2500) PATH '$.regraligacaooimovelfixo_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	REGRALIGACAOMIX_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT REGRALIGACAOMIX_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.REGRALIGACAOMIX_144',json VARCHAR2(2500) PATH '$.regraligacaomix_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSINICIOPROMODEGRAU_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSINICIOPROMODEGRAU_144',json VARCHAR2(2500) PATH '$.recebebonusiniciopromodegrau_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMAX_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMAX_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMAX_144',json VARCHAR2(2500) PATH '$.recebebonusmax_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMINDEGRAU2_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMINDEGRAU2_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMINDEGRAU2_144',json VARCHAR2(2500) PATH '$.recebebonusmindegrau2_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMINDEGRAU3_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMINDEGRAU3_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMINDEGRAU3_144',json VARCHAR2(2500) PATH '$.recebebonusmindegrau3_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMINDEGRAU2E3_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMINDEGRAU2E3_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMINDEGRAU2E3_144',json VARCHAR2(2500) PATH '$.recebebonusmindegrau2e3_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECEBEBONUSMAX3_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECEBEBONUSMAX3_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECEBEBONUSMAX3_144',json VARCHAR2(2500) PATH '$.recebebonusmax3_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_MENSAGEMINICIAL_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_MENSAGEMINICIAL_144',json VARCHAR2(2500) PATH '$.naocliente_mensageminicial_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_REGRATORPEDO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_REGRATORPEDO_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_REGRATORPEDO_144',json VARCHAR2(2500) PATH '$.naocliente_regratorpedo_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_REGRALIGACAO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_REGRALIGACAO_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_REGRALIGACAO_144',json VARCHAR2(2500) PATH '$.naocliente_regraligacao_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_COMOUSAR_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_COMOUSAR_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_COMOUSAR_144',json VARCHAR2(2500) PATH '$.naocliente_comousar_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_VALIDADEPROMO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_VALIDADEPROMO_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_VALIDADEPROMO_144',json VARCHAR2(2500) PATH '$.naocliente_validadepromo_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_REGRADADOS_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_REGRADADOS_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_REGRADADOS_144',json VARCHAR2(2500) PATH '$.naocliente_regradados_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	PROMOOICARTAO_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT PROMOOICARTAO_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.PROMOOICARTAO_144',json VARCHAR2(2500) PATH '$.promooicartao_144')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTA_PRE_144 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTA_PRE_144 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTA_PRE_144',json VARCHAR2(2500) PATH '$.oferta_pre_144')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO PROMPT_CARTAOMENU (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	CLIENTE_REGRATORPEDO_USSD,\n"
            + "	CLIENTE_REGRALIGACAO_USSD,\n"
            + "	CLIENTE_REGRADADOS_USSD,\n"
            + "	CLIENTE_SVA_USSD,\n"
            + "	CLIENTE_COMOUSAR_USSD,\n"
            + "	REGRALIGACAOOIMOVEL_USSD,\n"
            + "	REGRALIGACAOOIMOVELFIXO_USSD,\n"
            + "	REGRALIGACAOMIX_USSD,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_USSD,\n"
            + "	RECEBEBONUSMAX_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU3_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_USSD,\n"
            + "	RECEBEBONUSMAX3_USSD,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	NAOCLIENTE_REGRATORPEDO_USSD,\n"
            + "	NAOCLIENTE_REGRALIGACAO_USSD,\n"
            + "	NAOCLIENTE_COMOUSAR_USSD,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_USSD,\n"
            + "	NAOCLIENTE_REGRADADOS_USSD,\n"
            + "	PROMOOICARTAO_USSD,\n"
            + "	OFERTA_PRE_USSD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_144,\n"
            + "	CLIENTE_REGRATORPEDO_144,\n"
            + "	CLIENTE_REGRALIGACAO_144,\n"
            + "	CLIENTE_REGRADADOS_144,\n"
            + "	CLIENTE_SVA_144,\n"
            + "	CLIENTE_COMOUSAR_144,\n"
            + "	REGRALIGACAOOIMOVEL_144,\n"
            + "	REGRALIGACAOOIMOVELFIXO_144,\n"
            + "	REGRALIGACAOMIX_144,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_144,\n"
            + "	RECEBEBONUSMAX_144,\n"
            + "	RECEBEBONUSMINDEGRAU2_144,\n"
            + "	RECEBEBONUSMINDEGRAU3_144,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_144,\n"
            + "	RECEBEBONUSMAX3_144,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_144,\n"
            + "	NAOCLIENTE_REGRATORPEDO_144,\n"
            + "	NAOCLIENTE_REGRALIGACAO_144,\n"
            + "	NAOCLIENTE_COMOUSAR_144,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_144,\n"
            + "	NAOCLIENTE_REGRADADOS_144,\n"
            + "	PROMOOICARTAO_144,\n"
            + "	OFERTA_PRE_144,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	CLIENTE_REGRATORPEDO_USSD,\n"
            + "	CLIENTE_REGRALIGACAO_USSD,\n"
            + "	CLIENTE_REGRADADOS_USSD,\n"
            + "	CLIENTE_SVA_USSD,\n"
            + "	CLIENTE_COMOUSAR_USSD,\n"
            + "	REGRALIGACAOOIMOVEL_USSD,\n"
            + "	REGRALIGACAOOIMOVELFIXO_USSD,\n"
            + "	REGRALIGACAOMIX_USSD,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_USSD,\n"
            + "	RECEBEBONUSMAX_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU3_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_USSD,\n"
            + "	RECEBEBONUSMAX3_USSD,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	NAOCLIENTE_REGRATORPEDO_USSD,\n"
            + "	NAOCLIENTE_REGRALIGACAO_USSD,\n"
            + "	NAOCLIENTE_COMOUSAR_USSD,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_USSD,\n"
            + "	NAOCLIENTE_REGRADADOS_USSD,\n"
            + "	PROMOOICARTAO_USSD,\n"
            + "	OFERTA_PRE_USSD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_144,\n"
            + "	CLIENTE_REGRATORPEDO_144,\n"
            + "	CLIENTE_REGRALIGACAO_144,\n"
            + "	CLIENTE_REGRADADOS_144,\n"
            + "	CLIENTE_SVA_144,\n"
            + "	CLIENTE_COMOUSAR_144,\n"
            + "	REGRALIGACAOOIMOVEL_144,\n"
            + "	REGRALIGACAOOIMOVELFIXO_144,\n"
            + "	REGRALIGACAOMIX_144,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_144,\n"
            + "	RECEBEBONUSMAX_144,\n"
            + "	RECEBEBONUSMINDEGRAU2_144,\n"
            + "	RECEBEBONUSMINDEGRAU3_144,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_144,\n"
            + "	RECEBEBONUSMAX3_144,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_144,\n"
            + "	NAOCLIENTE_REGRATORPEDO_144,\n"
            + "	NAOCLIENTE_REGRALIGACAO_144,\n"
            + "	NAOCLIENTE_COMOUSAR_144,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_144,\n"
            + "	NAOCLIENTE_REGRADADOS_144,\n"
            + "	PROMOOICARTAO_144,\n"
            + "	OFERTA_PRE_144,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM PROMPT_CARTAOMENU WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO PROMPT_CARTAOMENU (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	CLIENTE_REGRATORPEDO_USSD,\n"
            + "	CLIENTE_REGRALIGACAO_USSD,\n"
            + "	CLIENTE_REGRADADOS_USSD,\n"
            + "	CLIENTE_SVA_USSD,\n"
            + "	CLIENTE_COMOUSAR_USSD,\n"
            + "	REGRALIGACAOOIMOVEL_USSD,\n"
            + "	REGRALIGACAOOIMOVELFIXO_USSD,\n"
            + "	REGRALIGACAOMIX_USSD,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_USSD,\n"
            + "	RECEBEBONUSMAX_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU3_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_USSD,\n"
            + "	RECEBEBONUSMAX3_USSD,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	NAOCLIENTE_REGRATORPEDO_USSD,\n"
            + "	NAOCLIENTE_REGRALIGACAO_USSD,\n"
            + "	NAOCLIENTE_COMOUSAR_USSD,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_USSD,\n"
            + "	NAOCLIENTE_REGRADADOS_USSD,\n"
            + "	PROMOOICARTAO_USSD,\n"
            + "	OFERTA_PRE_USSD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_144,\n"
            + "	CLIENTE_REGRATORPEDO_144,\n"
            + "	CLIENTE_REGRALIGACAO_144,\n"
            + "	CLIENTE_REGRADADOS_144,\n"
            + "	CLIENTE_SVA_144,\n"
            + "	CLIENTE_COMOUSAR_144,\n"
            + "	REGRALIGACAOOIMOVEL_144,\n"
            + "	REGRALIGACAOOIMOVELFIXO_144,\n"
            + "	REGRALIGACAOMIX_144,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_144,\n"
            + "	RECEBEBONUSMAX_144,\n"
            + "	RECEBEBONUSMINDEGRAU2_144,\n"
            + "	RECEBEBONUSMINDEGRAU3_144,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_144,\n"
            + "	RECEBEBONUSMAX3_144,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_144,\n"
            + "	NAOCLIENTE_REGRATORPEDO_144,\n"
            + "	NAOCLIENTE_REGRALIGACAO_144,\n"
            + "	NAOCLIENTE_COMOUSAR_144,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_144,\n"
            + "	NAOCLIENTE_REGRADADOS_144,\n"
            + "	PROMOOICARTAO_144,\n"
            + "	OFERTA_PRE_144,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_DDD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	CLIENTE_REGRATORPEDO_USSD,\n"
            + "	CLIENTE_REGRALIGACAO_USSD,\n"
            + "	CLIENTE_REGRADADOS_USSD,\n"
            + "	CLIENTE_SVA_USSD,\n"
            + "	CLIENTE_COMOUSAR_USSD,\n"
            + "	REGRALIGACAOOIMOVEL_USSD,\n"
            + "	REGRALIGACAOOIMOVELFIXO_USSD,\n"
            + "	REGRALIGACAOMIX_USSD,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_USSD,\n"
            + "	RECEBEBONUSMAX_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU3_USSD,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_USSD,\n"
            + "	RECEBEBONUSMAX3_USSD,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "	NAOCLIENTE_REGRATORPEDO_USSD,\n"
            + "	NAOCLIENTE_REGRALIGACAO_USSD,\n"
            + "	NAOCLIENTE_COMOUSAR_USSD,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_USSD,\n"
            + "	NAOCLIENTE_REGRADADOS_USSD,\n"
            + "	PROMOOICARTAO_USSD,\n"
            + "	OFERTA_PRE_USSD,\n"
            + "	CLIENTE_MENSAGEMINICIAL_144,\n"
            + "	CLIENTE_REGRATORPEDO_144,\n"
            + "	CLIENTE_REGRALIGACAO_144,\n"
            + "	CLIENTE_REGRADADOS_144,\n"
            + "	CLIENTE_SVA_144,\n"
            + "	CLIENTE_COMOUSAR_144,\n"
            + "	REGRALIGACAOOIMOVEL_144,\n"
            + "	REGRALIGACAOOIMOVELFIXO_144,\n"
            + "	REGRALIGACAOMIX_144,\n"
            + "	RECEBEBONUSINICIOPROMODEGRAU_144,\n"
            + "	RECEBEBONUSMAX_144,\n"
            + "	RECEBEBONUSMINDEGRAU2_144,\n"
            + "	RECEBEBONUSMINDEGRAU3_144,\n"
            + "	RECEBEBONUSMINDEGRAU2E3_144,\n"
            + "	RECEBEBONUSMAX3_144,\n"
            + "	NAOCLIENTE_MENSAGEMINICIAL_144,\n"
            + "	NAOCLIENTE_REGRATORPEDO_144,\n"
            + "	NAOCLIENTE_REGRALIGACAO_144,\n"
            + "	NAOCLIENTE_COMOUSAR_144,\n"
            + "	NAOCLIENTE_VALIDADEPROMO_144,\n"
            + "	NAOCLIENTE_REGRADADOS_144,\n"
            + "	PROMOOICARTAO_144,\n"
            + "	OFERTA_PRE_144,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM PROMPT_CARTAOMENU WHERE ID IN (?))";

    public static final String APROVAR
            = "t1.TB_ID_BENEFICIO = t2.TB_ID_BENEFICIO,\n"
            + "t1.TB_ID_PROGRAMA = t2.TB_ID_PROGRAMA,\n"
            + "t1.TB_DDD = t2.TB_DDD,\n"
            + "t1.CLIENTE_MENSAGEMINICIAL_USSD = t2.CLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "t1.CLIENTE_REGRATORPEDO_USSD = t2.CLIENTE_REGRATORPEDO_USSD,\n"
            + "t1.CLIENTE_REGRALIGACAO_USSD = t2.CLIENTE_REGRALIGACAO_USSD,\n"
            + "t1.CLIENTE_REGRADADOS_USSD = t2.CLIENTE_REGRADADOS_USSD,\n"
            + "t1.CLIENTE_SVA_USSD = t2.CLIENTE_SVA_USSD,\n"
            + "t1.CLIENTE_COMOUSAR_USSD = t2.CLIENTE_COMOUSAR_USSD,\n"
            + "t1.REGRALIGACAOOIMOVEL_USSD = t2.REGRALIGACAOOIMOVEL_USSD,\n"
            + "t1.REGRALIGACAOOIMOVELFIXO_USSD = t2.REGRALIGACAOOIMOVELFIXO_USSD,\n"
            + "t1.REGRALIGACAOMIX_USSD = t2.REGRALIGACAOMIX_USSD,\n"
            + "t1.RECEBEBONUSINICIOPROMODEGRAU_USSD = t2.RECEBEBONUSINICIOPROMODEGRAU_USSD,\n"
            + "t1.RECEBEBONUSMAX_USSD = t2.RECEBEBONUSMAX_USSD,\n"
            + "t1.RECEBEBONUSMINDEGRAU2_USSD = t2.RECEBEBONUSMINDEGRAU2_USSD,\n"
            + "t1.RECEBEBONUSMINDEGRAU3_USSD = t2.RECEBEBONUSMINDEGRAU3_USSD,\n"
            + "t1.RECEBEBONUSMINDEGRAU2E3_USSD = t2.RECEBEBONUSMINDEGRAU2E3_USSD,\n"
            + "t1.RECEBEBONUSMAX3_USSD = t2.RECEBEBONUSMAX3_USSD,\n"
            + "t1.NAOCLIENTE_MENSAGEMINICIAL_USSD = t2.NAOCLIENTE_MENSAGEMINICIAL_USSD,\n"
            + "t1.NAOCLIENTE_REGRATORPEDO_USSD = t2.NAOCLIENTE_REGRATORPEDO_USSD,\n"
            + "t1.NAOCLIENTE_REGRALIGACAO_USSD = t2.NAOCLIENTE_REGRALIGACAO_USSD,\n"
            + "t1.NAOCLIENTE_COMOUSAR_USSD = t2.NAOCLIENTE_COMOUSAR_USSD,\n"
            + "t1.NAOCLIENTE_VALIDADEPROMO_USSD = t2.NAOCLIENTE_VALIDADEPROMO_USSD,\n"
            + "t1.NAOCLIENTE_REGRADADOS_USSD = t2.NAOCLIENTE_REGRADADOS_USSD,\n"
            + "t1.PROMOOICARTAO_USSD = t2.PROMOOICARTAO_USSD,\n"
            + "t1.OFERTA_PRE_USSD = t2.OFERTA_PRE_USSD,\n"
            + "t1.CLIENTE_MENSAGEMINICIAL_144 = t2.CLIENTE_MENSAGEMINICIAL_144,\n"
            + "t1.CLIENTE_REGRATORPEDO_144 = t2.CLIENTE_REGRATORPEDO_144,\n"
            + "t1.CLIENTE_REGRALIGACAO_144 = t2.CLIENTE_REGRALIGACAO_144,\n"
            + "t1.CLIENTE_REGRADADOS_144 = t2.CLIENTE_REGRADADOS_144,\n"
            + "t1.CLIENTE_SVA_144 = t2.CLIENTE_SVA_144,\n"
            + "t1.CLIENTE_COMOUSAR_144 = t2.CLIENTE_COMOUSAR_144,\n"
            + "t1.REGRALIGACAOOIMOVEL_144 = t2.REGRALIGACAOOIMOVEL_144,\n"
            + "t1.REGRALIGACAOOIMOVELFIXO_144 = t2.REGRALIGACAOOIMOVELFIXO_144,\n"
            + "t1.REGRALIGACAOMIX_144 = t2.REGRALIGACAOMIX_144,\n"
            + "t1.RECEBEBONUSINICIOPROMODEGRAU_144 = t2.RECEBEBONUSINICIOPROMODEGRAU_144,\n"
            + "t1.RECEBEBONUSMAX_144 = t2.RECEBEBONUSMAX_144,\n"
            + "t1.RECEBEBONUSMINDEGRAU2_144 = t2.RECEBEBONUSMINDEGRAU2_144,\n"
            + "t1.RECEBEBONUSMINDEGRAU3_144 = t2.RECEBEBONUSMINDEGRAU3_144,\n"
            + "t1.RECEBEBONUSMINDEGRAU2E3_144 = t2.RECEBEBONUSMINDEGRAU2E3_144,\n"
            + "t1.RECEBEBONUSMAX3_144 = t2.RECEBEBONUSMAX3_144,\n"
            + "t1.NAOCLIENTE_MENSAGEMINICIAL_144 = t2.NAOCLIENTE_MENSAGEMINICIAL_144,\n"
            + "t1.NAOCLIENTE_REGRATORPEDO_144 = t2.NAOCLIENTE_REGRATORPEDO_144,\n"
            + "t1.NAOCLIENTE_REGRALIGACAO_144 = t2.NAOCLIENTE_REGRALIGACAO_144,\n"
            + "t1.NAOCLIENTE_COMOUSAR_144 = t2.NAOCLIENTE_COMOUSAR_144,\n"
            + "t1.NAOCLIENTE_VALIDADEPROMO_144 = t2.NAOCLIENTE_VALIDADEPROMO_144,\n"
            + "t1.NAOCLIENTE_REGRADADOS_144 = t2.NAOCLIENTE_REGRADADOS_144,\n"
            + "t1.PROMOOICARTAO_144 = t2.PROMOOICARTAO_144,\n"
            + "t1.OFERTA_PRE_144 = t2.OFERTA_PRE_144,\n"
            + "t1.HISTORY = t2.HISTORY";

}
