/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author mpma0
 */
public class TabelaBoCartao {

    public static final String SELECT
            = "SELECT JSON_QUERY(\n"
            + "	concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(\n"
            + "	concat(concat('{\"idbeneficio\":\"',IDBENEFICIO),'\",'),\n"
            + "	concat(concat('\"idprograma\":\"',IDPROGRAMA),'\",')),\n"
            + "	concat(concat('\"ddd\":\"',DDD),'\",')),\n"
            + "	concat(concat('\"cpfxc_promopadrao\":\"',CPFXC_PROMOPADRAO),'\",')),\n"
            + "	concat(concat('\"cpfxc_semrecarga\":\"',CPFXC_SEMRECARGA),'\",')),\n"
            + "	concat(concat('\"cpfxc_chamada\":\"',CPFXC_CHAMADA),'\",')),\n"
            + "	concat(concat('\"cpfxc_detalhes\":\"',CPFXC_DETALHES),'\",')),\n"
            + "	concat(concat('\"cpfxc_recarga\":\"',CPFXC_RECARGA),'\",')),\n"
            + "	concat(concat('\"cpfxc_informavalidade\":\"',CPFXC_INFORMAVALIDADE),'\",')),\n"
            + "	concat(concat('\"cpfxc_validade\":\"',CPFXC_VALIDADE),'\",')),\n"
            + "	concat(concat('\"cpfxc_contingencia\":\"',CPFXC_CONTINGENCIA),'\",')),\n"
            + "	concat(concat('\"naocpfxc_informapromo\":\"',NAOCPFXC_INFORMAPROMO),'\",')),\n"
            + "	concat(concat('\"naocpfxc_validade\":\"',NAOCPFXC_VALIDADE),'\",')),\n"
            + "	concat(concat('\"naocpfxc_regras\":\"',NAOCPFXC_REGRAS),'\",')),\n"
            + "	concat(concat('\"naocpfxc_recarga\":\"',NAOCPFXC_RECARGA),'\",')),\n"
            + "	concat(concat('\"incentivo_oferta_pre\":\"',INCENTIVO_OFERTA_PRE),'\",')),\n"
            + "	concat(concat('\"fallback\":\"',FALLBACK),'\",')),\n"
            + "	concat(concat('\"jacliente_sva\":\"',JACLIENTE_SVA),'\",')),\n"
            + "	concat(concat('\"informasaldopromo\":\"',INFORMASALDOPROMO),'\",')),\n"
            + "	concat(concat('\"ofertamigrados\":\"',OFERTAMIGRADOS),'\",')),\n"
            + "	concat(concat('\"naocps_infop_ussd\":\"',NAOCPS_INFOP_USSD),'\"}'))\n"
            + ",'$') as json,ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM BO_CARTAO t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO BO_CARTAO (\n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	CPFXC_PROMOPADRAO,\n"
            + "	CPFXC_SEMRECARGA,\n"
            + "	CPFXC_CHAMADA,\n"
            + "	CPFXC_DETALHES,\n"
            + "	CPFXC_RECARGA,\n"
            + "	CPFXC_INFORMAVALIDADE,\n"
            + "	CPFXC_VALIDADE,\n"
            + "	CPFXC_CONTINGENCIA,\n"
            + "	NAOCPFXC_INFORMAPROMO,\n"
            + "	NAOCPFXC_VALIDADE,\n"
            + "	NAOCPFXC_REGRAS,\n"
            + "	NAOCPFXC_RECARGA,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	FALLBACK,\n"
            + "	JACLIENTE_SVA,\n"
            + "	INFORMASALDOPROMO,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCPS_INFOP_USSD,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	CPFXC_PROMOPADRAO,\n"
            + "	CPFXC_SEMRECARGA,\n"
            + "	CPFXC_CHAMADA,\n"
            + "	CPFXC_DETALHES,\n"
            + "	CPFXC_RECARGA,\n"
            + "	CPFXC_INFORMAVALIDADE,\n"
            + "	CPFXC_VALIDADE,\n"
            + "	CPFXC_CONTINGENCIA,\n"
            + "	NAOCPFXC_INFORMAPROMO,\n"
            + "	NAOCPFXC_VALIDADE,\n"
            + "	NAOCPFXC_REGRAS,\n"
            + "	NAOCPFXC_RECARGA,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	FALLBACK,\n"
            + "	JACLIENTE_SVA,\n"
            + "	INFORMASALDOPROMO,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCPS_INFOP_USSD,\n"
            + "	?,\n"
            + "   DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + "	IDBENEFICIO VARCHAR2(2500) PATH '$.idbeneficio',\n"
            + "	IDPROGRAMA VARCHAR2(2500) PATH '$.idprograma',\n"
            + "	DDD VARCHAR2(2500) PATH '$.ddd',\n"
            + "	CPFXC_PROMOPADRAO VARCHAR2(2500) PATH '$.cpfxc_promopadrao',\n"
            + "	CPFXC_SEMRECARGA VARCHAR2(2500) PATH '$.cpfxc_semrecarga',\n"
            + "	CPFXC_CHAMADA VARCHAR2(2500) PATH '$.cpfxc_chamada',\n"
            + "	CPFXC_DETALHES VARCHAR2(2500) PATH '$.cpfxc_detalhes',\n"
            + "	CPFXC_RECARGA VARCHAR2(2500) PATH '$.cpfxc_recarga',\n"
            + "	CPFXC_INFORMAVALIDADE VARCHAR2(2500) PATH '$.cpfxc_informavalidade',\n"
            + "	CPFXC_VALIDADE VARCHAR2(2500) PATH '$.cpfxc_validade',\n"
            + "	CPFXC_CONTINGENCIA VARCHAR2(2500) PATH '$.cpfxc_contingencia',\n"
            + "	NAOCPFXC_INFORMAPROMO VARCHAR2(2500) PATH '$.naocpfxc_informapromo',\n"
            + "	NAOCPFXC_VALIDADE VARCHAR2(2500) PATH '$.naocpfxc_validade',\n"
            + "	NAOCPFXC_REGRAS VARCHAR2(2500) PATH '$.naocpfxc_regras',\n"
            + "	NAOCPFXC_RECARGA VARCHAR2(2500) PATH '$.naocpfxc_recarga',\n"
            + "	INCENTIVO_OFERTA_PRE VARCHAR2(2500) PATH '$.incentivo_oferta_pre',\n"
            + "	FALLBACK VARCHAR2(2500) PATH '$.fallback',\n"
            + "	JACLIENTE_SVA VARCHAR2(2500) PATH '$.jacliente_sva',\n"
            + "	INFORMASALDOPROMO VARCHAR2(2500) PATH '$.informasaldopromo',\n"
            + "	OFERTAMIGRADOS VARCHAR2(2500) PATH '$.ofertamigrados',\n"
            + "	NAOCPS_INFOP_USSD VARCHAR2(2500) PATH '$.naocps_infop_ussd',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE BO_CARTAO SET \n"
            + "	IDBENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDBENEFICIO as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDBENEFICIO',json NUMBER(38,0) PATH '$.idbeneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	IDPROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDPROGRAMA as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDPROGRAMA',json NUMBER(38,0) PATH '$.idprograma')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DDD as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DDD',json VARCHAR2(2500) PATH '$.ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CPFXC_PROMOPADRAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CPFXC_PROMOPADRAO as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CPFXC_PROMOPADRAO',json VARCHAR2(2500) PATH '$.cpfxc_promopadrao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CPFXC_SEMRECARGA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CPFXC_SEMRECARGA as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CPFXC_SEMRECARGA',json VARCHAR2(2500) PATH '$.cpfxc_semrecarga')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CPFXC_CHAMADA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CPFXC_CHAMADA as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CPFXC_CHAMADA',json VARCHAR2(2500) PATH '$.cpfxc_chamada')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CPFXC_DETALHES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CPFXC_DETALHES as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CPFXC_DETALHES',json VARCHAR2(2500) PATH '$.cpfxc_detalhes')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CPFXC_RECARGA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CPFXC_RECARGA as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CPFXC_RECARGA',json VARCHAR2(2500) PATH '$.cpfxc_recarga')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CPFXC_INFORMAVALIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CPFXC_INFORMAVALIDADE as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CPFXC_INFORMAVALIDADE',json VARCHAR2(2500) PATH '$.cpfxc_informavalidade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CPFXC_VALIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CPFXC_VALIDADE as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CPFXC_VALIDADE',json VARCHAR2(2500) PATH '$.cpfxc_validade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	CPFXC_CONTINGENCIA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT CPFXC_CONTINGENCIA as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.CPFXC_CONTINGENCIA',json VARCHAR2(2500) PATH '$.cpfxc_contingencia')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCPFXC_INFORMAPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCPFXC_INFORMAPROMO as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCPFXC_INFORMAPROMO',json VARCHAR2(2500) PATH '$.naocpfxc_informapromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCPFXC_VALIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCPFXC_VALIDADE as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCPFXC_VALIDADE',json VARCHAR2(2500) PATH '$.naocpfxc_validade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCPFXC_REGRAS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCPFXC_REGRAS as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCPFXC_REGRAS',json VARCHAR2(2500) PATH '$.naocpfxc_regras')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCPFXC_RECARGA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCPFXC_RECARGA as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCPFXC_RECARGA',json VARCHAR2(2500) PATH '$.naocpfxc_recarga')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	INCENTIVO_OFERTA_PRE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO_OFERTA_PRE as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO_OFERTA_PRE',json VARCHAR2(2500) PATH '$.incentivo_oferta_pre')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	FALLBACK = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT FALLBACK as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.FALLBACK',json VARCHAR2(2500) PATH '$.fallback')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	JACLIENTE_SVA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SVA as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SVA',json VARCHAR2(2500) PATH '$.jacliente_sva')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	INFORMASALDOPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INFORMASALDOPROMO as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INFORMASALDOPROMO',json VARCHAR2(2500) PATH '$.informasaldopromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTAMIGRADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTAMIGRADOS as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTAMIGRADOS',json VARCHAR2(2500) PATH '$.ofertamigrados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCPS_INFOP_USSD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCPS_INFOP_USSD as coluna,jsonEdit,json FROM BO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCPS_INFOP_USSD',json VARCHAR2(2500) PATH '$.naocps_infop_ussd')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO BO_CARTAO (\n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	CPFXC_PROMOPADRAO,\n"
            + "	CPFXC_SEMRECARGA,\n"
            + "	CPFXC_CHAMADA,\n"
            + "	CPFXC_DETALHES,\n"
            + "	CPFXC_RECARGA,\n"
            + "	CPFXC_INFORMAVALIDADE,\n"
            + "	CPFXC_VALIDADE,\n"
            + "	CPFXC_CONTINGENCIA,\n"
            + "	NAOCPFXC_INFORMAPROMO,\n"
            + "	NAOCPFXC_VALIDADE,\n"
            + "	NAOCPFXC_REGRAS,\n"
            + "	NAOCPFXC_RECARGA,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	FALLBACK,\n"
            + "	JACLIENTE_SVA,\n"
            + "	INFORMASALDOPROMO,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCPS_INFOP_USSD,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	CPFXC_PROMOPADRAO,\n"
            + "	CPFXC_SEMRECARGA,\n"
            + "	CPFXC_CHAMADA,\n"
            + "	CPFXC_DETALHES,\n"
            + "	CPFXC_RECARGA,\n"
            + "	CPFXC_INFORMAVALIDADE,\n"
            + "	CPFXC_VALIDADE,\n"
            + "	CPFXC_CONTINGENCIA,\n"
            + "	NAOCPFXC_INFORMAPROMO,\n"
            + "	NAOCPFXC_VALIDADE,\n"
            + "	NAOCPFXC_REGRAS,\n"
            + "	NAOCPFXC_RECARGA,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	FALLBACK,\n"
            + "	JACLIENTE_SVA,\n"
            + "	INFORMASALDOPROMO,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCPS_INFOP_USSD,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM BO_CARTAO WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO BO_CARTAO (\n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	CPFXC_PROMOPADRAO,\n"
            + "	CPFXC_SEMRECARGA,\n"
            + "	CPFXC_CHAMADA,\n"
            + "	CPFXC_DETALHES,\n"
            + "	CPFXC_RECARGA,\n"
            + "	CPFXC_INFORMAVALIDADE,\n"
            + "	CPFXC_VALIDADE,\n"
            + "	CPFXC_CONTINGENCIA,\n"
            + "	NAOCPFXC_INFORMAPROMO,\n"
            + "	NAOCPFXC_VALIDADE,\n"
            + "	NAOCPFXC_REGRAS,\n"
            + "	NAOCPFXC_RECARGA,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	FALLBACK,\n"
            + "	JACLIENTE_SVA,\n"
            + "	INFORMASALDOPROMO,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCPS_INFOP_USSD,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	CPFXC_PROMOPADRAO,\n"
            + "	CPFXC_SEMRECARGA,\n"
            + "	CPFXC_CHAMADA,\n"
            + "	CPFXC_DETALHES,\n"
            + "	CPFXC_RECARGA,\n"
            + "	CPFXC_INFORMAVALIDADE,\n"
            + "	CPFXC_VALIDADE,\n"
            + "	CPFXC_CONTINGENCIA,\n"
            + "	NAOCPFXC_INFORMAPROMO,\n"
            + "	NAOCPFXC_VALIDADE,\n"
            + "	NAOCPFXC_REGRAS,\n"
            + "	NAOCPFXC_RECARGA,\n"
            + "	INCENTIVO_OFERTA_PRE,\n"
            + "	FALLBACK,\n"
            + "	JACLIENTE_SVA,\n"
            + "	INFORMASALDOPROMO,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCPS_INFOP_USSD,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM BO_CARTAO WHERE ID IN (?))";

    public static final String APROVAR
            = "t1.IDBENEFICIO = t2.IDBENEFICIO,\n"
            + "t1.IDPROGRAMA = t2.IDPROGRAMA,\n"
            + "t1.DDD = t2.DDD,\n"
            + "t1.CPFXC_PROMOPADRAO = t2.CPFXC_PROMOPADRAO,\n"
            + "t1.CPFXC_SEMRECARGA = t2.CPFXC_SEMRECARGA,\n"
            + "t1.CPFXC_CHAMADA = t2.CPFXC_CHAMADA,\n"
            + "t1.CPFXC_DETALHES = t2.CPFXC_DETALHES,\n"
            + "t1.CPFXC_RECARGA = t2.CPFXC_RECARGA,\n"
            + "t1.CPFXC_INFORMAVALIDADE = t2.CPFXC_INFORMAVALIDADE,\n"
            + "t1.CPFXC_VALIDADE = t2.CPFXC_VALIDADE,\n"
            + "t1.CPFXC_CONTINGENCIA = t2.CPFXC_CONTINGENCIA,\n"
            + "t1.NAOCPFXC_INFORMAPROMO = t2.NAOCPFXC_INFORMAPROMO,\n"
            + "t1.NAOCPFXC_VALIDADE = t2.NAOCPFXC_VALIDADE,\n"
            + "t1.NAOCPFXC_REGRAS = t2.NAOCPFXC_REGRAS,\n"
            + "t1.NAOCPFXC_RECARGA = t2.NAOCPFXC_RECARGA,\n"
            + "t1.INCENTIVO_OFERTA_PRE = t2.INCENTIVO_OFERTA_PRE,\n"
            + "t1.FALLBACK = t2.FALLBACK,\n"
            + "t1.JACLIENTE_SVA = t2.JACLIENTE_SVA,\n"
            + "t1.INFORMASALDOPROMO = t2.INFORMASALDOPROMO,\n"
            + "t1.OFERTAMIGRADOS = t2.OFERTAMIGRADOS,\n"
            + "t1.NAOCPS_INFOP_USSD = t2.NAOCPS_INFOP_USSD,\n"
            + "t1.HISTORY = t2.HISTORY";

}
