/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author mpma0
 */
public class TabelaPromocoesCartao {

    public static final String SELECT
            = "SELECT JSON_QUERY(\n"
            + " concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(\n"
            + " concat(concat('{\"tb_id_beneficio\":\"',TB_ID_BENEFICIO),'\",'),\n"
            + " concat(concat('\"tb_id_programa\":\"',TB_ID_PROGRAMA),'\",')),\n"
            + " concat(concat('\"tb_id_oferta\":\"',TB_ID_OFERTA),'\",')),\n"
            + " concat(concat('\"tb_ddd\":\"',TB_DDD),'\",')),\n"
            + " concat(concat('\"tb_regiao\":\"',TB_REGIAO),'\",')),\n"
            + " concat(concat('\"incentivo1\":\"',INCENTIVO1),'\",')),\n"
            + " concat(concat('\"incentivo2\":\"',INCENTIVO2),'\",')),\n"
            + " concat(concat('\"outrosplanos\":\"',OUTROSPLANOS),'\",')),\n"
            + " concat(concat('\"ofertapromo1\":\"',OFERTAPROMO1),'\",')),\n"
            + " concat(concat('\"ofertapromo2\":\"',OFERTAPROMO2),'\",')),\n"
            + " concat(concat('\"tb_nome_promocao\":\"',TB_NOME_PROMOCAO),'\",')),\n"
            + " concat(concat('\"tb_tipo_promo\":\"',TB_TIPO_PROMO),'\",')),\n"
            + " concat(concat('\"tb_sn_elegivel_nova_promo\":\"',TB_SN_ELEGIVEL_NOVA_PROMO),'\",')),\n"
            + " concat(concat('\"tb_taxaadesao\":\"',TB_TAXAADESAO),'\",')),\n"
            + " concat(concat('\"tb_sn_elegivel_estendida\":\"',TB_SN_ELEGIVEL_ESTENDIDA),'\",')),\n"
            + " concat(concat('\"tb_dt_inicio_promo\":\"',TB_DT_INICIO_PROMO),'\",')),\n"
            + " concat(concat('\"tb_dt_fim_promo\":\"',TB_DT_FIM_PROMO),'\",')),\n"
            + " concat(concat('\"tb_tipo_bonus\":\"',TB_TIPO_BONUS),'\",')),\n"
            + " concat(concat('\"tb_recarga_min\":\"',TB_RECARGA_MIN),'\",')),\n"
            + " concat(concat('\"tb_recarga_max\":\"',TB_RECARGA_MAX),'\",')),\n"
            + " concat(concat('\"tb_bonus_min\":\"',TB_BONUS_MIN),'\",')),\n"
            + " concat(concat('\"tb_bonus_max\":\"',TB_BONUS_MAX),'\",')),\n"
            + " concat(concat('\"tb_multiplicador\":\"',TB_MULTIPLICADOR),'\",')),\n"
            + " concat(concat('\"tb_sn_bonus_torpedo\":\"',TB_SN_BONUS_TORPEDO),'\",')),\n"
            + " concat(concat('\"tb_qtd_torp\":\"',TB_QTD_TORP),'\",')),\n"
            + " concat(concat('\"tb_bonus_torp\":\"',TB_BONUS_TORP),'\",')),\n"
            + " concat(concat('\"tb_prorrogacao_6_meses\":\"',TB_PRORROGACAO_6_MESES),'\",')),\n"
            + " concat(concat('\"tb_prorrogacao_12_meses\":\"',TB_PRORROGACAO_12_MESES),'\",')),\n"
            + " concat(concat('\"tb_valortaxa_6_meses\":\"',TB_VALORTAXA_6_MESES),'\",')),\n"
            + " concat(concat('\"tb_valortaxa_12_meses\":\"',TB_VALORTAXA_12_MESES),'\",')),\n"
            + " concat(concat('\"tb_id_beneficio_6_meses\":\"',TB_ID_BENEFICIO_6_MESES),'\",')),\n"
            + " concat(concat('\"tb_id_programa_6_meses\":\"',TB_ID_PROGRAMA_6_MESES),'\",')),\n"
            + " concat(concat('\"tb_id_beneficio_12_meses\":\"',TB_ID_BENEFICIO_12_MESES),'\",')),\n"
            + " concat(concat('\"tb_id_programa_12_meses\":\"',TB_ID_PROGRAMA_12_MESES),'\",')),\n"
            + " concat(concat('\"tb_bonusbolsodiferenciado\":\"',TB_BONUSBOLSODIFERENCIADO),'\",')),\n"
            + " concat(concat('\"tb_recargabolsodegrau2\":\"',TB_RECARGABOLSODEGRAU2),'\",')),\n"
            + " concat(concat('\"tb_bolsobonusdegrau2\":\"',TB_BOLSOBONUSDEGRAU2),'\",')),\n"
            + " concat(concat('\"tb_recargabolsodegrau3\":\"',TB_RECARGABOLSODEGRAU3),'\",')),\n"
            + " concat(concat('\"tb_bolsobonusdegrau3\":\"',TB_BOLSOBONUSDEGRAU3),'\",')),\n"
            + " concat(concat('\"tb_bonusligacaooimovel\":\"',TB_BONUSLIGACAOOIMOVEL),'\",')),\n"
            + " concat(concat('\"tb_bonusligacaooimovelfixo\":\"',TB_BONUSLIGACAOOIMOVELFIXO),'\",')),\n"
            + " concat(concat('\"tb_bonusligacaomix\":\"',TB_BONUSLIGACAOMIX),'\",')),\n"
            + " concat(concat('\"tb_ligacaooimovelfixo_dados\":\"',TB_LIGACAOOIMOVELFIXO_DADOS),'\",')),\n"
            + " concat(concat('\"tb_bonusligacaomix_dados\":\"',TB_BONUSLIGACAOMIX_DADOS),'\",')),\n"
            + " concat(concat('\"tb_semcarencia\":\"',TB_SEMCARENCIA),'\",')),\n"
            + " concat(concat('\"tem_bce\":\"',TEM_BCE),'\",')),\n"
            + " concat(concat('\"elegivel_promo_secundaria\":\"',ELEGIVEL_PROMO_SECUNDARIA),'\",')),\n"
            + " concat(concat('\"prioridade\":\"',PRIORIDADE),'\",')),\n"
            + " concat(concat('\"ofertar_sempromo\":\"',OFERTAR_SEMPROMO),'\",')),\n"
            + " concat(concat('\"pre_contratacao\":\"',PRE_CONTRATACAO),'\",')),\n"
            + " concat(concat('\"cobrartaxa\":\"',COBRARTAXA),'\",')),\n"
            + " concat(concat('\"tb_ussd_convertido\":\"',TB_USSD_CONVERTIDO),'\",')),\n"
            + " concat(concat('\"tb_categoria\":\"',TB_CATEGORIA),'\"}'))\n"
            + ",'$') as json,ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM TB_CARTPROMOCOES t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO TB_CARTPROMOCOES (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_ID_OFERTA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_NOME_PROMOCAO,\n"
            + "	TB_TIPO_PROMO,\n"
            + "	TB_SN_ELEGIVEL_NOVA_PROMO,\n"
            + "	TB_TAXAADESAO,\n"
            + "	TB_SN_ELEGIVEL_ESTENDIDA,\n"
            + "	TB_DT_INICIO_PROMO,\n"
            + "	TB_DT_FIM_PROMO,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	TB_RECARGA_MIN,\n"
            + "	TB_RECARGA_MAX,\n"
            + "	TB_BONUS_MIN,\n"
            + "	TB_BONUS_MAX,\n"
            + "	TB_MULTIPLICADOR,\n"
            + "	TB_SN_BONUS_TORPEDO,\n"
            + "	TB_QTD_TORP,\n"
            + "	TB_BONUS_TORP,\n"
            + "	TB_PRORROGACAO_6_MESES,\n"
            + "	TB_PRORROGACAO_12_MESES,\n"
            + "	TB_VALORTAXA_6_MESES,\n"
            + "	TB_VALORTAXA_12_MESES,\n"
            + "	TB_ID_BENEFICIO_6_MESES,\n"
            + "	TB_ID_PROGRAMA_6_MESES,\n"
            + "	TB_ID_BENEFICIO_12_MESES,\n"
            + "	TB_ID_PROGRAMA_12_MESES,\n"
            + "	TB_BONUSBOLSODIFERENCIADO,\n"
            + "	TB_RECARGABOLSODEGRAU2,\n"
            + "	TB_BOLSOBONUSDEGRAU2,\n"
            + "	TB_RECARGABOLSODEGRAU3,\n"
            + "	TB_BOLSOBONUSDEGRAU3,\n"
            + "	TB_BONUSLIGACAOOIMOVEL,\n"
            + "	TB_BONUSLIGACAOOIMOVELFIXO,\n"
            + "	TB_BONUSLIGACAOMIX,\n"
            + "	TB_LIGACAOOIMOVELFIXO_DADOS,\n"
            + "	TB_BONUSLIGACAOMIX_DADOS,\n"
            + "	TB_SEMCARENCIA,\n"
            + "	TEM_BCE,\n"
            + "	ELEGIVEL_PROMO_SECUNDARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRE_CONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_CATEGORIA,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_ID_OFERTA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_NOME_PROMOCAO,\n"
            + "	TB_TIPO_PROMO,\n"
            + "	TB_SN_ELEGIVEL_NOVA_PROMO,\n"
            + "	TB_TAXAADESAO,\n"
            + "	TB_SN_ELEGIVEL_ESTENDIDA,\n"
            + "	TB_DT_INICIO_PROMO,\n"
            + "	TB_DT_FIM_PROMO,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	TB_RECARGA_MIN,\n"
            + "	TB_RECARGA_MAX,\n"
            + "	TB_BONUS_MIN,\n"
            + "	TB_BONUS_MAX,\n"
            + "	TB_MULTIPLICADOR,\n"
            + "	TB_SN_BONUS_TORPEDO,\n"
            + "	TB_QTD_TORP,\n"
            + "	TB_BONUS_TORP,\n"
            + "	TB_PRORROGACAO_6_MESES,\n"
            + "	TB_PRORROGACAO_12_MESES,\n"
            + "	TB_VALORTAXA_6_MESES,\n"
            + "	TB_VALORTAXA_12_MESES,\n"
            + "	TB_ID_BENEFICIO_6_MESES,\n"
            + "	TB_ID_PROGRAMA_6_MESES,\n"
            + "	TB_ID_BENEFICIO_12_MESES,\n"
            + "	TB_ID_PROGRAMA_12_MESES,\n"
            + "	TB_BONUSBOLSODIFERENCIADO,\n"
            + "	TB_RECARGABOLSODEGRAU2,\n"
            + "	TB_BOLSOBONUSDEGRAU2,\n"
            + "	TB_RECARGABOLSODEGRAU3,\n"
            + "	TB_BOLSOBONUSDEGRAU3,\n"
            + "	TB_BONUSLIGACAOOIMOVEL,\n"
            + "	TB_BONUSLIGACAOOIMOVELFIXO,\n"
            + "	TB_BONUSLIGACAOMIX,\n"
            + "	TB_LIGACAOOIMOVELFIXO_DADOS,\n"
            + "	TB_BONUSLIGACAOMIX_DADOS,\n"
            + "	TB_SEMCARENCIA,\n"
            + "	TEM_BCE,\n"
            + "	ELEGIVEL_PROMO_SECUNDARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRE_CONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_CATEGORIA,\n"
            + "	?,\n"
            + " DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + "	TB_ID_BENEFICIO VARCHAR2(2500) PATH '$.tb_id_beneficio',\n"
            + "	TB_ID_PROGRAMA VARCHAR2(2500) PATH '$.tb_id_programa',\n"
            + "	TB_ID_OFERTA VARCHAR2(2500) PATH '$.tb_id_oferta',\n"
            + "	TB_DDD VARCHAR2(2500) PATH '$.tb_ddd',\n"
            + "	TB_REGIAO VARCHAR2(2500) PATH '$.tb_regiao',\n"
            + "	INCENTIVO1 VARCHAR2(2500) PATH '$.incentivo1',\n"
            + "	INCENTIVO2 VARCHAR2(2500) PATH '$.incentivo2',\n"
            + "	OUTROSPLANOS VARCHAR2(2500) PATH '$.outrosplanos',\n"
            + "	OFERTAPROMO1 VARCHAR2(2500) PATH '$.ofertapromo1',\n"
            + "	OFERTAPROMO2 VARCHAR2(2500) PATH '$.ofertapromo2',\n"
            + "	TB_NOME_PROMOCAO VARCHAR2(2500) PATH '$.tb_nome_promocao',\n"
            + "	TB_TIPO_PROMO VARCHAR2(2500) PATH '$.tb_tipo_promo',\n"
            + "	TB_SN_ELEGIVEL_NOVA_PROMO VARCHAR2(2500) PATH '$.tb_sn_elegivel_nova_promo',\n"
            + "	TB_TAXAADESAO VARCHAR2(2500) PATH '$.tb_taxaadesao',\n"
            + "	TB_SN_ELEGIVEL_ESTENDIDA VARCHAR2(2500) PATH '$.tb_sn_elegivel_estendida',\n"
            + "	TB_DT_INICIO_PROMO VARCHAR2(2500) PATH '$.tb_dt_inicio_promo',\n"
            + "	TB_DT_FIM_PROMO VARCHAR2(2500) PATH '$.tb_dt_fim_promo',\n"
            + "	TB_TIPO_BONUS VARCHAR2(2500) PATH '$.tb_tipo_bonus',\n"
            + "	TB_RECARGA_MIN VARCHAR2(2500) PATH '$.tb_recarga_min',\n"
            + "	TB_RECARGA_MAX VARCHAR2(2500) PATH '$.tb_recarga_max',\n"
            + "	TB_BONUS_MIN VARCHAR2(2500) PATH '$.tb_bonus_min',\n"
            + "	TB_BONUS_MAX VARCHAR2(2500) PATH '$.tb_bonus_max',\n"
            + "	TB_MULTIPLICADOR VARCHAR2(2500) PATH '$.tb_multiplicador',\n"
            + "	TB_SN_BONUS_TORPEDO VARCHAR2(2500) PATH '$.tb_sn_bonus_torpedo',\n"
            + "	TB_QTD_TORP VARCHAR2(2500) PATH '$.tb_qtd_torp',\n"
            + "	TB_BONUS_TORP VARCHAR2(2500) PATH '$.tb_bonus_torp',\n"
            + "	TB_PRORROGACAO_6_MESES VARCHAR2(2500) PATH '$.tb_prorrogacao_6_meses',\n"
            + "	TB_PRORROGACAO_12_MESES VARCHAR2(2500) PATH '$.tb_prorrogacao_12_meses',\n"
            + "	TB_VALORTAXA_6_MESES VARCHAR2(2500) PATH '$.tb_valortaxa_6_meses',\n"
            + "	TB_VALORTAXA_12_MESES VARCHAR2(2500) PATH '$.tb_valortaxa_12_meses',\n"
            + "	TB_ID_BENEFICIO_6_MESES VARCHAR2(2500) PATH '$.tb_id_beneficio_6_meses',\n"
            + "	TB_ID_PROGRAMA_6_MESES VARCHAR2(2500) PATH '$.tb_id_programa_6_meses',\n"
            + "	TB_ID_BENEFICIO_12_MESES VARCHAR2(2500) PATH '$.tb_id_beneficio_12_meses',\n"
            + "	TB_ID_PROGRAMA_12_MESES VARCHAR2(2500) PATH '$.tb_id_programa_12_meses',\n"
            + "	TB_BONUSBOLSODIFERENCIADO VARCHAR2(2500) PATH '$.tb_bonusbolsodiferenciado',\n"
            + "	TB_RECARGABOLSODEGRAU2 VARCHAR2(2500) PATH '$.tb_recargabolsodegrau2',\n"
            + "	TB_BOLSOBONUSDEGRAU2 VARCHAR2(2500) PATH '$.tb_bolsobonusdegrau2',\n"
            + "	TB_RECARGABOLSODEGRAU3 VARCHAR2(2500) PATH '$.tb_recargabolsodegrau3',\n"
            + "	TB_BOLSOBONUSDEGRAU3 VARCHAR2(2500) PATH '$.tb_bolsobonusdegrau3',\n"
            + "	TB_BONUSLIGACAOOIMOVEL VARCHAR2(2500) PATH '$.tb_bonusligacaooimovel',\n"
            + "	TB_BONUSLIGACAOOIMOVELFIXO VARCHAR2(2500) PATH '$.tb_bonusligacaooimovelfixo',\n"
            + "	TB_BONUSLIGACAOMIX VARCHAR2(2500) PATH '$.tb_bonusligacaomix',\n"
            + "	TB_LIGACAOOIMOVELFIXO_DADOS VARCHAR2(2500) PATH '$.tb_ligacaooimovelfixo_dados',\n"
            + "	TB_BONUSLIGACAOMIX_DADOS VARCHAR2(2500) PATH '$.tb_bonusligacaomix_dados',\n"
            + "	TB_SEMCARENCIA VARCHAR2(2500) PATH '$.tb_semcarencia',\n"
            + "	TEM_BCE VARCHAR2(2500) PATH '$.tem_bce',\n"
            + "	ELEGIVEL_PROMO_SECUNDARIA VARCHAR2(2500) PATH '$.elegivel_promo_secundaria',\n"
            + "	PRIORIDADE VARCHAR2(2500) PATH '$.prioridade',\n"
            + "	OFERTAR_SEMPROMO VARCHAR2(2500) PATH '$.ofertar_sempromo',\n"
            + "	PRE_CONTRATACAO VARCHAR2(2500) PATH '$.pre_contratacao',\n"
            + "	COBRARTAXA VARCHAR2(2500) PATH '$.cobrartaxa',\n"
            + "	TB_USSD_CONVERTIDO VARCHAR2(2500) PATH '$.tb_ussd_convertido',\n"
            + "	TB_CATEGORIA VARCHAR2(2500) PATH '$.tb_categoria',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE TB_CARTPROMOCOES SET \n"
            + "	TB_ID_BENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_BENEFICIO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_BENEFICIO',json NUMBER(38,0) PATH '$.tb_id_beneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_ID_PROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_PROGRAMA as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_PROGRAMA',json NUMBER(38,0) PATH '$.tb_id_programa')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_ID_OFERTA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_OFERTA as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_OFERTA',json VARCHAR2(2500) PATH '$.tb_id_oferta')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_DDD as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_DDD',json VARCHAR2(2500) PATH '$.tb_ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_REGIAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_REGIAO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_REGIAO',json VARCHAR2(2500) PATH '$.tb_regiao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	INCENTIVO1 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO1 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO1',json VARCHAR2(2500) PATH '$.incentivo1')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	INCENTIVO2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO2 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO2',json VARCHAR2(2500) PATH '$.incentivo2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OUTROSPLANOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OUTROSPLANOS as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OUTROSPLANOS',json VARCHAR2(2500) PATH '$.outrosplanos')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTAPROMO1 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTAPROMO1 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTAPROMO1',json VARCHAR2(2500) PATH '$.ofertapromo1')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTAPROMO2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTAPROMO2 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTAPROMO2',json VARCHAR2(2500) PATH '$.ofertapromo2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_NOME_PROMOCAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_NOME_PROMOCAO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_NOME_PROMOCAO',json VARCHAR2(2500) PATH '$.tb_nome_promocao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_TIPO_PROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_TIPO_PROMO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_TIPO_PROMO',json VARCHAR2(2500) PATH '$.tb_tipo_promo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_SN_ELEGIVEL_NOVA_PROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_SN_ELEGIVEL_NOVA_PROMO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_SN_ELEGIVEL_NOVA_PROMO',json VARCHAR2(2500) PATH '$.tb_sn_elegivel_nova_promo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_TAXAADESAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_TAXAADESAO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_TAXAADESAO',json NUMBER(38,0) PATH '$.tb_taxaadesao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_SN_ELEGIVEL_ESTENDIDA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_SN_ELEGIVEL_ESTENDIDA as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_SN_ELEGIVEL_ESTENDIDA',json VARCHAR2(2500) PATH '$.tb_sn_elegivel_estendida')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_DT_INICIO_PROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_DT_INICIO_PROMO as coluna,jsonEdit,TO_DATE(json,'YY/MM/DD') as json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_DT_INICIO_PROMO',json DATE PATH '$.tb_dt_inicio_promo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_DT_FIM_PROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_DT_FIM_PROMO as coluna,jsonEdit,TO_DATE(json,'YY/MM/DD') as json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_DT_FIM_PROMO',json DATE PATH '$.tb_dt_fim_promo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_TIPO_BONUS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_TIPO_BONUS as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_TIPO_BONUS',json VARCHAR2(2500) PATH '$.tb_tipo_bonus')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_RECARGA_MIN = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_RECARGA_MIN as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_RECARGA_MIN',json NUMBER(38,0) PATH '$.tb_recarga_min')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_RECARGA_MAX = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_RECARGA_MAX as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_RECARGA_MAX',json NUMBER(38,0) PATH '$.tb_recarga_max')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BONUS_MIN = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BONUS_MIN as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BONUS_MIN',json NUMBER(38,0) PATH '$.tb_bonus_min')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BONUS_MAX = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BONUS_MAX as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BONUS_MAX',json NUMBER(38,0) PATH '$.tb_bonus_max')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_MULTIPLICADOR = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_MULTIPLICADOR as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_MULTIPLICADOR',json NUMBER(38,0) PATH '$.tb_multiplicador')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_SN_BONUS_TORPEDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_SN_BONUS_TORPEDO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_SN_BONUS_TORPEDO',json VARCHAR2(2500) PATH '$.tb_sn_bonus_torpedo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_QTD_TORP = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_QTD_TORP as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_QTD_TORP',json NUMBER(38,0) PATH '$.tb_qtd_torp')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BONUS_TORP = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BONUS_TORP as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BONUS_TORP',json NUMBER(38,0) PATH '$.tb_bonus_torp')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_PRORROGACAO_6_MESES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_PRORROGACAO_6_MESES as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_PRORROGACAO_6_MESES',json VARCHAR2(2500) PATH '$.tb_prorrogacao_6_meses')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_PRORROGACAO_12_MESES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_PRORROGACAO_12_MESES as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_PRORROGACAO_12_MESES',json VARCHAR2(2500) PATH '$.tb_prorrogacao_12_meses')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_VALORTAXA_6_MESES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_VALORTAXA_6_MESES as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_VALORTAXA_6_MESES',json NUMBER(38,0) PATH '$.tb_valortaxa_6_meses')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_VALORTAXA_12_MESES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_VALORTAXA_12_MESES as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_VALORTAXA_12_MESES',json NUMBER(38,0) PATH '$.tb_valortaxa_12_meses')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_ID_BENEFICIO_6_MESES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_BENEFICIO_6_MESES as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_BENEFICIO_6_MESES',json NUMBER(38,0) PATH '$.tb_id_beneficio_6_meses')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_ID_PROGRAMA_6_MESES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_PROGRAMA_6_MESES as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_PROGRAMA_6_MESES',json NUMBER(38,0) PATH '$.tb_id_programa_6_meses')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_ID_BENEFICIO_12_MESES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_BENEFICIO_12_MESES as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_BENEFICIO_12_MESES',json NUMBER(38,0) PATH '$.tb_id_beneficio_12_meses')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_ID_PROGRAMA_12_MESES = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_ID_PROGRAMA_12_MESES as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_ID_PROGRAMA_12_MESES',json NUMBER(38,0) PATH '$.tb_id_programa_12_meses')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BONUSBOLSODIFERENCIADO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BONUSBOLSODIFERENCIADO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BONUSBOLSODIFERENCIADO',json VARCHAR2(2500) PATH '$.tb_bonusbolsodiferenciado')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_RECARGABOLSODEGRAU2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_RECARGABOLSODEGRAU2 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_RECARGABOLSODEGRAU2',json NUMBER(38,0) PATH '$.tb_recargabolsodegrau2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BOLSOBONUSDEGRAU2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BOLSOBONUSDEGRAU2 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BOLSOBONUSDEGRAU2',json NUMBER(38,0) PATH '$.tb_bolsobonusdegrau2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_RECARGABOLSODEGRAU3 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_RECARGABOLSODEGRAU3 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_RECARGABOLSODEGRAU3',json NUMBER(38,0) PATH '$.tb_recargabolsodegrau3')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BOLSOBONUSDEGRAU3 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BOLSOBONUSDEGRAU3 as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BOLSOBONUSDEGRAU3',json NUMBER(38,0) PATH '$.tb_bolsobonusdegrau3')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BONUSLIGACAOOIMOVEL = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BONUSLIGACAOOIMOVEL as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BONUSLIGACAOOIMOVEL',json VARCHAR2(2500) PATH '$.tb_bonusligacaooimovel')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BONUSLIGACAOOIMOVELFIXO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BONUSLIGACAOOIMOVELFIXO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BONUSLIGACAOOIMOVELFIXO',json VARCHAR2(2500) PATH '$.tb_bonusligacaooimovelfixo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BONUSLIGACAOMIX = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BONUSLIGACAOMIX as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BONUSLIGACAOMIX',json VARCHAR2(2500) PATH '$.tb_bonusligacaomix')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_LIGACAOOIMOVELFIXO_DADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_LIGACAOOIMOVELFIXO_DADOS as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_LIGACAOOIMOVELFIXO_DADOS',json VARCHAR2(2500) PATH '$.tb_ligacaooimovelfixo_dados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_BONUSLIGACAOMIX_DADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_BONUSLIGACAOMIX_DADOS as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_BONUSLIGACAOMIX_DADOS',json VARCHAR2(2500) PATH '$.tb_bonusligacaomix_dados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_SEMCARENCIA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_SEMCARENCIA as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_SEMCARENCIA',json VARCHAR2(2500) PATH '$.tb_semcarencia')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TEM_BCE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TEM_BCE as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TEM_BCE',json VARCHAR2(2500) PATH '$.tem_bce')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	ELEGIVEL_PROMO_SECUNDARIA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT ELEGIVEL_PROMO_SECUNDARIA as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.ELEGIVEL_PROMO_SECUNDARIA',json VARCHAR2(2500) PATH '$.elegivel_promo_secundaria')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	PRIORIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT PRIORIDADE as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.PRIORIDADE',json VARCHAR2(2500) PATH '$.prioridade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTAR_SEMPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTAR_SEMPROMO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTAR_SEMPROMO',json VARCHAR2(2500) PATH '$.ofertar_sempromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	PRE_CONTRATACAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT PRE_CONTRATACAO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.PRE_CONTRATACAO',json VARCHAR2(2500) PATH '$.pre_contratacao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	COBRARTAXA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT COBRARTAXA as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.COBRARTAXA',json VARCHAR2(2500) PATH '$.cobrartaxa')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_USSD_CONVERTIDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_USSD_CONVERTIDO as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_USSD_CONVERTIDO',json VARCHAR2(2500) PATH '$.tb_ussd_convertido')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_CATEGORIA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_CATEGORIA as coluna,jsonEdit,json FROM TB_CARTPROMOCOES,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_CATEGORIA',json VARCHAR2(2500) PATH '$.tb_categoria')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO TB_CARTPROMOCOES (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_ID_OFERTA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_NOME_PROMOCAO,\n"
            + "	TB_TIPO_PROMO,\n"
            + "	TB_SN_ELEGIVEL_NOVA_PROMO,\n"
            + "	TB_TAXAADESAO,\n"
            + "	TB_SN_ELEGIVEL_ESTENDIDA,\n"
            + "	TB_DT_INICIO_PROMO,\n"
            + "	TB_DT_FIM_PROMO,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	TB_RECARGA_MIN,\n"
            + "	TB_RECARGA_MAX,\n"
            + "	TB_BONUS_MIN,\n"
            + "	TB_BONUS_MAX,\n"
            + "	TB_MULTIPLICADOR,\n"
            + "	TB_SN_BONUS_TORPEDO,\n"
            + "	TB_QTD_TORP,\n"
            + "	TB_BONUS_TORP,\n"
            + "	TB_PRORROGACAO_6_MESES,\n"
            + "	TB_PRORROGACAO_12_MESES,\n"
            + "	TB_VALORTAXA_6_MESES,\n"
            + "	TB_VALORTAXA_12_MESES,\n"
            + "	TB_ID_BENEFICIO_6_MESES,\n"
            + "	TB_ID_PROGRAMA_6_MESES,\n"
            + "	TB_ID_BENEFICIO_12_MESES,\n"
            + "	TB_ID_PROGRAMA_12_MESES,\n"
            + "	TB_BONUSBOLSODIFERENCIADO,\n"
            + "	TB_RECARGABOLSODEGRAU2,\n"
            + "	TB_BOLSOBONUSDEGRAU2,\n"
            + "	TB_RECARGABOLSODEGRAU3,\n"
            + "	TB_BOLSOBONUSDEGRAU3,\n"
            + "	TB_BONUSLIGACAOOIMOVEL,\n"
            + "	TB_BONUSLIGACAOOIMOVELFIXO,\n"
            + "	TB_BONUSLIGACAOMIX,\n"
            + "	TB_LIGACAOOIMOVELFIXO_DADOS,\n"
            + "	TB_BONUSLIGACAOMIX_DADOS,\n"
            + "	TB_SEMCARENCIA,\n"
            + "	TEM_BCE,\n"
            + "	ELEGIVEL_PROMO_SECUNDARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRE_CONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_CATEGORIA,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_ID_OFERTA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_NOME_PROMOCAO,\n"
            + "	TB_TIPO_PROMO,\n"
            + "	TB_SN_ELEGIVEL_NOVA_PROMO,\n"
            + "	TB_TAXAADESAO,\n"
            + "	TB_SN_ELEGIVEL_ESTENDIDA,\n"
            + "	TB_DT_INICIO_PROMO,\n"
            + "	TB_DT_FIM_PROMO,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	TB_RECARGA_MIN,\n"
            + "	TB_RECARGA_MAX,\n"
            + "	TB_BONUS_MIN,\n"
            + "	TB_BONUS_MAX,\n"
            + "	TB_MULTIPLICADOR,\n"
            + "	TB_SN_BONUS_TORPEDO,\n"
            + "	TB_QTD_TORP,\n"
            + "	TB_BONUS_TORP,\n"
            + "	TB_PRORROGACAO_6_MESES,\n"
            + "	TB_PRORROGACAO_12_MESES,\n"
            + "	TB_VALORTAXA_6_MESES,\n"
            + "	TB_VALORTAXA_12_MESES,\n"
            + "	TB_ID_BENEFICIO_6_MESES,\n"
            + "	TB_ID_PROGRAMA_6_MESES,\n"
            + "	TB_ID_BENEFICIO_12_MESES,\n"
            + "	TB_ID_PROGRAMA_12_MESES,\n"
            + "	TB_BONUSBOLSODIFERENCIADO,\n"
            + "	TB_RECARGABOLSODEGRAU2,\n"
            + "	TB_BOLSOBONUSDEGRAU2,\n"
            + "	TB_RECARGABOLSODEGRAU3,\n"
            + "	TB_BOLSOBONUSDEGRAU3,\n"
            + "	TB_BONUSLIGACAOOIMOVEL,\n"
            + "	TB_BONUSLIGACAOOIMOVELFIXO,\n"
            + "	TB_BONUSLIGACAOMIX,\n"
            + "	TB_LIGACAOOIMOVELFIXO_DADOS,\n"
            + "	TB_BONUSLIGACAOMIX_DADOS,\n"
            + "	TB_SEMCARENCIA,\n"
            + "	TEM_BCE,\n"
            + "	ELEGIVEL_PROMO_SECUNDARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRE_CONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_CATEGORIA,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM TB_CARTPROMOCOES WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO TB_CARTPROMOCOES (\n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_ID_OFERTA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_NOME_PROMOCAO,\n"
            + "	TB_TIPO_PROMO,\n"
            + "	TB_SN_ELEGIVEL_NOVA_PROMO,\n"
            + "	TB_TAXAADESAO,\n"
            + "	TB_SN_ELEGIVEL_ESTENDIDA,\n"
            + "	TB_DT_INICIO_PROMO,\n"
            + "	TB_DT_FIM_PROMO,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	TB_RECARGA_MIN,\n"
            + "	TB_RECARGA_MAX,\n"
            + "	TB_BONUS_MIN,\n"
            + "	TB_BONUS_MAX,\n"
            + "	TB_MULTIPLICADOR,\n"
            + "	TB_SN_BONUS_TORPEDO,\n"
            + "	TB_QTD_TORP,\n"
            + "	TB_BONUS_TORP,\n"
            + "	TB_PRORROGACAO_6_MESES,\n"
            + "	TB_PRORROGACAO_12_MESES,\n"
            + "	TB_VALORTAXA_6_MESES,\n"
            + "	TB_VALORTAXA_12_MESES,\n"
            + "	TB_ID_BENEFICIO_6_MESES,\n"
            + "	TB_ID_PROGRAMA_6_MESES,\n"
            + "	TB_ID_BENEFICIO_12_MESES,\n"
            + "	TB_ID_PROGRAMA_12_MESES,\n"
            + "	TB_BONUSBOLSODIFERENCIADO,\n"
            + "	TB_RECARGABOLSODEGRAU2,\n"
            + "	TB_BOLSOBONUSDEGRAU2,\n"
            + "	TB_RECARGABOLSODEGRAU3,\n"
            + "	TB_BOLSOBONUSDEGRAU3,\n"
            + "	TB_BONUSLIGACAOOIMOVEL,\n"
            + "	TB_BONUSLIGACAOOIMOVELFIXO,\n"
            + "	TB_BONUSLIGACAOMIX,\n"
            + "	TB_LIGACAOOIMOVELFIXO_DADOS,\n"
            + "	TB_BONUSLIGACAOMIX_DADOS,\n"
            + "	TB_SEMCARENCIA,\n"
            + "	TEM_BCE,\n"
            + "	ELEGIVEL_PROMO_SECUNDARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRE_CONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_CATEGORIA,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	TB_ID_BENEFICIO,\n"
            + "	TB_ID_PROGRAMA,\n"
            + "	TB_ID_OFERTA,\n"
            + "	TB_DDD,\n"
            + "	TB_REGIAO,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_NOME_PROMOCAO,\n"
            + "	TB_TIPO_PROMO,\n"
            + "	TB_SN_ELEGIVEL_NOVA_PROMO,\n"
            + "	TB_TAXAADESAO,\n"
            + "	TB_SN_ELEGIVEL_ESTENDIDA,\n"
            + "	TB_DT_INICIO_PROMO,\n"
            + "	TB_DT_FIM_PROMO,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	TB_RECARGA_MIN,\n"
            + "	TB_RECARGA_MAX,\n"
            + "	TB_BONUS_MIN,\n"
            + "	TB_BONUS_MAX,\n"
            + "	TB_MULTIPLICADOR,\n"
            + "	TB_SN_BONUS_TORPEDO,\n"
            + "	TB_QTD_TORP,\n"
            + "	TB_BONUS_TORP,\n"
            + "	TB_PRORROGACAO_6_MESES,\n"
            + "	TB_PRORROGACAO_12_MESES,\n"
            + "	TB_VALORTAXA_6_MESES,\n"
            + "	TB_VALORTAXA_12_MESES,\n"
            + "	TB_ID_BENEFICIO_6_MESES,\n"
            + "	TB_ID_PROGRAMA_6_MESES,\n"
            + "	TB_ID_BENEFICIO_12_MESES,\n"
            + "	TB_ID_PROGRAMA_12_MESES,\n"
            + "	TB_BONUSBOLSODIFERENCIADO,\n"
            + "	TB_RECARGABOLSODEGRAU2,\n"
            + "	TB_BOLSOBONUSDEGRAU2,\n"
            + "	TB_RECARGABOLSODEGRAU3,\n"
            + "	TB_BOLSOBONUSDEGRAU3,\n"
            + "	TB_BONUSLIGACAOOIMOVEL,\n"
            + "	TB_BONUSLIGACAOOIMOVELFIXO,\n"
            + "	TB_BONUSLIGACAOMIX,\n"
            + "	TB_LIGACAOOIMOVELFIXO_DADOS,\n"
            + "	TB_BONUSLIGACAOMIX_DADOS,\n"
            + "	TB_SEMCARENCIA,\n"
            + "	TEM_BCE,\n"
            + "	ELEGIVEL_PROMO_SECUNDARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRE_CONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_CATEGORIA,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM TB_CARTPROMOCOES WHERE ID IN (?))";

    public static final String APROVAR
            = "t1.TB_BONUS_TORP = t2.TB_BONUS_TORP,\n"
            + "t1.TB_PRORROGACAO_6_MESES = t2.TB_PRORROGACAO_6_MESES,\n"
            + "t1.TB_PRORROGACAO_12_MESES = t2.TB_PRORROGACAO_12_MESES,\n"
            + "t1.TB_VALORTAXA_6_MESES = t2.TB_VALORTAXA_6_MESES,\n"
            + "t1.TB_VALORTAXA_12_MESES = t2.TB_VALORTAXA_12_MESES,\n"
            + "t1.TB_ID_BENEFICIO_6_MESES = t2.TB_ID_BENEFICIO_6_MESES,\n"
            + "t1.TB_ID_PROGRAMA_6_MESES = t2.TB_ID_PROGRAMA_6_MESES,\n"
            + "t1.TB_ID_BENEFICIO_12_MESES = t2.TB_ID_BENEFICIO_12_MESES,\n"
            + "t1.TB_ID_PROGRAMA_12_MESES = t2.TB_ID_PROGRAMA_12_MESES,\n"
            + "t1.TB_BONUSBOLSODIFERENCIADO = t2.TB_BONUSBOLSODIFERENCIADO,\n"
            + "t1.TB_RECARGABOLSODEGRAU2 = t2.TB_RECARGABOLSODEGRAU2,\n"
            + "t1.TB_BOLSOBONUSDEGRAU2 = t2.TB_BOLSOBONUSDEGRAU2,\n"
            + "t1.TB_RECARGABOLSODEGRAU3 = t2.TB_RECARGABOLSODEGRAU3,\n"
            + "t1.TB_BOLSOBONUSDEGRAU3 = t2.TB_BOLSOBONUSDEGRAU3,\n"
            + "t1.TB_BONUSLIGACAOOIMOVEL = t2.TB_BONUSLIGACAOOIMOVEL,\n"
            + "t1.TB_BONUSLIGACAOOIMOVELFIXO = t2.TB_BONUSLIGACAOOIMOVELFIXO,\n"
            + "t1.TB_BONUSLIGACAOMIX = t2.TB_BONUSLIGACAOMIX,\n"
            + "t1.TB_LIGACAOOIMOVELFIXO_DADOS = t2.TB_LIGACAOOIMOVELFIXO_DADOS,\n"
            + "t1.TB_BONUSLIGACAOMIX_DADOS = t2.TB_BONUSLIGACAOMIX_DADOS,\n"
            + "t1.TB_SEMCARENCIA = t2.TB_SEMCARENCIA,\n"
            + "t1.TEM_BCE = t2.TEM_BCE,\n"
            + "t1.ELEGIVEL_PROMO_SECUNDARIA = t2.ELEGIVEL_PROMO_SECUNDARIA,\n"
            + "t1.PRIORIDADE = t2.PRIORIDADE,\n"
            + "t1.OFERTAR_SEMPROMO = t2.OFERTAR_SEMPROMO,\n"
            + "t1.PRE_CONTRATACAO = t2.PRE_CONTRATACAO,\n"
            + "t1.COBRARTAXA = t2.COBRARTAXA,\n"
            + "t1.TB_USSD_CONVERTIDO = t2.TB_USSD_CONVERTIDO,\n"
            + "t1.TB_CATEGORIA = t2.TB_CATEGORIA,\n"
            + "t1.HISTORY = t2.HISTORY";

}
