/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author mpma0
 */
public class TabelaPromptsOfertasPre {

    public static final String SELECT
            = "SELECT JSON_QUERY(\n"
            + " concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(\n"
            + " concat(concat('{\"id_bfpg\":\"',ID_BFPG),'\",'),\n"
            + " concat(concat('\"id_ofertaocs\":\"',ID_OFERTAOCS),'\",')),\n"
            + " concat(concat('\"ddd\":\"',DDD),'\",')),\n"
            + " concat(concat('\"jacliente_oferta\":\"',JACLIENTE_OFERTA),'\",')),\n"
            + " concat(concat('\"jacliente_sva\":\"',JACLIENTE_SVA),'\",')),\n"
            + " concat(concat('\"detalhesoferta\":\"',DETALHESOFERTA),'\",')),\n"
            + " concat(concat('\"regrarollover\":\"',REGRAROLLOVER),'\",')),\n"
            + " concat(concat('\"regrafallback\":\"',REGRAFALLBACK),'\",')),\n"
            + " concat(concat('\"ofertamigrados\":\"',OFERTAMIGRADOS),'\",')),\n"
            + " concat(concat('\"naocliente_informaoferta\":\"',NAOCLIENTE_INFORMAOFERTA),'\",')),\n"
            + " concat(concat('\"naocliente_incentivooferta\":\"',NAOCLIENTE_INCENTIVOOFERTA),'\",')),\n"
            + " concat(concat('\"incentivooferta\":\"',INCENTIVOOFERTA),'\"}'))\n"
            + ",'$') as json,ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM PROMPTS_OFERTASPRE t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO PROMPTS_OFERTASPRE (\n"
            + "	ID_BFPG,\n"
            + "	ID_OFERTAOCS,\n"
            + "	DDD,\n"
            + "	JACLIENTE_OFERTA,\n"
            + "	JACLIENTE_SVA,\n"
            + "	DETALHESOFERTA,\n"
            + "	REGRAROLLOVER,\n"
            + "	REGRAFALLBACK,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCLIENTE_INFORMAOFERTA,\n"
            + "	NAOCLIENTE_INCENTIVOOFERTA,\n"
            + "	INCENTIVOOFERTA,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + "	ID_BFPG,\n"
            + "	ID_OFERTAOCS,\n"
            + "	DDD,\n"
            + "	JACLIENTE_OFERTA,\n"
            + "	JACLIENTE_SVA,\n"
            + "	DETALHESOFERTA,\n"
            + "	REGRAROLLOVER,\n"
            + "	REGRAFALLBACK,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCLIENTE_INFORMAOFERTA,\n"
            + "	NAOCLIENTE_INCENTIVOOFERTA,\n"
            + "	INCENTIVOOFERTA,\n"
            + "	?,\n"
            + " DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + "	ID_BFPG VARCHAR2(2500) PATH '$.id_bfpg',\n"
            + "	ID_OFERTAOCS VARCHAR2(2500) PATH '$.id_ofertaocs',\n"
            + "	DDD VARCHAR2(2500) PATH '$.ddd',\n"
            + "	JACLIENTE_OFERTA VARCHAR2(2500) PATH '$.jacliente_oferta',\n"
            + "	JACLIENTE_SVA VARCHAR2(2500) PATH '$.jacliente_sva',\n"
            + "	DETALHESOFERTA VARCHAR2(2500) PATH '$.detalhesoferta',\n"
            + "	REGRAROLLOVER VARCHAR2(2500) PATH '$.regrarollover',\n"
            + "	REGRAFALLBACK VARCHAR2(2500) PATH '$.regrafallback',\n"
            + "	OFERTAMIGRADOS VARCHAR2(2500) PATH '$.ofertamigrados',\n"
            + "	NAOCLIENTE_INFORMAOFERTA VARCHAR2(2500) PATH '$.naocliente_informaoferta',\n"
            + "	NAOCLIENTE_INCENTIVOOFERTA VARCHAR2(2500) PATH '$.naocliente_incentivooferta',\n"
            + "	INCENTIVOOFERTA VARCHAR2(2500) PATH '$.incentivooferta',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE PROMPTS_OFERTASPRE SET \n"
            + "	ID_BFPG = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT ID_BFPG as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.ID_BFPG',json VARCHAR2(2500) PATH '$.id_bfpg')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	ID_OFERTAOCS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT ID_OFERTAOCS as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.ID_OFERTAOCS',json NUMBER(38,0) PATH '$.id_ofertaocs')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DDD as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DDD',json VARCHAR2(2500) PATH '$.ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	JACLIENTE_OFERTA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_OFERTA as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_OFERTA',json VARCHAR2(2500) PATH '$.jacliente_oferta')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	JACLIENTE_SVA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SVA as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SVA',json VARCHAR2(2500) PATH '$.jacliente_sva')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	DETALHESOFERTA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DETALHESOFERTA as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DETALHESOFERTA',json VARCHAR2(2500) PATH '$.detalhesoferta')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	REGRAROLLOVER = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT REGRAROLLOVER as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.REGRAROLLOVER',json VARCHAR2(2500) PATH '$.regrarollover')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	REGRAFALLBACK = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT REGRAFALLBACK as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.REGRAFALLBACK',json VARCHAR2(2500) PATH '$.regrafallback')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTAMIGRADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTAMIGRADOS as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTAMIGRADOS',json VARCHAR2(2500) PATH '$.ofertamigrados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_INFORMAOFERTA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_INFORMAOFERTA as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_INFORMAOFERTA',json VARCHAR2(2500) PATH '$.naocliente_informaoferta')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	NAOCLIENTE_INCENTIVOOFERTA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT NAOCLIENTE_INCENTIVOOFERTA as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.NAOCLIENTE_INCENTIVOOFERTA',json VARCHAR2(2500) PATH '$.naocliente_incentivooferta')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	INCENTIVOOFERTA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVOOFERTA as coluna,jsonEdit,json FROM PROMPTS_OFERTASPRE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVOOFERTA',json VARCHAR2(2500) PATH '$.incentivooferta')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO PROMPTS_OFERTASPRE (\n"
            + "	ID_BFPG,\n"
            + "	ID_OFERTAOCS,\n"
            + "	DDD,\n"
            + "	JACLIENTE_OFERTA,\n"
            + "	JACLIENTE_SVA,\n"
            + "	DETALHESOFERTA,\n"
            + "	REGRAROLLOVER,\n"
            + "	REGRAFALLBACK,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCLIENTE_INFORMAOFERTA,\n"
            + "	NAOCLIENTE_INCENTIVOOFERTA,\n"
            + "	INCENTIVOOFERTA,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	ID_BFPG,\n"
            + "	ID_OFERTAOCS,\n"
            + "	DDD,\n"
            + "	JACLIENTE_OFERTA,\n"
            + "	JACLIENTE_SVA,\n"
            + "	DETALHESOFERTA,\n"
            + "	REGRAROLLOVER,\n"
            + "	REGRAFALLBACK,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCLIENTE_INFORMAOFERTA,\n"
            + "	NAOCLIENTE_INCENTIVOOFERTA,\n"
            + "	INCENTIVOOFERTA,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM PROMPTS_OFERTASPRE WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO PROMPTS_OFERTASPRE (\n"
            + "	ID_BFPG,\n"
            + "	ID_OFERTAOCS,\n"
            + "	DDD,\n"
            + "	JACLIENTE_OFERTA,\n"
            + "	JACLIENTE_SVA,\n"
            + "	DETALHESOFERTA,\n"
            + "	REGRAROLLOVER,\n"
            + "	REGRAFALLBACK,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCLIENTE_INFORMAOFERTA,\n"
            + "	NAOCLIENTE_INCENTIVOOFERTA,\n"
            + "	INCENTIVOOFERTA,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	ID_BFPG,\n"
            + "	ID_OFERTAOCS,\n"
            + "	DDD,\n"
            + "	JACLIENTE_OFERTA,\n"
            + "	JACLIENTE_SVA,\n"
            + "	DETALHESOFERTA,\n"
            + "	REGRAROLLOVER,\n"
            + "	REGRAFALLBACK,\n"
            + "	OFERTAMIGRADOS,\n"
            + "	NAOCLIENTE_INFORMAOFERTA,\n"
            + "	NAOCLIENTE_INCENTIVOOFERTA,\n"
            + "	INCENTIVOOFERTA,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM PROMPTS_OFERTASPRE WHERE ID IN (?))";

    public static final String APROVAR
            = "	t1.ID_BFPG = t2.ID_BFPG,\n"
            + "	t1.ID_OFERTAOCS = t2.ID_OFERTAOCS,\n"
            + "	t1.DDD = t2.DDD,\n"
            + "	t1.JACLIENTE_OFERTA = t2.JACLIENTE_OFERTA,\n"
            + "	t1.JACLIENTE_SVA = t2.JACLIENTE_SVA,\n"
            + "	t1.DETALHESOFERTA = t2.DETALHESOFERTA,\n"
            + "	t1.REGRAROLLOVER = t2.REGRAROLLOVER,\n"
            + "	t1.REGRAFALLBACK = t2.REGRAFALLBACK,\n"
            + "	t1.OFERTAMIGRADOS = t2.OFERTAMIGRADOS,\n"
            + "	t1.NAOCLIENTE_INFORMAOFERTA = t2.NAOCLIENTE_INFORMAOFERTA,\n"
            + "	t1.NAOCLIENTE_INCENTIVOOFERTA = t2.NAOCLIENTE_INCENTIVOOFERTA,\n"
            + "	t1.INCENTIVOOFERTA = t2.INCENTIVOOFERTA,\n"
            + "   t1.HISTORY = t2.HISTORY";

}
