/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author Jpereirc
 */
public class TabelaBoControle {

    public static final String SELECT
            = "SELECT JSON_QUERY(\n"
            + " concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(\n"
            + " concat(concat('{\"idbeneficio\":\"',IDBENEFICIO),'\",'),\n"
            + " concat(concat('\"idprograma\":\"',IDPROGRAMA),'\",')),\n"
            + " concat(concat('\"ddd\":\"',DDD),'\",')),\n" 
            + " concat(concat('\"oicjac_promopadrao\":\"',OICJAC_PROMOPADRAO),'\",')),\n"
            + " concat(concat('\"oicjac_regras\":\"',OICJAC_REGRAS),'\",')),\n"
            + " concat(concat('\"oicjac_validade\":\"',OICJAC_VALIDADE),'\",')),\n"
            + " concat(concat('\"oicjac_saldo\":\"',OICJAC_SALDO),'\",')),\n"
            + " concat(concat('\"oicjac_conting\":\"',OICJAC_CONTING),'\",')),\n"
            + " concat(concat('\"oicnaoc_informapromo\":\"',OICNAOC_INFORMAPROMO),'\",')),\n"
            + " concat(concat('\"oicnaoc_regras\":\"',OICNAOC_REGRAS),'\",')),\n"
            + " concat(concat('\"oicnaoc_validade\":\"',OICNAOC_VALIDADE),'\",')),\n"
            + " concat(concat('\"oicconectado_incentivo\":\"',OICCONECTADO_INCENTIVO),'\",')),\n"
            + " concat(concat('\"oicconectado_incentivopromo\":\"',OICCONECTADO_INCENTIVOPROMO),'\",')),\n"
            + " concat(concat('\"jacliente_sva\":\"',JACLIENTE_SVA),'\",')),\n"
            + " concat(concat('\"oicc_incentivo_comboleto\":\"',OICC_INCENTIVO_COMBOLETO),'\",')),\n" 
            + " concat(concat('\"detalhes_ofertaretencao\":\"',DETALHES_OFERTARETENCAO),'\",')),\n" 
            + " concat(concat('\"intemdobro_jacliente\":\"',INTEMDOBRO_JACLIENTE),'\",')),\n"
            + " concat(concat('\"intemdobro_naocliente\":\"',INTEMDOBRO_NAOCLIENTE),'\",')),\n"
            + " concat(concat('\"benint_anteriordtvendaura\":\"',BENINT_ANTERIORDTVENDAURA),'\",')),\n"
            + " concat(concat('\"benint_aposdtvendaura\":\"',BENINT_APOSDTVENDAURA),'\",')),\n"
            + " concat(concat('\"fallback_controle\":\"',FALLBACK_CONTROLE),'\"}'))\n"
            + ",'$') as json,ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM BO_CONTROLE t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO BO_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " OICJAC_PROMOPADRAO,\n"
            + " OICJAC_REGRAS,\n"
            + " OICJAC_VALIDADE,\n"
            + " OICJAC_SALDO,\n"
            + " OICJAC_CONTING,\n"
            + " OICNAOC_INFORMAPROMO,\n"
            + " OICNAOC_REGRAS,\n"
            + " OICNAOC_VALIDADE,\n"
            + " OICCONECTADO_INCENTIVO,\n"
            + " OICCONECTADO_INCENTIVOPROMO,\n"
            + " JACLIENTE_SVA,\n"
            + " OICC_INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTEMDOBRO_JACLIENTE,\n"
            + " INTEMDOBRO_NAOCLIENTE,\n"
            + " BENINT_ANTERIORDTVENDAURA,\n"
            + " BENINT_APOSDTVENDAURA,\n"
            + " FALLBACK_CONTROLE,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " OICJAC_PROMOPADRAO,\n"
            + " OICJAC_REGRAS,\n"
            + " OICJAC_VALIDADE,\n"
            + " OICJAC_SALDO,\n"
            + " OICJAC_CONTING,\n"
            + " OICNAOC_INFORMAPROMO,\n"
            + " OICNAOC_REGRAS,\n"
            + " OICNAOC_VALIDADE,\n"
            + " OICCONECTADO_INCENTIVO,\n"
            + " OICCONECTADO_INCENTIVOPROMO,\n"
            + " JACLIENTE_SVA,\n"
            + " OICC_INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTEMDOBRO_JACLIENTE,\n"
            + " INTEMDOBRO_NAOCLIENTE,\n"
            + " BENINT_ANTERIORDTVENDAURA,\n"
            + " BENINT_APOSDTVENDAURA,\n"
            + " FALLBACK_CONTROLE,\n"
            + "	?,\n"
            + "   DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + " IDBENEFICIO VARCHAR2(2500) PATH '$.idbeneficio',\n"
            + " IDPROGRAMA VARCHAR2(2500) PATH '$.idprograma',\n"
            + " DDD VARCHAR2(2500) PATH '$.ddd',\n"
            + " OICJAC_PROMOPADRAO VARCHAR2(2500) PATH '$.oicjac_promopadrao',\n"
            + " OICJAC_REGRAS VARCHAR2(2500) PATH '$.oicjac_regras',\n"
            + " OICJAC_VALIDADE VARCHAR2(2500) PATH '$.oicjac_validade',\n"
            + " OICJAC_SALDO VARCHAR2(2500) PATH '$.oicjac_saldo',\n"
            + " OICJAC_CONTING VARCHAR2(2500) PATH '$.oicjac_conting',\n"
            + " OICNAOC_INFORMAPROMO VARCHAR2(2500) PATH '$.oicnaoc_informapromo',\n"
            + " OICNAOC_REGRAS VARCHAR2(2500) PATH '$.oicnaoc_regras',\n"
            + " OICNAOC_VALIDADE VARCHAR2(2500) PATH '$.oicnaoc_validade',\n"
            + " OICCONECTADO_INCENTIVO VARCHAR2(2500) PATH '$.oicconectado_incentivo',\n"
            + " OICCONECTADO_INCENTIVOPROMO VARCHAR2(2500) PATH '$.oicconectado_incentivopromo',\n"
            + " JACLIENTE_SVA VARCHAR2(2500) PATH '$.jacliente_sva',\n"
            + " OICC_INCENTIVO_COMBOLETO VARCHAR2(2500) PATH '$.oicc_incentivo_comboleto',\n"
            + " DETALHES_OFERTARETENCAO VARCHAR2(2500) PATH '$.detalhes_ofertaretencao',\n"
            + " INTEMDOBRO_JACLIENTE VARCHAR2(2500) PATH '$.intemdobro_jacliente',\n"
            + " INTEMDOBRO_NAOCLIENTE VARCHAR2(2500) PATH '$.intemdobro_naocliente',\n"
            + " BENINT_ANTERIORDTVENDAURA VARCHAR2(2500) PATH '$.benint_anteriordtvendaura',\n"
            + " BENINT_APOSDTVENDAURA VARCHAR2(2500) PATH '$.benint_aposdtvendaura',\n"
            + " FALLBACK_CONTROLE VARCHAR2(2500) PATH '$.fallback_controle',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE BO_CONTROLE SET \n"
            + "IDBENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDBENEFICIO as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDBENEFICIO',json NUMBER(38,0) PATH '$.idbeneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "IDPROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDPROGRAMA as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDPROGRAMA',json NUMBER(38,0) PATH '$.idprograma')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DDD as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DDD',json VARCHAR2(2500) PATH '$.ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICJAC_PROMOPADRAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICJAC_PROMOPADRAO as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICJAC_PROMOPADRAO',json VARCHAR2(2500) PATH '$.oicjac_promopadrao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICJAC_REGRAS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICJAC_REGRAS as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICJAC_REGRAS',json VARCHAR2(2500) PATH '$.oicjac_regras')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICJAC_VALIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICJAC_VALIDADE as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICJAC_VALIDADE',json VARCHAR2(2500) PATH '$.oicjac_validade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICJAC_SALDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICJAC_SALDO as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICJAC_SALDO',json VARCHAR2(2500) PATH '$.oicjac_saldo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICJAC_CONTING = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICJAC_CONTING as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICJAC_CONTING',json VARCHAR2(2500) PATH '$.oicjac_conting')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICNAOC_INFORMAPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICNAOC_INFORMAPROMO as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICNAOC_INFORMAPROMO',json VARCHAR2(2500) PATH '$.oicnaoc_informapromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICNAOC_REGRAS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICNAOC_REGRAS as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICNAOC_REGRAS',json VARCHAR2(2500) PATH '$.oicnaoc_regras')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICNAOC_VALIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICNAOC_VALIDADE as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICNAOC_VALIDADE',json VARCHAR2(2500) PATH '$.oicnaoc_validade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICCONECTADO_INCENTIVO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICCONECTADO_INCENTIVO as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICCONECTADO_INCENTIVO',json VARCHAR2(2500) PATH '$.oicconectado_incentivo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICCONECTADO_INCENTIVOPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICCONECTADO_INCENTIVOPROMO as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICCONECTADO_INCENTIVOPROMO',json VARCHAR2(2500) PATH '$.oicconectado_incentivopromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "JACLIENTE_SVA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT JACLIENTE_SVA as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.JACLIENTE_SVA',json VARCHAR2(2500) PATH '$.jacliente_sva')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "OICC_INCENTIVO_COMBOLETO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OICC_INCENTIVO_COMBOLETO as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OICC_INCENTIVO_COMBOLETO',json VARCHAR2(2500) PATH '$.oicc_incentivo_comboleto')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "DETALHES_OFERTARETENCAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DETALHES_OFERTARETENCAO as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DETALHES_OFERTARETENCAO',json VARCHAR2(2500) PATH '$.detalhes_ofertaretencao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "INTEMDOBRO_JACLIENTE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INTEMDOBRO_JACLIENTE as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INTEMDOBRO_JACLIENTE',json VARCHAR2(2500) PATH '$.intemdobro_jacliente')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "INTEMDOBRO_NAOCLIENTE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INTEMDOBRO_NAOCLIENTE as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INTEMDOBRO_NAOCLIENTE',json VARCHAR2(2500) PATH '$.intemdobro_naocliente')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "BENINT_ANTERIORDTVENDAURA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT BENINT_ANTERIORDTVENDAURA as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.BENINT_ANTERIORDTVENDAURA',json VARCHAR2(2500) PATH '$.benint_anteriordtvendaura')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "BENINT_APOSDTVENDAURA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT BENINT_APOSDTVENDAURA as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.BENINT_APOSDTVENDAURA',json VARCHAR2(2500) PATH '$.benint_aposdtvendaura')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "FALLBACK_CONTROLE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT FALLBACK_CONTROLE as coluna,jsonEdit,json FROM BO_CONTROLE,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.FALLBACK_CONTROLE',json VARCHAR2(2500) PATH '$.fallback_controle')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO BO_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " OICJAC_PROMOPADRAO,\n"
            + " OICJAC_REGRAS,\n"
            + " OICJAC_VALIDADE,\n"
            + " OICJAC_SALDO,\n"
            + " OICJAC_CONTING,\n"
            + " OICNAOC_INFORMAPROMO,\n"
            + " OICNAOC_REGRAS,\n"
            + " OICNAOC_VALIDADE,\n"
            + " OICCONECTADO_INCENTIVO,\n"
            + " OICCONECTADO_INCENTIVOPROMO,\n"
            + " JACLIENTE_SVA,\n"
            + " OICC_INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTEMDOBRO_JACLIENTE,\n"
            + " INTEMDOBRO_NAOCLIENTE,\n"
            + " BENINT_ANTERIORDTVENDAURA,\n"
            + " BENINT_APOSDTVENDAURA,\n"
            + " FALLBACK_CONTROLE,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " OICJAC_PROMOPADRAO,\n"
            + " OICJAC_REGRAS,\n"
            + " OICJAC_VALIDADE,\n"
            + " OICJAC_SALDO,\n"
            + " OICJAC_CONTING,\n"
            + " OICNAOC_INFORMAPROMO,\n"
            + " OICNAOC_REGRAS,\n"
            + " OICNAOC_VALIDADE,\n"
            + " OICCONECTADO_INCENTIVO,\n"
            + " OICCONECTADO_INCENTIVOPROMO,\n"
            + " JACLIENTE_SVA,\n"
            + " OICC_INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTEMDOBRO_JACLIENTE,\n"
            + " INTEMDOBRO_NAOCLIENTE,\n"
            + " BENINT_ANTERIORDTVENDAURA,\n"
            + " BENINT_APOSDTVENDAURA,\n"
            + " FALLBACK_CONTROLE,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM BO_CONTROLE WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO BO_CONTROLE (\n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " OICJAC_PROMOPADRAO,\n"
            + " OICJAC_REGRAS,\n"
            + " OICJAC_VALIDADE,\n"
            + " OICJAC_SALDO,\n"
            + " OICJAC_CONTING,\n"
            + " OICNAOC_INFORMAPROMO,\n"
            + " OICNAOC_REGRAS,\n"
            + " OICNAOC_VALIDADE,\n"
            + " OICCONECTADO_INCENTIVO,\n"
            + " OICCONECTADO_INCENTIVOPROMO,\n"
            + " JACLIENTE_SVA,\n"
            + " OICC_INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTEMDOBRO_JACLIENTE,\n"
            + " INTEMDOBRO_NAOCLIENTE,\n"
            + " BENINT_ANTERIORDTVENDAURA,\n"
            + " BENINT_APOSDTVENDAURA,\n"
            + " FALLBACK_CONTROLE,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + " IDBENEFICIO,\n"
            + " IDPROGRAMA,\n"
            + " DDD,\n"
            + " OICJAC_PROMOPADRAO,\n"
            + " OICJAC_REGRAS,\n"
            + " OICJAC_VALIDADE,\n"
            + " OICJAC_SALDO,\n"
            + " OICJAC_CONTING,\n"
            + " OICNAOC_INFORMAPROMO,\n"
            + " OICNAOC_REGRAS,\n"
            + " OICNAOC_VALIDADE,\n"
            + " OICCONECTADO_INCENTIVO,\n"
            + " OICCONECTADO_INCENTIVOPROMO,\n"
            + " JACLIENTE_SVA,\n"
            + " OICC_INCENTIVO_COMBOLETO,\n"
            + " DETALHES_OFERTARETENCAO,\n"
            + " INTEMDOBRO_JACLIENTE,\n"
            + " INTEMDOBRO_NAOCLIENTE,\n"
            + " BENINT_ANTERIORDTVENDAURA,\n"
            + " BENINT_APOSDTVENDAURA,\n"
            + " FALLBACK_CONTROLE,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM BO_CONTROLE WHERE ID IN (?))";

    public static final String APROVAR
            = "t1.IDBENEFICIO = t2.IDBENEFICIO,\n"
            + "t1.IDPROGRAMA = t2.IDPROGRAMA,\n"
            + "t1.DDD = t2.DDD,\n"
            + "t1.OICJAC_PROMOPADRAO = t2.OICJAC_PROMOPADRAO,\n"
            + "t1.OICJAC_REGRAS = t2.OICJAC_REGRAS,\n"
            + "t1.OICJAC_VALIDADE = t2.OICJAC_VALIDADE,\n"
            + "t1.OICJAC_SALDO = t2.	OICJAC_SALDO,\n"
            + "t1.OICJAC_CONTING = t2.OICJAC_CONTING,\n"
            + "t1.OICNAOC_INFORMAPROMO = t2.OICNAOC_INFORMAPROMO,\n"
            + "t1.OICNAOC_REGRAS = t2.OICNAOC_REGRAS,\n"
            + "t1.OICNAOC_VALIDADE = t2.OICNAOC_VALIDADE,\n"
            + "t1.OICCONECTADO_INCENTIVO = t2.OICCONECTADO_INCENTIVO,\n"
            + "t1.OICCONECTADO_INCENTIVOPROMO = t2.OICCONECTADO_INCENTIVOPROMO,\n"
            + "t1.JACLIENTE_SVA = t2.JACLIENTE_SVA,\n"
            + "t1.OICC_INCENTIVO_COMBOLETO = t2.OICC_INCENTIVO_COMBOLETO,\n"
            + "t1.DETALHES_OFERTARETENCAO = t2.DETALHES_OFERTARETENCAO,\n"
            + "t1.INTEMDOBRO_JACLIENTE	 = t2.INTEMDOBRO_JACLIENTE,\n"
            + "t1.INTEMDOBRO_NAOCLIENTE = t2.INTEMDOBRO_NAOCLIENTE,\n"
            + "t1.BENINT_ANTERIORDTVENDAURA = t2.BENINT_ANTERIORDTVENDAURA,\n"
            + "t1.BENINT_APOSDTVENDAURA = t2.BENINT_APOSDTVENDAURA,\n"
            + "t1.FALLBACK_CONTROLE = t2.FALLBACK_CONTROLE,\n"
            + "t1.HISTORY = t2.HISTORY";

}
