/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oi.promocoesweb.template.enums;

/**
 *
 * @author mpma0
 */
public class TabelaVoCartao {

    public static final String SELECT
            = "SELECT JSON_QUERY(\n"
            + " concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(\n"
            + " concat(concat('{\"idbeneficio\":\"',IDBENEFICIO),'\",'),\n"
            + " concat(concat('\"idprograma\":\"',IDPROGRAMA),'\",')),\n"
            + " concat(concat('\"ddd\":\"',DDD),'\",')),\n"
            + " concat(concat('\"incentivo1\":\"',INCENTIVO1),'\",')),\n"
            + " concat(concat('\"incentivo2\":\"',INCENTIVO2),'\",')),\n"
            + " concat(concat('\"outrosplanos\":\"',OUTROSPLANOS),'\",')),\n"
            + " concat(concat('\"ofertapromo1\":\"',OFERTAPROMO1),'\",')),\n"
            + " concat(concat('\"ofertapromo2\":\"',OFERTAPROMO2),'\",')),\n"
            + " concat(concat('\"tb_tipo_bonus\":\"',TB_TIPO_BONUS),'\",')),\n"
            + " concat(concat('\"data_inic\":\"',DATA_INIC),'\",')),\n"
            + " concat(concat('\"data_fim\":\"',DATA_FIM),'\",')),\n"
            + " concat(concat('\"taxaadesao\":\"',TAXAADESAO),'\",')),\n"
            + " concat(concat('\"tarifasmsdadoswifi\":\"',TARIFASMSDADOSWIFI),'\",')),\n"
            + " concat(concat('\"tarifasms\":\"',TARIFASMS),'\",')),\n"
            + " concat(concat('\"tarifadados\":\"',TARIFADADOS),'\",')),\n"
            + " concat(concat('\"tarifavoz\":\"',TARIFAVOZ),'\",')),\n"
            + " concat(concat('\"tarifavozfixo\":\"',TARIFAVOZFIXO),'\",')),\n"
            + " concat(concat('\"recargamin\":\"',RECARGAMIN),'\",')),\n"
            + " concat(concat('\"elegivel_nova_promo\":\"',ELEGIVEL_NOVA_PROMO),'\",')),\n"
            + " concat(concat('\"elegivel_promo_template_primaria\":\"',ELEGIVEL_PROMO_TEMPLATE_PRIMARIA),'\",')),\n"
            + " concat(concat('\"prioridade\":\"',PRIORIDADE),'\",')),\n"
            + " concat(concat('\"ofertar_sempromo\":\"',OFERTAR_SEMPROMO),'\",')),\n"
            + " concat(concat('\"precontratacao\":\"',PRECONTRATACAO),'\",')),\n"
            + " concat(concat('\"cobrartaxa\":\"',COBRARTAXA),'\",')),\n"
            + " concat(concat('\"tb_ussd_convertido\":\"',TB_USSD_CONVERTIDO),'\",')),\n"
            + " concat(concat('\"tb_gatilhoofertasflex\":\"',TB_GATILHOOFERTASFLEX),'\"}'))\n"
            + ",'$') as json,ID,TEMPID,HISTORY,INSERTED,DT_GMUD,DELETED FROM VO_CARTAO t WHERE (DT_GMUD IS NULL AND DELETED = 0) OR (DT_GMUD IS NOT NULL) ORDER BY INSERTED DESC NULLS LAST";

    public static final String INSERT
            = "INSERT INTO VO_CARTAO (\n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	DATA_INIC,\n"
            + "	DATA_FIM,\n"
            + "	TAXAADESAO,\n"
            + "	TARIFASMSDADOSWIFI,\n"
            + "	TARIFASMS,\n"
            + "	TARIFADADOS,\n"
            + "	TARIFAVOZ,\n"
            + "	TARIFAVOZFIXO,\n"
            + "	RECARGAMIN,\n"
            + "	ELEGIVEL_NOVA_PROMO,\n"
            + "	ELEGIVEL_PROMO_TEMPLATE_PRIMARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRECONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_GATILHOOFERTASFLEX,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD\n"
            + ")(SELECT \n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	DATA_INIC,\n"
            + "	DATA_FIM,\n"
            + "	TAXAADESAO,\n"
            + "	TARIFASMSDADOSWIFI,\n"
            + "	TARIFASMS,\n"
            + "	TARIFADADOS,\n"
            + "	TARIFAVOZ,\n"
            + "	TARIFAVOZFIXO,\n"
            + "	RECARGAMIN,\n"
            + "	ELEGIVEL_NOVA_PROMO,\n"
            + "	ELEGIVEL_PROMO_TEMPLATE_PRIMARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRECONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_GATILHOOFERTASFLEX,\n"
            + "	?,\n"
            + "   DT_GMUD\n"
            + "FROM dual, JSON_TABLE(?, '$' COLUMNS (\n"
            + "	IDBENEFICIO VARCHAR2(2500) PATH '$.idbeneficio',\n"
            + "	IDPROGRAMA VARCHAR2(2500) PATH '$.idprograma',\n"
            + "	DDD VARCHAR2(2500) PATH '$.ddd',\n"
            + "	INCENTIVO1 VARCHAR2(2500) PATH '$.incentivo1',\n"
            + "	INCENTIVO2 VARCHAR2(2500) PATH '$.incentivo2',\n"
            + "	OUTROSPLANOS VARCHAR2(2500) PATH '$.outrosplanos',\n"
            + "	OFERTAPROMO1 VARCHAR2(2500) PATH '$.ofertapromo1',\n"
            + "	OFERTAPROMO2 VARCHAR2(2500) PATH '$.ofertapromo2',\n"
            + "	TB_TIPO_BONUS VARCHAR2(2500) PATH '$.tb_tipo_bonus',\n"
            + "	DATA_INIC VARCHAR2(2500) PATH '$.data_inic',\n"
            + "	DATA_FIM VARCHAR2(2500) PATH '$.data_fim',\n"
            + "	TAXAADESAO VARCHAR2(2500) PATH '$.taxaadesao',\n"
            + "	TARIFASMSDADOSWIFI VARCHAR2(2500) PATH '$.tarifasmsdadoswifi',\n"
            + "	TARIFASMS VARCHAR2(2500) PATH '$.tarifasms',\n"
            + "	TARIFADADOS VARCHAR2(2500) PATH '$.tarifadados',\n"
            + "	TARIFAVOZ VARCHAR2(2500) PATH '$.tarifavoz',\n"
            + "	TARIFAVOZFIXO VARCHAR2(2500) PATH '$.tarifavozfixo',\n"
            + "	RECARGAMIN VARCHAR2(2500) PATH '$.recargamin',\n"
            + "	ELEGIVEL_NOVA_PROMO VARCHAR2(2500) PATH '$.elegivel_nova_promo',\n"
            + "	ELEGIVEL_PROMO_TEMPLATE_PRIMARIA VARCHAR2(2500) PATH '$.elegivel_promo_template_primaria',\n"
            + "	PRIORIDADE VARCHAR2(2500) PATH '$.prioridade',\n"
            + "	OFERTAR_SEMPROMO VARCHAR2(2500) PATH '$.ofertar_sempromo',\n"
            + "	PRECONTRATACAO VARCHAR2(2500) PATH '$.precontratacao',\n"
            + "	COBRARTAXA VARCHAR2(2500) PATH '$.cobrartaxa',\n"
            + "	TB_USSD_CONVERTIDO VARCHAR2(2500) PATH '$.tb_ussd_convertido',\n"
            + "	TB_GATILHOOFERTASFLEX VARCHAR2(2500) PATH '$.tb_gatilhoofertasflex',\n"
            + "	DT_GMUD VARCHAR2(2500) PATH '$.dt_gmud'\n"
            + ")))";

    public static final String UPDATE
            = "UPDATE VO_CARTAO SET \n"
            + "	IDBENEFICIO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDBENEFICIO as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDBENEFICIO',json NUMBER(38,0) PATH '$.idbeneficio')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	IDPROGRAMA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT IDPROGRAMA as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.IDPROGRAMA',json NUMBER(38,0) PATH '$.idprograma')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	DDD = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DDD as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DDD',json VARCHAR2(2500) PATH '$.ddd')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	INCENTIVO1 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO1 as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO1',json VARCHAR2(2500) PATH '$.incentivo1')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	INCENTIVO2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT INCENTIVO2 as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.INCENTIVO2',json VARCHAR2(2500) PATH '$.incentivo2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OUTROSPLANOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OUTROSPLANOS as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OUTROSPLANOS',json VARCHAR2(2500) PATH '$.outrosplanos')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTAPROMO1 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTAPROMO1 as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTAPROMO1',json VARCHAR2(2500) PATH '$.ofertapromo1')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTAPROMO2 = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTAPROMO2 as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTAPROMO2',json VARCHAR2(2500) PATH '$.ofertapromo2')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_TIPO_BONUS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_TIPO_BONUS as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_TIPO_BONUS',json VARCHAR2(2500) PATH '$.tb_tipo_bonus')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	DATA_INIC = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DATA_INIC as coluna,jsonEdit,TO_DATE(json,'YY/MM/DD') as json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DATA_INIC',json DATE PATH '$.data_inic')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	DATA_FIM = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT DATA_FIM as coluna,jsonEdit,TO_DATE(json,'YY/MM/DD') as json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.DATA_FIM',json DATE PATH '$.data_fim')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TAXAADESAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TAXAADESAO as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TAXAADESAO',json VARCHAR2(2500) PATH '$.taxaadesao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TARIFASMSDADOSWIFI = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFASMSDADOSWIFI as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFASMSDADOSWIFI',json VARCHAR2(2500) PATH '$.tarifasmsdadoswifi')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TARIFASMS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFASMS as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFASMS',json VARCHAR2(2500) PATH '$.tarifasms')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TARIFADADOS = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFADADOS as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFADADOS',json VARCHAR2(2500) PATH '$.tarifadados')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TARIFAVOZ = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFAVOZ as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFAVOZ',json VARCHAR2(2500) PATH '$.tarifavoz')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TARIFAVOZFIXO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TARIFAVOZFIXO as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TARIFAVOZFIXO',json VARCHAR2(2500) PATH '$.tarifavozfixo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	RECARGAMIN = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT RECARGAMIN as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.RECARGAMIN',json VARCHAR2(2500) PATH '$.recargamin')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	ELEGIVEL_NOVA_PROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT ELEGIVEL_NOVA_PROMO as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.ELEGIVEL_NOVA_PROMO',json VARCHAR2(2500) PATH '$.elegivel_nova_promo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	ELEGIVEL_PROMO_TEMPLATE_PRIMARIA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT ELEGIVEL_PROMO_TEMPLATE_PRIMARIA as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.ELEGIVEL_PROMO_TEMPLATE_PRIMARIA',json VARCHAR2(2500) PATH '$.elegivel_promo_template_primaria')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	PRIORIDADE = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT PRIORIDADE as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.PRIORIDADE',json VARCHAR2(2500) PATH '$.prioridade')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	OFERTAR_SEMPROMO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT OFERTAR_SEMPROMO as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.OFERTAR_SEMPROMO',json VARCHAR2(2500) PATH '$.ofertar_sempromo')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	PRECONTRATACAO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT PRECONTRATACAO as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.PRECONTRATACAO',json VARCHAR2(2500) PATH '$.precontratacao')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	COBRARTAXA = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT COBRARTAXA as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.COBRARTAXA',json VARCHAR2(2500) PATH '$.cobrartaxa')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_USSD_CONVERTIDO = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_USSD_CONVERTIDO as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_USSD_CONVERTIDO',json VARCHAR2(2500) PATH '$.tb_ussd_convertido')) where ID = ? order by rownum asc) where rownum = 1),\n"
            + "	TB_GATILHOOFERTASFLEX = (SELECT case when jsonedit='true' then json else coluna end FROM (SELECT TB_GATILHOOFERTASFLEX as coluna,jsonEdit,json FROM VO_CARTAO,JSON_TABLE(history, '$[*]' COLUMNS (jsonEdit VARCHAR2(2500) PATH '$.editMap.TB_GATILHOOFERTASFLEX',json VARCHAR2(2500) PATH '$.tb_gatilhoofertasflex')) where ID = ? order by rownum asc) where rownum = 1)\n"
            + ", DT_GMUD = ? WHERE ID = ?";

    public static final String UPDATEINSERT
            = "INSERT INTO VO_CARTAO (\n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	DATA_INIC,\n"
            + "	DATA_FIM,\n"
            + "	TAXAADESAO,\n"
            + "	TARIFASMSDADOSWIFI,\n"
            + "	TARIFASMS,\n"
            + "	TARIFADADOS,\n"
            + "	TARIFAVOZ,\n"
            + "	TARIFAVOZFIXO,\n"
            + "	RECARGAMIN,\n"
            + "	ELEGIVEL_NOVA_PROMO,\n"
            + "	ELEGIVEL_PROMO_TEMPLATE_PRIMARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRECONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_GATILHOOFERTASFLEX,\n"
            + "	HISTORY,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	DATA_INIC,\n"
            + "	DATA_FIM,\n"
            + "	TAXAADESAO,\n"
            + "	TARIFASMSDADOSWIFI,\n"
            + "	TARIFASMS,\n"
            + "	TARIFADADOS,\n"
            + "	TARIFAVOZ,\n"
            + "	TARIFAVOZFIXO,\n"
            + "	RECARGAMIN,\n"
            + "	ELEGIVEL_NOVA_PROMO,\n"
            + "	ELEGIVEL_PROMO_TEMPLATE_PRIMARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRECONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_GATILHOOFERTASFLEX,\n"
            + "	? HISTORY,\n"
            + "	? DT_GMUD,\n"
            + "	ID\n"
            + "FROM VO_CARTAO WHERE ID = ?)";

    public static final String DELETE
            = "INSERT INTO VO_CARTAO (\n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	DATA_INIC,\n"
            + "	DATA_FIM,\n"
            + "	TAXAADESAO,\n"
            + "	TARIFASMSDADOSWIFI,\n"
            + "	TARIFASMS,\n"
            + "	TARIFADADOS,\n"
            + "	TARIFAVOZ,\n"
            + "	TARIFAVOZFIXO,\n"
            + "	RECARGAMIN,\n"
            + "	ELEGIVEL_NOVA_PROMO,\n"
            + "	ELEGIVEL_PROMO_TEMPLATE_PRIMARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRECONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_GATILHOOFERTASFLEX,\n"
            + "	HISTORY,\n"
            + "	DELETED,\n"
            + "	DT_GMUD,\n"
            + "	TEMPID\n"
            + ")(SELECT \n"
            + "	IDBENEFICIO,\n"
            + "	IDPROGRAMA,\n"
            + "	DDD,\n"
            + "	INCENTIVO1,\n"
            + "	INCENTIVO2,\n"
            + "	OUTROSPLANOS,\n"
            + "	OFERTAPROMO1,\n"
            + "	OFERTAPROMO2,\n"
            + "	TB_TIPO_BONUS,\n"
            + "	DATA_INIC,\n"
            + "	DATA_FIM,\n"
            + "	TAXAADESAO,\n"
            + "	TARIFASMSDADOSWIFI,\n"
            + "	TARIFASMS,\n"
            + "	TARIFADADOS,\n"
            + "	TARIFAVOZ,\n"
            + "	TARIFAVOZFIXO,\n"
            + "	RECARGAMIN,\n"
            + "	ELEGIVEL_NOVA_PROMO,\n"
            + "	ELEGIVEL_PROMO_TEMPLATE_PRIMARIA,\n"
            + "	PRIORIDADE,\n"
            + "	OFERTAR_SEMPROMO,\n"
            + "	PRECONTRATACAO,\n"
            + "	COBRARTAXA,\n"
            + "	TB_USSD_CONVERTIDO,\n"
            + "	TB_GATILHOOFERTASFLEX,\n"
            + "	?,\n"
            + "	1,\n"
            + "	?, \n"
            + "	ID \n"
            + "FROM VO_CARTAO WHERE ID IN (?))";

    public static final String APROVAR
            = "t1.IDBENEFICIO = t2.IDBENEFICIO,\n"
            + "t1.IDPROGRAMA = t2.IDPROGRAMA,\n"
            + "t1.DDD = t2.DDD,\n"
            + "t1.INCENTIVO1 = t2.INCENTIVO1,\n"
            + "t1.INCENTIVO2 = t2.INCENTIVO2,\n"
            + "t1.OUTROSPLANOS = t2.OUTROSPLANOS,\n"
            + "t1.OFERTAPROMO1 = t2.OFERTAPROMO1,\n"
            + "t1.OFERTAPROMO2 = t2.OFERTAPROMO2,\n"
            + "t1.TB_TIPO_BONUS = t2.TB_TIPO_BONUS,\n"
            + "t1.DATA_INIC = t2.DATA_INIC,\n"
            + "t1.DATA_FIM = t2.DATA_FIM,\n"
            + "t1.TAXAADESAO = t2.TAXAADESAO,\n"
            + "t1.TARIFASMSDADOSWIFI = t2.TARIFASMSDADOSWIFI,\n"
            + "t1.TARIFASMS = t2.TARIFASMS,\n"
            + "t1.TARIFADADOS = t2.TARIFADADOS,\n"
            + "t1.TARIFAVOZ = t2.TARIFAVOZ,\n"
            + "t1.TARIFAVOZFIXO = t2.TARIFAVOZFIXO,\n"
            + "t1.RECARGAMIN = t2.RECARGAMIN,\n"
            + "t1.ELEGIVEL_NOVA_PROMO = t2.ELEGIVEL_NOVA_PROMO,\n"
            + "t1.ELEGIVEL_PROMO_TEMPLATE_PRIMARIA = t2.ELEGIVEL_PROMO_TEMPLATE_PRIMARIA,\n"
            + "t1.PRIORIDADE = t2.PRIORIDADE,\n"
            + "t1.OFERTAR_SEMPROMO = t2.OFERTAR_SEMPROMO,\n"
            + "t1.PRECONTRATACAO = t2.PRECONTRATACAO,\n"
            + "t1.COBRARTAXA = t2.COBRARTAXA,\n"
            + "t1.TB_USSD_CONVERTIDO = t2.TB_USSD_CONVERTIDO,\n"
            + "t1.TB_GATILHOOFERTASFLEX = t2.TB_GATILHOOFERTASFLEX,\n"
            + "t1.HISTORY = t2.HISTORY";

}
